### ISSUE TITLE
ABI attached from geoinheritance for Sam Bacha to view

### ISSUE THREAD

**Issue by geoinheritance** [poanetwork/token-wizard#1003]
[tokenwizard_Rinkeby_0xCE3BD1Bdc9Bb0E381eC05c9D5DF3DcCbACbe8aF7.zip](https://github.com/poanetwork/token-wizard/files/2157032/tokenwizard_Rinkeby_0xCE3BD1Bdc9Bb0E381eC05c9D5DF3DcCbACbe8aF7.zip)
[Token Wizard_MainNet.pdf](https://github.com/poanetwork/token-wizard/files/2157050/Token.Wizard_MainNet.pdf)

Please, see Parameters in .pdf. 
The Decimal used was: 18.
Coin Name: USER PAY
Ticker: UP

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Mainnet*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/crowdsale/?addr=0x97847D9d2F36BC01612D8a4D6226aAc320586Ff2&networkID=1*

### Do you have screenshots showing the problem?

*Yes, I do*

### Do you see errors in the dev console? If yes, please include a screenshot
![image](https://user-images.githubusercontent.com/39395850/42194656-e4b9a35c-7e6c-11e8-809a-dec39aeb514e.png)

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*
__________________________________
Hi Sam Bacha,
Please find the ABI for geoinheritance
![image](https://user-images.githubusercontent.com/39395850/42194650-da05e830-7e6c-11e8-8cce-6da16177a461.png)

---
[003_CrowdsaleTokenExt.zip](https://github.com/poanetwork/token-wizard/files/2157000/003_CrowdsaleTokenExt.zip)

**Comment by vbaranov** [comment]
https://gitter.im/poanetwork/ico-wizard?at=5b3b6a073d8f71623d589d58
