### ISSUE TITLE
WAS NOT ABLE TO DISTRIBUTE THE RESERVED TOKENS AND FINALIZE

### ISSUE THREAD

**Issue by geoinheritance** [poanetwork/token-wizard#1009]
If you are reporting a problem with Token Wizard, please include the following information:

@igorbarinov, thanks for your efforts, I  have taken step manually by using the method's signature sending:

Amount: 0

to: 0xce3bd1bdc9bb0e381ec05c9d5df3dccbacbe8af7

and data:
0x29ff4f5300000000000000000000000033a89cd95f588e9240408a2ef9353e2ec8bef038

The transaction was successful and the Button for DISTRIBUTE RESERVED TOKEN was enabled while the FINALIZATION Button was disabled BUT when I clicked on the  DISTRIBUTE RESERVED TOKEN, it pop-up a message as shown in the screen shot below: "WAS NOT ABLE TO DISTRIBUTE RESERVED TOKENS"

Please, what can we do to resolve this issue NOW.

NB:
https://github.com/poanetwork/token-wizard/wiki/Set-release-agent. Using token contract address: 0xce3bd1bdc9bb0e381ec05c9d5df3dccbacbe8af7. Last finalize agent contract: 0x33a89cd95f588e9240408a2ef9353e2ec8bef038. After doing this transaction 

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Mainnet*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/crowdsale/?addr=0x97847D9d2F36BC01612D8a4D6226aAc320586Ff2&networkID=1*

### Do you have screenshots showing the problem?
Yes, I do.
![image](https://user-images.githubusercontent.com/39395850/42235874-f8095b94-7ef0-11e8-9ac0-559baf4611d2.png)

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@geoinheritance 

You should do one more tx manually because you didn't finish deployment process with Token Wizard.
This step: https://github.com/poanetwork/token-wizard/wiki/Set-mint-agent
In your case you should make only one tx: you need to set finalize agent as a mint agent of your token contract.
Target token contract: `0xce3bd1bdc9bb0e381ec05c9d5df3dccbacbe8af7`
Address of finalize agent: `0x33a89cd95f588e9240408a2ef9353e2ec8bef038`
