### ISSUE TITLE
(Bug)Mincap is ignored in current tier if user has already bought tokens  in previous tier.

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1010]
The issue actual for whitelisted investors also

Steps for reproduce:
1. Create MintedCapped crowdsale : 2 tiers, with minCap
2. Buy minCap in 1st tier
3. Wait until 2nd tier starts
4. Buy amount less than minCap from the same account

Expected result:
 - investor should not be allowed to buy less than minCap since he hasn't  yet bought  in 2nd tier;
 - minCap should be individual for each tier

Actual result:
 - investor able to buy less than minCap if he has bought in previous tier;
 - Contribution page: zero minContribution value displayed

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

minCap: `0xa2eb3e10cd3eb5d0d758ea844e5eec46c96269c5440f2013ba6f40ae79d85d77`
whitelisted:`0xf18ca643185f2f7d2dfc2c7c007d0ddd72b9c093b96132a092e5c8730d105473`
`Ropsten`

### If you were able to create it, what is the URL of your crowdsale?

*local*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-07-04 at 04 03 49" src="https://user-images.githubusercontent.com/14067096/42273950-c38ad8d0-7f3f-11e8-9e29-977373a986aa.png">
<img width="1440" alt="screen shot 2018-07-04 at 04 05 02" src="https://user-images.githubusercontent.com/14067096/42273952-c5c5daa0-7f3f-11e8-93c4-4237576a2854.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No

---

**Comment by vbaranov** [comment]
@dennis00010011b does this issue still exist?

**Comment by dennis00010011b** [comment]
@vbaranov  Yes, this issue still exist

**Comment by vbaranov** [comment]
@dennis00010011b it won't be fixed from Auth-os side. We should leave the functionality of global min cap as is. Please update corresponding e2e test. Please post the link to commit with e2e fix here and then we could close the issue.

**Comment by dennis00010011b** [comment]
e2e tests updated 
https://github.com/poanetwork/token-wizard-test-automation/commit/9cef9c9fffe3232b044c069ad2bc4a571bdeff7a
