### ISSUE TITLE
(Bug) Minted-Multitier: allow owner to finalize before end of crowdsale if all tokens were sold in latest tier

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1026]
Scenario:  
 - MintedCapped strategy, miltitier crowdsale
 - 1st tier: not all  tokens were sold 
 -  latest tier: all tokens  were sold before time expired 

Problem: in this case owner can't finalize and has to wait  until crowdsale will be ended . But there is no reason to wait  since all tokens were sold and investors can't buy anymore.

Solution: change condition for finalization.
Now:
    - all tokens were sold  in all tiers OR latest tier's time is expired
Should be:
   - all tokens were sold in latest tier  OR latest tier's time is expired
---

**Comment by vbaranov** [comment]
We should change the logic of `canFinalize()` function:
https://github.com/poanetwork/token-wizard/blob/894b500958781a539b5a6784f845544594449532/src/components/manage/index.js#L492

Fix should cover only these conditions: Minted Capped stategy, we are at the last tier and tier has not ended.

When the owner should be able to finalize (assuming conditions above):
if `getCurrentTierInfo.tier_tokens_remaining` is equal 0 or `isCrowdsaleFull.is_crowdsale_full` is true.
