### ISSUE TITLE
(Bug) Contribution page:countdown timer has incorrect status after finalization

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1029]
Steps:
1. Create  crowdsale with any  parameter, ex. :Minted, 1 tier, duration 2 min, minCap
2. Wait until crowdsale ended
3. As an owner open manage page and finalize 
4. Open contribution page and observe countdown timer.

Expected result: 
 -timer's status is "CROWDSALE HAS BEEN FINALIZED""

Actual result: 
 -timer's status is "CROWDSALE HAS ENDED"

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*localhost*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-07-11 at 00 08 37" src="https://user-images.githubusercontent.com/14067096/42556205-b78fd908-849f-11e8-9538-5f621802fc91.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No
---

**Comment by mariano-aguero** [comment]
@dennis00010011b mmm I tried to reproduce the problem without success
Can you confirm if it keeps happening? Maybe I missed some step
Thanks!

![screenshot_20180711_153024](https://user-images.githubusercontent.com/1144028/42592336-8b6b51ec-851f-11e8-9d41-e28e0dc34839.png)

**Comment by dennis00010011b** [comment]
Not reproducible in branch 2.0

**Comment by dennis00010011b** [comment]
It is again reproducible in branch 2.0
http://localhost:3000/contribute?addr=0xa82dd65d279a54be6fed602d47c5941a7b0c621e&networkID=3
Proxy address `0xa82dd65d279a54be6fed602d47c5941a7b0c621e ` , Ropsten

**Comment by dennis00010011b** [comment]
@mariano-aguero 
It  still reproducible for Dutch strategy. I think it can be fixed together   with https://github.com/poanetwork/token-wizard/issues/1049
