### ISSUE TITLE
(Bug) Reserved addresses are not initialized if list length  > 20

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1048]
Steps:
1. Start creating  Minted capped crowdsale, decimals =18, 1 tier, no whitelist
2.  In Step 2:  add 21 reserved addresses from *. csv file 
```
0x66f537cCD03f21c58172602B919884A442A3c313,percentage,4511707483.49603
0x665772109Eb2dc9F5B7c28F987Ec58949d4Eeb87,percentage,5703652631.602385
0x693d436da2c3C11341149522E5F6d0390B363197,tokens,1788191146.7779398
0x67737e0046b05D2553ad1021A02d957D9c854C00,percentage,3813647171.476058
0x20372dffd12d7b012FF44c9DBae70E5e1aE47C73,percentage,6519551480.223114
0x2BCDBBd0Df231e9C35F3a27a4b9F4E631DD6f8AB,percentage,6587800412.130846
0xc4C92D54E2136d7A72F4f738B3FA69Df7b479821,percentage,6802360751.615493
0x2bD96eA633e8BcB468732c68B2CD632BfF4D79Db,tokens,758413595.514329
0x848822D9101ecF8731B09CF52d4a034123FF7F97,percentage,6696003885.57482
0x866623622b19D8603F54d0aF23236759DCeB48d9,tokens,159797903.39822885
0x46fe103Be22C370E2D4143e6b61D1769017b48F0,percentage,7351028916.256665
0x063376DDB05d9e0E0D3761D0D962f9d31F9F6035,percentage,7103593263.293569
0xc6fD167492BeDf4B4f83e84FeCf9483027565650,percentage,2176445015.874138
0x1595F0a0dE18aE149081aA28b2F51aa5619e3523,percentage,8405737163.361933
0xb51454306fAa9A3Cf0505a22dff85d5b4EC13B3F,tokens,1792235377.7930033
0x7A317D210de8201C8623a0f35d44Eb34D8115B45,tokens,6421660777.500122
0x91c93F00F32898269336734Fe0611C1E9CB12d0A,percentage,3777298132.521336
0x61B748ccD326dEF03dE119d74c81391050dFe021,percentage,7330715514.135273
0x24952775eE2c842ea624991a0A422f1B0AcecA84,percentage,4928816077.592806
0xB848714c08acC2D32511C5F93F7BCcd43112F3cb,percentage,7209626039.05291
0x08C9f711d326CaCB341DDBb406BB67475817DAd3,percentage,281316414.4389435
 ```
3. Complete deployment, check if `Register addresses for Reserved Tokens` transaction  is skipped in Step 4

Expected result : 
 -  user should be able to add more than 21 reserved addresses 
OR  warning  'EXCEED THE LIMIT   OF RESERVED ADDRESSES  etc ....  ' should be displayed  in Step 2

Actual result:
 -  Reserved addresses are not initialized if list length  > 20

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?
*n/a*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-07-16 at 23 14 16" src="https://user-images.githubusercontent.com/14067096/42800677-ac5a5872-8951-11e8-97ff-7f522b8e6f2d.png">

### Do you see errors in the dev console? If yes, please include a screenshot

---

**Comment by vbaranov** [comment]
@dennis00010011b does it relate to `2.0` dev version? If yes, please, add the corresponding label.
