### ISSUE TITLE
(Bug) Minted, Dutch: Whitelisted addresses are not initialized if list length > 60

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1052]
Steps:
1. Start creating Minted (or Dutch) crowdsale, decimals =18, 1 tier, whitelisted
2. In Step 3: add 61 whitelisted addresses from `*. csv` file:
https://drive.google.com/open?id=1XpOw_lqxZE6G5k0qAwWbhT2MTcTxFsWm
3. Complete deployment, check if `Register whitelisted addresses` transaction is skipped in Step 4

Expected result :
 - user should be able to create crowdsale with more than 61 whitelisted addresses
OR 
 -  should be restriction of length of whitelisted list  in Step 3

Actual result:
 - Whitelisted  addresses are not initialized if list length > 60 (for both strategy)

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*
Proxy address: `0xbbe7f8062c2d6214af0451d8b4c3526ad88986ba`
ExecID: `0x116fea137db6e131133e7f2bab296045d8f41cc5607279db17b218cab0929a51 `

### If you were able to create it, what is the URL of your crowdsale?
http://localhost:3000/contribute?addr=0xbbe7f8062c2d6214af0451d8b4c3526ad88986ba&networkID=3

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-07-18 at 09 56 41" src="https://user-images.githubusercontent.com/14067096/42896850-09317e00-8a73-11e8-83f2-7377d4a771bd.png">
<img width="1440" alt="screen shot 2018-07-18 at 09 47 48" src="https://user-images.githubusercontent.com/14067096/42896854-0cab76da-8a73-11e8-8e77-c167c82444df.png">

### Do you see errors in the dev console? If yes, please include a screenshot
No

---

**Comment by vbaranov** [comment]
@dennis00010011b do you have the Etherscan link to the failed transaction to add a big number of items into the whitelist in Ropsten?
