### ISSUE TITLE
(Bug) Minted: 2nd tier has incorrect rate

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1055]
Steps:
1. Create crowdsale, Minted,no whitelist, 2 tiers, decimals =18:
  ```
   - 1st tier: rate =100,  supply=100, minCap =0
   - 2nd tier: rate =200, supply=100, minCap =0 
```
2. Wait until 2nd tier starts and buy 10 tokens as an **owner** (I have waited until 10 minutes after 2nd tier start before the purchase for exclude a propagation time). Check Eth amount for transaction (in metamask window)
3. Observe contribution page after transaction

Expected result:
 - transaction amount should be: ```value/rate=10/200=0.05 Eth```

Actual result:
 - transaction amount is `0.100` Eth
 - owners balance is `20` tokens after transaction

Issue is not reproducible for non-owner account

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*ganache, local deployment*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?
**crowdsale parameters**
<img width="1440" alt="screen shot 2018-07-20 at 04 17 42" src="https://user-images.githubusercontent.com/14067096/43000014-b1ed217c-8bd4-11e8-9895-b08a56a3bca5.png">

**1 st  transaction**
<img width="1440" alt="screen shot 2018-07-20 at 04 14 24" src="https://user-images.githubusercontent.com/14067096/42999879-4d4fc832-8bd4-11e8-8da0-3ff7060a3a39.png">
**After 1st transaction**
<img width="1440" alt="screen shot 2018-07-20 at 04 16 26" src="https://user-images.githubusercontent.com/14067096/42999910-69a40f8e-8bd4-11e8-8070-2b42dd29724a.png">

**2nd transaction**
<img width="1440" alt="screen shot 2018-07-20 at 04 16 47" src="https://user-images.githubusercontent.com/14067096/42999939-84bf3b9a-8bd4-11e8-8159-b279ccd35d9b.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by mariano-aguero** [comment]
Wait until this PR #1058  is closed

**Comment by mariano-aguero** [comment]
I did some tests with the branch issue#1012 and the problem is solved in this branch
![screenshot_20180726_122731](https://user-images.githubusercontent.com/1144028/43271997-543ae122-90cf-11e8-9390-e93b1910f274.png)

**Comment by fernandomg** [comment]
@dennis00010011b @mariano-aguero #1012 (PR #1058) just closed.
