### ISSUE TITLE
Sorry! The Compiled Contract ByteCode for 'CrowdsaleTokenExt' does NOT match the Contract Creation Code for

### ISSUE THREAD

**Issue by ShemiHazah** [poanetwork/token-wizard#1059]
Im getting this when trying to verify a contract code on etherscan:

 Note: Contract was created during Txn# [0x08c39f1a5028a7691764397f9441c0c5890026515b7e51a9e29ac752b68670eb]
 Result: Does not match the input creation bytecode found at this address

Sorry! The Compiled Contract ByteCode for 'CrowdsaleTokenExt' does NOT match the Contract Creation Code for [0x7CC62d8E80Be9bEa3947F3443aD136f50f75b505].

Contract name(s) found: 'CrowdsaleTokenExt' , 'ERC20' , 'ERC20Basic' , 'MintableTokenExt' , 'Ownable' , 'ReleasableToken' , 'SafeMath' , 'SafeMathLibExt' , 'StandardToken' , 'UpgradeAgent' , 'UpgradeableToken' 
Unable to Verify Contract source code.

I already verify the SafeMathLib, Flatpricing, MintedToken and ReservedToken (I only have 5 files in the wizzard zip (both txt and sol, 10 files total) , I tried everything and keeps failing. Please help me.

- I checked the compiler version and I was able to verify the other 4 contracts (SafeMathLib, Flatpricing, MintedToken and ReservedToken)
- I tried both options:     :SafeMathLib and SafeMathLib (without :)
- Tried to enable or disable optimization (same results)

Screenshot: http://knekted.net/wp-content/uploads/2018/07/fail.png
I have days trying to do this with same results, thanks in advance.

**Comment by vbaranov** [comment]
@ShemiHazah 
- The version of the compiler is `v.0.4.11`
- Optimization should be enabled
- contractName is CrowdsaleTokenExt
- the source code is from .zip downloaded from publish step of Token Wizard
- Etherscan substitutes ABI encoded parameters itself
- SafeMathLib (without :)

**Comment by vbaranov** [comment]
@ShemiHazah did it help you?

**Comment by vbaranov** [comment]
Closed due to no response from the author
