### ISSUE TITLE
The continue button on token setup not working nor is it showing certain boxes

### ISSUE THREAD

**Issue by dylanhaupert1** [poanetwork/token-wizard#1060]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

I have tried the kovan networ, and the sokel network

### If you were able to create it, what is the URL of your crowdsale

NA

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/37154404/43206351-6c043298-901d-11e8-80de-e5dccdb22f91.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

![image](https://user-images.githubusercontent.com/37154404/43206295-444fb326-901d-11e8-91f2-b5dcc275e8c9.png)

![image](https://user-images.githubusercontent.com/37154404/43206605-10f7a190-901e-11e8-8ea0-10e0eaa6b768.png)

the only thing i could see was that javascript isn't enabled but i have enabled for the app and site

![image](https://user-images.githubusercontent.com/37154404/43206535-deb59700-901d-11e8-8060-7a8ba27ada3e.png)

---

**Comment by dennis00010011b** [comment]
@dylanhaupert1 
Could you please provide Chrome version and Windows version?
I can't reproduce issue with Chrome 68.0.3440.75, Windows 10 Home 1607, OS Build 14393.693

**Comment by dylanhaupert1** [comment]
hello i have Google Chrome Version 67.0.3396.99 
 and windows 10 Enterprise 1803 OS build 17134.165

**Comment by vbaranov** [comment]
@dylanhaupert1 did you close and reopen Chrome after enabling of javascript for TW? If no, try this.
