### ISSUE TITLE
Why doesn't it work for me?

### ISSUE THREAD

**Issue by xryptopolis** [poanetwork/token-wizard#1074]
Hello,

I have spend around 80$ on trying to submit +50 transactions for a multi tier crowdsale.
Without success.

So now I was trying a 1 tier crowdsale with 13 transactions to submit.
The first transaction was submitted successfully but the second one is awaiting with an estimated confirmation time of more than 1 days, with a fee of 1.31$.
Are my fees to low?

Would somebody be willing to do the crowdsale for me if I send eth for the fees?

Thanks for helping.
rgds
walt

**Comment by vbaranov** [comment]
Recommended gas price is high (61Gwei) in Main Ethereum network now. You can check it here https://ethgasstation.info/. Be sure, that you are using the recommended gas price for your transactions. Token Wizard chooses the slowest (and cheapest at the same time) option of gas price to send transaction. Gas price is configured at step 3 of Token Wizard:

![2018-08-09 18 49 55](https://user-images.githubusercontent.com/4341812/43910275-09e4a23e-9c05-11e8-9539-103fbcaee590.png)

**Comment by xryptopolis** [comment]
Hi Victor, thank you very much for the advice.

I have now found out the 2 mistakes I made.
For those new to Token Wizard, please do not make the same ones; 

1)Do NOT refresh your page untill the whole process is finished.
If you do you will basically lose whatever money you've put in.

2) If you submit the first contract for let's say $0.6, do not be surprised to see the fee popping to 8$ to be able to submit the second one. This all depends on the complexity of the contracts. Some are more complex than others, so the fees go up and down. The fees for submitting the third contract could go down again to 1$, don't worry. Probably the indication of total estimated costs at the beginning of the process is a good one to watch.

Thanks again Victor for your prompt input.
And may the force be with POA Network.

Rgds,
w
