### ISSUE TITLE
Issues with final step

### ISSUE THREAD

**Issue by katsutori** [poanetwork/token-wizard#1077]
If you are reporting a problem with Token Wizard, please include the following information:

Ii can't get pass the final step of launching

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

Can't get to final step

### Do you have screenshots showing the problem?

yes
https://imgur.com/a/RBeMP2k

### Do you see errors in the dev console? If yes, please include a screenshot

MetaMask - RPC Error: Error: gas required exceeds allowance or always failing transaction
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1723632
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1273654
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:369926
    at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:388157)

*Your answer*

---

**Comment by katsutori** [comment]
Yes

**Comment by katsutori** [comment]
I skipped the last tx. We should be good, right?

**Comment by vbaranov** [comment]
@katsutori  Did you successfully proceed to the crowdsale page? If yes, your crowdsale should work.

**Comment by katsutori** [comment]
Yes
