### ISSUE TITLE
(Bug) Step 4-Minted: file `Auth-os_addresses.txt`  doesn't contain adresses of `Sale manager` and `Token manager` contracts

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1118]
Downloaded file `Auth-os_addresses.txt` (Minted crowdsale) should contain  two more contracts in `Crowdsale` section :
 1. Sale manager ( .env var REACT_APP_MINTED_CAPPED_CROWDSALE_MANAGER_ADDRESS)
 2. Token manager ( .env var REACT_APP_MINTED_CAPPED_TOKEN_MANAGER_ADDRESS)

<img width="1440" alt="screen shot 2018-08-30 at 10 57 40 am" src="https://user-images.githubusercontent.com/14067096/44869913-96f19080-ac43-11e8-8fd2-35c8366537c8.png">

---

**Comment by mariano-aguero** [comment]
Worked on PR #1117

**Comment by mariano-aguero** [comment]
Closes by PR #1117
