### ISSUE TITLE
Sorry! The Compiled Contract ByteCode for 'contract AsX' does NOT match the Contract Creation Code

### ISSUE THREAD

**Issue by Tommynitroz** [poanetwork/token-wizard#1132]
I have a problem on Etherscan.io Ropsten. When I want to verify my contract it keeps saying: 
Sorry! The Compiled Contract ByteCode for 'contract AsX' does NOT match the Contract Creation Code for [0x981f646a6b0d053bbc58afca76fe44ce1ea1d836].

Contract name(s) found: 'ApproveAndCallFallBack' , 'AsX' , 'ERC20Interface' , 'Owned' , 'SafeMath' 
Unable to Verify Contract source code.
![image](https://user-images.githubusercontent.com/43153040/45323014-2fdcb180-b54a-11e8-9c1e-ad2269c7cac4.png)

Anyone that can help me out?

**Comment by vbaranov** [comment]
The issue doesn’t relate to Token Wizard.
