### ISSUE TITLE
Token-wizard Failure at stepFour: Unhandled Rejection (TypeError): abi.forEach is not a function findConstructor

### ISSUE THREAD

**Issue by pratimasethi** [poanetwork/token-wizard#1137]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

kovan

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

yes

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab
![image](https://user-images.githubusercontent.com/3583447/45406306-be088300-b683-11e8-9f0b-73e5e8a85ebb.png)

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

[tokenwizard.12092018.log.zip](https://github.com/poanetwork/token-wizard/files/2373829/tokenwizard.12092018.log.zip)

---

**Comment by vbaranov** [comment]
Closed due to https://gitter.im/poanetwork/ico-wizard?at=5b98c009e481f854a6a761fc
