### ISSUE TITLE
Can the token wizard work with KYC and whitelisting platforms?

### ISSUE THREAD

**Issue by katsutori** [poanetwork/token-wizard#1147]
Is there a way to get the wizard to work with a KYC service provider? If not, can a token sale be setup for white list only and the white list can be updated at any time?

**Comment by vbaranov** [comment]
>Is there a way to get the wizard to work with a KYC service provider?

It is on your own. We don't have an integration with any 3d party KYC provider.

>If not, can a token sale be setup for white list only and the white list can be updated at any time?

Yes, 
- to make your crowdsale whitelisted, you need to swith on `enable whitelisting` flag
- to make your crowdsale editable, you need to switch on `Allow modifying` flag (for every tier, you have in your crowdsale)
![2018-09-20 12 17 45](https://user-images.githubusercontent.com/4341812/45809135-27197780-bcd0-11e8-88b7-60199c54a879.png)

And you'll be able to manage the whitelist during the crowdsale through your management page, like here:

![2018-09-20 12 21 22](https://user-images.githubusercontent.com/4341812/45809273-71025d80-bcd0-11e8-9294-353426acd4f7.png)
