### ISSUE TITLE
(Bug) TW 2.0 doesn't work with Ganache-cli

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#1162]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Localhost:8545

### If you were able to create it, what is the URL of your crowdsale?

No, I was not able to deploy crowdsale. I was trying to create Minted capped crowdsale with Ganache without using any wallet. There are two problems here:
1. I see warning messages, that wallet is not installed.
2. I was not able to create crowdsale. 1st transaction to deploy Proxy contract failed. Log is attached.

Additional details:
- I've started TW2.0 with `npm run dev:minted`
- `./public/contracts` folder comprises of all needed assets: binary code, ABI and source code for Proxy.

### Do you have screenshots showing the problem?

<img width="1430" alt="2018-09-28 15 15 10" src="https://user-images.githubusercontent.com/4341812/46207814-53b53b00-c331-11e8-88d2-8659c3e6857d.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

[localhost-1538136803528.zip](https://github.com/poanetwork/token-wizard/files/2428102/localhost-1538136803528.zip)

---

**Comment by mariano-aguero** [comment]
This is happening in the branch 2.0 , but to be sure we should check this error the design integration branch too
