### ISSUE TITLE
(Fix) Warning in console after each tier's addition

### ISSUE THREAD

**Issue by gabitoesmiapodo** [poanetwork/token-wizard#1180]
See https://github.com/poanetwork/token-wizard/pull/1172#issuecomment-429499215

**Comment by mariano-aguero** [comment]
@dennis00010011b 

I can not reproduce the problem in the branch `integration/#1082-new-design`
Can you check it? I think is solved

Regards

**Comment by dennis00010011b** [comment]
Issue isn't reroducible
