### ISSUE TITLE
(Bug) User can add whitelist if supply is not set in DutchAuction Strategy

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#1183]
**Problem:** If the user adds a whitelist address before touching the 'supply' value. Values validations passes, `supply` is disabled and user can't continue.

**Solution:** Validate `maxValue` against `supply` as it's done in MintedCapped Strategy.

I think we should fix this directly in the redesign branch.

![image](https://user-images.githubusercontent.com/3315606/47099216-36c2a800-d20b-11e8-9279-cfb9e3c00038.png)
![image](https://user-images.githubusercontent.com/3315606/47099292-5d80de80-d20b-11e8-92c2-8fb443c56449.png)

**Comment by dennis00010011b** [comment]
https://github.com/poanetwork/token-wizard/pull/1172#issuecomment-430494723

**Comment by fernandomg** [comment]
Oh, thanks @dennis00010011b... I missed that. So let's have it as a separate issue. As this can be reproduced in `2.0` as well.

**Comment by mariano-aguero** [comment]
@dennis00010011b 

See https://github.com/poanetwork/token-wizard/pull/1234

Regards
