### ISSUE TITLE
(Bug) Minted crowdsale: owner able to finalize before start

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1195]
Seems like root of this issue comes from duration of crowdsale
Steps:
1. Create crowdsale: Minted,  1 tier, no whitelist, start time by default, end time= start time +(~40 hours)
2. Finish deployment
3. Open manage page as an owner, observe button 'Finalize'

Expected result: 
 - button 'Finalize' should be disabled
 - owner should not be able to finalize unless all tokens were sold or crowdsale ended

Actual result: 
 - owner able to finalize before start of crowdsale

https://www.useloom.com/share/244c700c9b2742d59c81b24949908bc8

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*localhost, xDai*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-10-22 at 7 31 51 pm" src="https://user-images.githubusercontent.com/14067096/47333903-9240cb80-d639-11e8-8b41-c774f95cd4c6.png">

### Do you see errors in the dev console? If yes, please include a screenshot

n/a

---

**Comment by mariano-aguero** [comment]
@dennis00010011b 

I used the command `npm run dev: minted`, and I could not reproduce the problem in the branch 2.0. Could you test it again? If the problem exist, could you add more information to reproduce the problem?

Thanks

**Comment by dennis00010011b** [comment]
@mariano-aguero 
I was able to reproduce issue now by setting  local machine time and date like in video
Date: 10/22/2108, time ~8:15pm

**Comment by dennis00010011b** [comment]
@mariano-aguero
I was able to reproduce issue now by setting local machine time and date like in video
Date: 10/22/2108, time ~8:15pm
