### ISSUE TITLE
(Bug) Step3: field gas price custom empty by default

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1199]
Steps:
 1. Start creating Minted (or Dutch) crowdsale
 2. Proceed to Step 3 with valid data
 3. Select gas price -> custom

Expected result: 
 - field gas price custom should has value 0.1 by default

Actual  result: 
 - field gas price empty
 - user able to continue with empty gas price custom field 

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*n/a*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

<img width="1435" alt="screen shot 2018-10-23 at 9 36 32 am" src="https://user-images.githubusercontent.com/14067096/47376418-6d833d00-d6a7-11e8-825a-50c49153f232.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*no*

---

**Comment by dennis00010011b** [comment]
This issue is reproducible again in branch https://github.com/poanetwork/token-wizard/tree/integration/%231082-new-design

Relates https://github.com/poanetwork/token-wizard/pull/1203

**Comment by mariano-aguero** [comment]
@dennis00010011b 

It seems that the commit was lost in some merge with the integration branch, added in new PR #1225
