### ISSUE TITLE
Sorry! The Compiled Contract ByteCode for ... does NOT match the Contract Creation Code for Address

### ISSUE THREAD

**Issue by LucreToken** [poanetwork/token-wizard#1205]
I have deployed my contract on the Mainnet. My contract address is 0x4ac583bb9c55658ebb17805f1cc8c1fa75c210d8

When I try to verify it here https://etherscan.io/verifyContract2 I get the following error:

Sorry! The Compiled Contract ByteCode for 'Lucre' does NOT match the Contract Creation Code for Address 0x4ac583BB9c55658EBB17805F1Cc8c1Fa75c210d8.
Found the following ContractName(s) in source code: Lucre, SafeMath, StandardToken, Token. 

Here is the source code: https://github.com/LucreToken/contracts/blob/master/Lucre.sol

**Comment by vbaranov** [comment]
@LucreToken Could you post here a screenshot of the filled verification form before submission?

**Comment by LucreToken** [comment]
Here is the screenshot 
![image](https://user-images.githubusercontent.com/39747118/47858610-d878f600-ddc2-11e8-981b-2e0ebfc46288.png)

**Comment by vbaranov** [comment]
@LucreToken I mean screenshot before you clicked to "Verify" button. It is interesting, how your filled form looks like.

**Comment by LucreToken** [comment]
![image](https://user-images.githubusercontent.com/39747118/47860351-b3868200-ddc6-11e8-9e53-10b886434fe2.png)

**Comment by vbaranov** [comment]
The current repository supports only tokens created by Token Wizard.
