### ISSUE TITLE
(UI bug) White empty area behind the loader

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#1213]
After the switching from Step 2 to Step 3 behind the loader I see white empty area occupying half of a screen:

![screen shot 2018-11-06 at 12 37 01](https://user-images.githubusercontent.com/4341812/48055503-d054f800-e1c0-11e8-8c25-88ca66207e57.png)

**Comment by mariano-aguero** [comment]
@dennis00010011b 

Could you test if this keeps happening, using the branch of this pull request? 
PR: #1226
Branch:  issue#1221

Gracias
