### ISSUE TITLE
(Bug) Step4: no alert if user closes or refresh the page

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1227]
Steps:
 1. Start creating a crowdsale with any valid data
2. Proceed to Step4
3. Before first transaction will be constructed, try to refresh or close page/browser 

Expected result:
 - should be an alert 'Leave site?' 
 - how it works in branch 2.0 https://www.useloom.com/share/800c83e56ae34ba89f06ce404e24b08b

Actual result: 
 -  user is able to close/refresh the page/browser without alert (only before 1st transaction is constructed)
 - alert present if transaction isn't first

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

*no*

### Do you see errors in the dev console? If yes, please include a screenshot

*no*

---

**Comment by mariano-aguero** [comment]
@dennis00010011b  Do you want this alert to be also in step 1, step 2 and step 3?  It could be a good idea to be in all the steps . Let me now

Regards

**Comment by dennis00010011b** [comment]
@mariano-aguero
I agree, It would be good to have such alert for each step
