### ISSUE TITLE
(Bug) Investor can't contribute in 2nd tier if already has bought total supply in 1st tier

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#1235]
Issue reproducible both in branches `2.0` and `feature/#1090-apply-new-design-to-step-6-contribute`
Network : Ropsten, proxy address `0x16749780db1f1029d3a56494134733f3b2c1c49d`

Steps:
 1. Create Minted crowdsale, 2 tiers, no whitelist, mincaps = 0, tier#1 duration ~5 min
 2. Buy full supply in tier #1
 3. Wait until 2nd tier starts
 4. Try to buy from the same account

Expected result:
 - investor should be allowed to buy in 2nd tier

Actual result:
 - timer's status is 'Tier sold out'
 - button 'Contribute' is disabled
 - actually allowed to contribute from others accounts 
 - allowed to contribute if switch account to other an back

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/contribute?addr=0x16749780db1f1029d3a56494134733f3b2c1c49d&networkID=3*

### Do you have screenshots showing the problem?

*
![screenshot from 2018-11-28 00-16-35](https://user-images.githubusercontent.com/14067096/49115379-7f7c7080-f24f-11e8-9230-1c1699592e23.png)
*

### Do you see errors in the dev console? If yes, please include a screenshot

*no*

---

**Comment by gabitoesmiapodo** [comment]
@dennis00010011b @vbaranov 

Should we close this? 

See https://github.com/poanetwork/token-wizard/pull/1230#issuecomment-442309706
