### ISSUE TITLE
Make a list of testing scenarios

### ISSUE THREAD

**Issue by fvictorio** [poanetwork/token-wizard#376]
It would be useful to have a document with scenarios for manual testing. Each scenario would have a list of steps to follow and some assertions. For example:

```cucumber
Scenario: User creates a crowdsale

Given I started the application
And I opened it with a browser connected to a local testrpc
When I start a new crowdsale
And I select "Whitelist with cap"
And I type some name and ticker and put 2 in the decimals input
And I click "Continue"
And Insert 100 as Rate and 100 as Supply
And I click "Continue"
And I submit all the transactions
And I click "Continue"
Then I should be prompted to download a ZIP file with information about the crowdsale
And I should be redirected to the crowdsale page
```

Here I used [Cucumber](https://cucumber.io/), but it can be less formal. And I was very specific with the steps, but other scenarios could be shorter:

```cucumber
Scenario: User wants to buy too many tokens

Given I started the application
And I opened it with a browser connected to a local testrpc
And I created a crowdsale with 100 supply
When I go to the invest page of the crowdsale
And I insert 101 in the "Amount to invest" input
And I click "Contribute"
And I submit the transaction
Then The transaction should fail
```

There's a lot that can be done around this, but I would start with a very basic and non-exhaustive list (just the more important scenarios) and we can iterate after that.

If you want, you can just comment here a list of scenarios and I can create the `.feature` files.

---

Brief descriptions of basic scenarios that should be tested.

- Basic:
  - Users can create a crowdsale and invest
  - If a transaction is rejected during the deploy, the spinner should be hidden
  - If a crowdsale has reserved tokens, these should appear when inspecting the crowdsale contract (using mist, for example)
  - If a crowdsale has reserved tokens, these should be distributed when the crowdsale is finalized.
  - If a crowdsale has a global min cap, a contribution of less than that cap should fail.
- Whitelist:
  - If a crowdsale has whitelisted addresses, other addresses should not be allowed to buy tokens
  - If an address is whitelisted, it should not be allowed to buy less than the min value and more than the max value.

**Comment by dennis00010011b** [comment]
I started to work on test cases for manual testing
https://docs.google.com/spreadsheets/d/1nsJtlVOa9ZkHCOoBwl8eyQQzxpA0Y5ozfO4-Zu2fMUM/edit?usp=sharing

**Comment by fernandomg** [comment]
I'm closing this as seems to be solved. Please, reopen if not.
