### ISSUE TITLE
ico wizard issue setting up erc20

### ISSUE THREAD

**Issue by lytlejustin0421** [poanetwork/token-wizard#413]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
main network

### If you were able to create it, what is the URL of your crowdsale?
hi! i am trying to setup an erc20 token with the ico wizard and have gotten as far as paying for the contracts and then it spins endlessly , i have a dev tools console screenshot that says the violations , please help if possible , if i copy and paste the page to another tab it says to restart the ico wizard and dont want to lose the money i spent on contracts already. Thanks!

### Do you have screenshots showing the problem?
yes

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

yes
![screenshot 2](https://user-images.githubusercontent.com/34811228/34329810-44b84f9e-e8d4-11e7-9171-555c4684af3b.png)

---

**Comment by fvictorio** [comment]
Hi @lytlejustin0421, thanks for reporting this. I'm not being able to reproduce it. Could you please try again in Rinkeby and see if it's still happening?

Also, could you tell me which version of Google Chrome you are using?

**Comment by lytlejustin0421** [comment]
will this cost more money? i already lost my money from that token not
being reproduced correctly.....

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lytlejustin0421** [comment]
also i have no idea what rinkeby is

**Comment by fvictorio** [comment]
Rinkeby is an ethereum blockchain used for testing purposes, ether costs no money there.

To use it, open MetaMask and select Rinkeby as the current network (left top corner):

![image](https://user-images.githubusercontent.com/417134/34359285-6b7b9002-ea35-11e7-8f37-8b4054b42016.png)

You can get ether here: https://faucet.rinkeby.io/, or import an account with this private key and you should have some ether: `4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d`

**Comment by igorbarinov** [comment]
Also, you could use our testnet Sokol, which is Kovan-compatible
- select Custom RPC
- add https://sokol.poa.network
- get free coins in faucet https://faucet-sokol.herokuapp.com/

**Comment by lytlejustin0421** [comment]
We already created a token with a different platform since it was time
sensitive but thanks for  your effort and if your willing to refund the
fees that would be appreciated. Thanks for your time.

**Comment by igorbarinov** [comment]
If you would like to get the refund you need to cooperate with us. E.g. we need to reproduce the issue.

**Comment by vbaranov** [comment]
It is not reproducible
