### ISSUE TITLE
Crowdsale contract stuck in between

### ISSUE THREAD

**Issue by DavidNish** [poanetwork/token-wizard#445]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Main network
### If you were able to create it, what is the URL of your crowdsale?

I have created it but it doesn't allow me to download the files and continue

### Do you have screenshots showing the problem?

Yes
![image](https://user-images.githubusercontent.com/35144176/34616677-fa0ba4ca-f25e-11e7-8eaa-9d008e0535cc.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

yes
![image](https://user-images.githubusercontent.com/35144176/34616602-c88b4068-f25e-11e7-817b-ce2a1ce10fad.png)
![image](https://user-images.githubusercontent.com/35144176/34616632-dc83d79c-f25e-11e7-9e7a-dd705f22fb94.png)

---

**Comment by igorbarinov** [comment]
@vbaranov @fernandomg please take a look at the issue

**Comment by DavidNish** [comment]
Owner Address : 0x051204720e956E3e3f83613952eE2bD4E01F33D5

Meta Mask Images
![image](https://user-images.githubusercontent.com/35144176/34616878-85f33660-f25f-11e7-9cba-9583713adcde.png)
![image](https://user-images.githubusercontent.com/35144176/34616886-8afc967e-f25f-11e7-9db7-bcfd52af9c63.png)
![image](https://user-images.githubusercontent.com/35144176/34616901-9488107e-f25f-11e7-863a-80218d4213f2.png)

**Comment by DavidNish** [comment]
List of Transactions made
0x8ad6bc223b3c2c3082ef085df12a30cece653a53ec0de0f87429ea726b953b18
0xb69d5154c202af1c865e55f7753c92261f94f3ea92f964b47f8eb63d4c7c4989
0x8c678255823698b3ae553bb436ded93af89220836ab7a0fcc4e97f66d91bb7da
0x0d1ccc7ad5639d7393fd0865c0e27f64fc5b77c0448c8a1c030951fecc741c3d
0x85d2318d39796f777345a132da7ccbbd5fc11ebe78a4a5023d29a50785a9c036
0x9409d422f93751cfd9b9021dd3b7d0a995744729d4303f6e837079d10ae2eb05
0x07960c72b10e59fca7d1ee8fd37615ec4255b26051aca86552eab7f38a5de041
0xd418b2444b2b763184e7cd73c44bc4a1d3e39c8dc9239f8652e68d774c75913f
0xa71c0ff6e1d79d644fddc59513ac2911569a1717e88af59f67ec18563996fc22
0x9e0ad8a6edefe3cd8d920b6e2691477cba24e8291bb609ec67b547829e4b902d
0xe2944d4386985985fd27f8e0f0f29388bcc78a20f0c7867bbdc4d3002906590d
0xcfa3d5305bfe962b6d052a32b5106dfc47d112ee2aabd15410f37f04e2345465
0x0a6d450d689a7d4f92e56f295ac219bfb8b9cdf7e7747740b88cba4816cb425f
0x022c4618885c57d3023d0be3552a7666346a77bccee5a1e280b1bc8f17ac42b0
0xb0151cfa897094fc09af7f60d7b53ffb7c80701803a35149305e748ed52e2116

**Comment by igorbarinov** [comment]
Same contract was deployed on Ropsten successfully  https://wizard.oracles.org/crowdsale?addr=0xa00FCc1F453E8b433c63aa40BD1A9ACDbC1C9377&networkID=3

**Comment by igorbarinov** [comment]
from a recreated contract on Ropsten with the same bug [icowizard_Ropsten_0x3b8f5e55cF1DdE9104C755fFE707a413057B490d.zip](https://github.com/poanetwork/ico-wizard/files/1607205/icowizard_Ropsten_0x3b8f5e55cF1DdE9104C755fFE707a413057B490d.zip)

**Comment by fernandomg** [comment]
I'm working on this... still I'm not being able to repoduce it

**Comment by igorbarinov** [comment]
@fernandomg as far as I understood it's on Foundation (mainnet) only
please send me your mainnet wallet I'll send coins to reproduce

**Comment by DavidNish** [comment]
What do you mean, you want me to send eth private keys?

**Comment by igorbarinov** [comment]
@DavidNish it's not addressed to you

**Comment by DavidNish** [comment]
@i-dobrovolsky I was too late to get that

**Comment by igorbarinov** [comment]
@DavidNish please don't mention other people who are not related to the issue

**Comment by DavidNish** [comment]
@igorbarinov sry I thought it was your handle

**Comment by vbaranov** [comment]
@DavidNish I see, that your crowdsale is not completely setup 

![2018-01-05 21 11 48](https://user-images.githubusercontent.com/4341812/34622317-c372cd18-f25d-11e7-9ce3-65b7089436a9.png)

It seems, you've signed not all transactions to setup your crowdsale. Did you interrupt any of transaction? 
Any additional details will help us to solve this problem:
- how many tiers did you setup?
- is whitelisted?
- did you setup reserved tokens?

**Comment by DavidNish** [comment]
It seems, you've signed not all transactions to setup your crowdsale. Did you interrupt any of transaction?
no, I haven't interrupted any tx. 

Any additional details will help us to solve this problem:

how many tiers did you setup?
just 1 tier
is whitelisted?
no
did you setup reserved tokens?
5% reserved tokens

**Comment by vbaranov** [comment]
@DavidNish thank you. Btw, while we are trying to reproduce your issue, this is your crowdsale page https://wizard.poa.network/crowdsale?addr=0xa0c8be78eb060c6fd85e210083e09bfc8b4fba18&networkID=1

**Comment by DavidNish** [comment]
Great, is everything working normally?

**Comment by vbaranov** [comment]
I've double checked your transactions. The number of transactions is correct. So, your crowdsale is alive. The problem affected only downloading of the file with crowdsale info.

**Comment by DavidNish** [comment]
So, how can I get those files

**Comment by DavidNish** [comment]
Confirm me once everything is fine and can start transactions over smart contract

**Comment by igorbarinov** [comment]
@vbaranov is there a way to get files or not?

@DavidNish do you want to recreate the crowdsale? why do you need files?

**Comment by vbaranov** [comment]
>is there a way to get files or not?

No. There is no way to download the files except 4th step for now. I've added the proposal to consider possibility of downloading the files from `/manage` page https://github.com/poanetwork/ico-wizard/issues/422

**Comment by igorbarinov** [comment]
@DavidNish there is no way to restore the file. Please contact me for the refund

**Comment by igorbarinov** [comment]
@vbaranov @fernandomg did we find the root cause or not?

**Comment by fernandomg** [comment]
@igorbarinov I didn't found it yet.

**Comment by DavidNish** [comment]
@igorbarinov  i need refund

**Comment by vbaranov** [comment]
The root cause of the problem is when the user confirms transaction in Metamask, and then doesn't wait for the confirmation of it and increases the gas price from Metamask and sends it again. The similar problem is described here: https://forum.poa.network/t/error-after-finish-all-signing-when-trying-to-click-continue/1123/9?u=viktorbaranov. I have added this case to the FAQ: https://github.com/poanetwork/token-wizard/wiki/FAQ#13-i-confirmed-transaction-in-metamask-and-after-some-time-of-waiting-i-see-the-message-in-metamask-taking-too-long-retry-with-a-higher-gas-price-here-should-i-increase-gas
