### ISSUE TITLE
(Bug) QR code is not working when Wizard embedded in iframe

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/token-wizard#448]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

All

### If you were able to create it, what is the URL of your crowdsale?

https://www.thebtcbtq.com/btq (scroll down)

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/424628/34647782-22da9a72-f341-11e7-9d11-b73bfd4df90a.png)

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

[www.thebtcbtq.com-1515313790741.zip](https://github.com/poanetwork/ico-wizard/files/1609589/www.thebtcbtq.com-1515313790741.zip)

---

**Comment by fernandomg** [comment]
@igorbarinov QR code is generated properly, but it's render outside of the `iframe` boundaries. Original height is set to `600px`.

![image](https://user-images.githubusercontent.com/3315606/34685654-e1dc0248-f487-11e7-9746-611fd5a114ac.png)
