### ISSUE TITLE
(Feature) Give user information about crowdsale deployment status and provide the ability to resume

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#464]
Due to the recent issues we were facing with the crowdsale deployment, I think that will be a good idea to add an informative list with each step and its status in `stepFour`

i.e.:
- [x] safeMathLibrary
- [x] token
- [x] pricingStrategy
- [ ] crowdsale (... processing)
    - [x] tier 1
    - [ ] tier 2 (... processing)
    - [ ] tier 3 (pending)
- [ ] crowdsaleAddress (pending)
- [ ] finalizeAgentABIArguments (pending)
- [ ] finalizeAgent (pending)

Also, add the ability to resume from where the process was halted.

Thus, if the user don't leave the screen or refresh it; he/she will be able to continue from where the deployment failed if for instance the Tx goes OOG, Metamask fails for any reason, and that kind of issues.

@igorbarinov @vbaranov l look forward to your comments.

**Comment by rstormsf** [comment]
@fernandomg I think using something like 
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
might help to save session on the client

**Comment by igorbarinov** [comment]
Don't we have localStorage with MobX?

**Comment by fernandomg** [comment]
@rstormsf yes, it's really useful. I'll add it in a different stage, as it has to be thoroughly tested. To avoid persisting undesired information across sessions (maybe https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage is the best option for this phase).

 @igorbarinov I don't think that persistence is part of the Mobx core.

**Comment by fernandomg** [comment]
This feature is already done, the part related to localStorage will be worked as part of #529
