### ISSUE TITLE
(Fix) Add reserved tokens object, if user forgot to click +

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#486]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Sokol POA, but the behavior is the same on every network

### If you were able to create it, what is the URL of your crowdsale?
https://wizard.poa.network/invest?addr=0xFfCCdB7b03077630851FB97d59e60cdDe8ee27Ff&networkID=77

### Do you have screenshots showing the problem?

No. Reserved token object is not added to reserved tokens list, if user forgot to click "+" button.

### Do you see errors in the dev console? If yes, please include a screenshot

(To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab)

No

---

**Comment by fvictorio** [comment]
I don't think this is the best solution from a UI/UX perspective, and besides that I think it would add unnecessary complexity to the code. Two alternatives come to mind:

1. Make the component behave in a more standard way. I think the most common approach here is to start with just an empty list and a "+" button. Pressing it adds an empty row of inputs. You can add as many rows as you want, and you can also remove them individually. This also allows editing them in whatever order you want. So you would start with something like this:

    ![image](https://user-images.githubusercontent.com/417134/35063981-5f647ee0-fba7-11e7-99b7-9d70c42e9f9b.png)

    And after clicking the button to add an address, you'd get this:

    ![image](https://user-images.githubusercontent.com/417134/35063890-29de3e1e-fba7-11e7-8343-c33a46ebadf8.png)

2. Validate that the address and value inputs are empty when you click "Continue". If they are not, show a warning indicating that the address wasn't added.

I thinks that the first approach is better, but it would also take more time. The second approach is a compromise solution that would get the job done.

What do you think?

**Comment by vbaranov** [comment]
@fvictorio I look into reserved block form as an input form. In this case, maybe, let's simply rename "+" button to "submit" or "save"? In this case, it is obvious, that data is not submitted until the user will press the button. What do you think about this solution from UI/UX perspective?
