### ISSUE TITLE
(UX/UI) Not clear on cap amount

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/token-wizard#525]
https://cl.ly/0R1R1y0c0a3X
![image](https://user-images.githubusercontent.com/9360827/35478653-df9b85fc-0397-11e8-8729-7dea6ee2e830.png)

As a user, I'd like to know if Cap is in ETH or Tokens

**Comment by fvictorio** [comment]
Not sure how to improve this. The explanation below is pretty clear IMO. Maybe replacing `Investor min cap` with `Investor min cap (tokens)`. Any suggestions?

cc @igorbarinov @vbaranov

**Comment by vbaranov** [comment]
Yes, change to `Investor min cap (tokens)` would be a good idea for clarity

**Comment by rstormsf** [comment]
exactly, as a user, I need to know the unit measurement. The below box isn't clear at all. Need to rework wordings part
@fvictorio

**Comment by igorbarinov** [comment]
Let's also replace `Investor` to `Contributor`

**Comment by fvictorio** [comment]
@rstormsf @igorbarinov What do you think of a description like this:

> Minimum amount of tokens to buy. Not the minimal amount for every transaction: if minCap is 1 and a user already has 1 token from a previous transaction, they can buy any amount they want.
