### ISSUE TITLE
(Feature) Remove footer and header in embedded mode

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/token-wizard#530]
Problem:
When wizard invest page embedded in iframe there is header/footer of ICO Wizard inside the iframe. Users of ICO Wizard decide not embed the page because it's not convenient/not design friendly.
Example of an embedded invest page https://www.thebtcbtq.com/btq
https://cl.ly/143d3c0U2U1O

Solution:
When invest page is in an iframe, don't show footer and header. Should be configurable in a yml config file. By default header/footer should be disabled in the embedded mode.

**Comment by fvictorio** [comment]
I'm not sure I understand the part about the yml config file. Do you mean having an option like "removeFooterOnIframe", so that the person deploying the wizard has the option to show the header and footer when embedding it?

**Comment by igorbarinov** [comment]
@fvictorio yes, you are right. I meant to have it configurable

**Comment by fernandomg** [comment]
@igorbarinov I was testing this in the BTQ page.
With the current iframe's `600px` height and removing header/footer and paddings/margins, the page won't be fully visible.
![image](https://user-images.githubusercontent.com/3315606/35746198-c908c980-0824-11e8-8fab-f186ec738f1d.png)

In this scenario, the minimum height for the QR Code to be visible, is `900px`, but with this height when QR is not being displayed there will be a big white space beneath the wizard.

---
Probably we should re-arrange the page elements when the height is ~600px or think in a responsive approach.

**Comment by fernandomg** [comment]
Just to make it clear, the solution will include adding a new attribute to `ICOConfig` (should we change the number of that variable too?)

The new attribute will be: `showHeaderAndFooterInIframe`, and it will be _falsy_ by default. That means, no header nor footer.

@igorbarinov @vbaranov is it ok?

**Comment by vbaranov** [comment]
>...ICOConfig (should we change the number of that variable too?)

What do you mean?

>The new attribute will be: showHeaderAndFooterInIframe, and it will be falsy by default. That means, no header nor footer.

Sounds good to me

**Comment by fernandomg** [comment]
> What do you mean?
Sorry, the "name" of the variable I meant

**Comment by vbaranov** [comment]
Oh, yes, maybe, rename to `CrowdsaleConfig`. Also, lets change example in wiki too after renaming: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-ICO-Configuration
