### ISSUE TITLE
ICO wizard error when creating token

### ISSUE THREAD

**Issue by Febrero** [poanetwork/token-wizard#534]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten test network

### If you were able to create it, what is the URL of your crowdsale?

Transaction error, not able to create

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/25055383/35514885-90f8750e-04ff-11e8-8620-788a46455cae.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab
[wizard.poa.network-1517235866219.zip](https://github.com/poanetwork/ico-wizard/files/1673872/wizard.poa.network-1517235866219.zip)
[wizard.poa.network-1517235845571.zip](https://github.com/poanetwork/ico-wizard/files/1673873/wizard.poa.network-1517235845571.zip)

files attached

I've also attached some results from the poa ico wizard:
[FINALIZE AGENT CONTRACT SOURCE CODE.txt](https://github.com/poanetwork/ico-wizard/files/1673874/FINALIZE.AGENT.CONTRACT.SOURCE.CODE.txt)
[poa-ico-wizard-source-code.txt](https://github.com/poanetwork/ico-wizard/files/1673875/poa-ico-wizard-source-code.txt)
[TOKEN CONTRACT ABI.txt](https://github.com/poanetwork/ico-wizard/files/1673876/TOKEN.CONTRACT.ABI.txt)
[token contract source code.txt](https://github.com/poanetwork/ico-wizard/files/1673877/token.contract.source.code.txt)

**Comment by Febrero** [comment]
also, contract download and attached

[icowizard_Ropsten_.zip](https://github.com/poanetwork/ico-wizard/files/1673887/icowizard_Ropsten_.zip)

**Comment by Vcoin6** [comment]
Thanks

**Comment by vbaranov** [comment]
@Febrero I can't reproduce. Could you repeat the test in Ropsten again? Is any transaction failed now? Also, I can't open zip file with logs you attached. If your transaction will fail, could you send a valid archive?

**Comment by Febrero** [comment]
please see below, transaction failed again,

[icowizard_Ropsten_0xfb5DBa9A7B70C23Aa671A2210255c05b1Aa6B21a.zip](https://github.com/poanetwork/ico-wizard/files/1686342/icowizard_Ropsten_0xfb5DBa9A7B70C23Aa671A2210255c05b1Aa6B21a.zip)

files inside:

**Comment by Febrero** [comment]
i tried downloading the file attached and it worked. can you tell me if now you see the logfiles?

**Comment by vbaranov** [comment]
I need logs from Google Chrome developer console:

>To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab
If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

**Comment by Febrero** [comment]
Poa is offline at the moment. will do so as soon as it s online

(button greyed out)

![image](https://user-images.githubusercontent.com/25055383/35691776-54a04d10-0771-11e8-8e07-62d3954d71fd.png)

**Comment by vbaranov** [comment]
It is online now. It would be great if you'll be able to attach log files from dev console.

**Comment by Febrero** [comment]
see below



[wizard.poa.network-1517507344528.log](https://github.com/poanetwork/ico-wizard/files/1686597/wizard.poa.network-1517507344528.log)
[wizard.poa.network-1517507337236.log](https://github.com/poanetwork/ico-wizard/files/1686598/wizard.poa.network-1517507337236.log)

**Comment by Febrero** [comment]
Hello

the issue hasn't been fixed. just tried 3 times every time it fails.
1. i have ether in both addresses im using for crowdfunding (owner address, escrow address)
2. it seems the erros are always the same 2.

logfiles below.

[wizard.poa.network-1517582162205.log](https://github.com/poanetwork/token-wizard/files/1689697/wizard.poa.network-1517582162205.log)
[wizard.poa.network-1517582171355.log](https://github.com/poanetwork/token-wizard/files/1689698/wizard.poa.network-1517582171355.log)

**Comment by vbaranov** [comment]
Please, clear cache in browser. You are still using the previous version of Wizard. Try to open in a new browser window, also. 
If you are using the new version of Wizard, you'll see this header in `.sol` file:
>// Created using Token Wizard https://github.com/poanetwork/token-wizard by POA Network

**Comment by Febrero** [comment]
awesome it did work on the sokol test network. Could i ask one more quick question?

1. I've successfully created the crowdfunding, but on the parameters (attached) i defined that 40% of tokens would go to the owner address and 60% for the contract address. 

so basically the idea is
a. max supply: 100000000
b. offered in crowdfunding: 60000000
c. reserved for owner: 40000000

my question is: is there a way to define only a X% amount of the total supply goes into crowdfunding? If not, i can create a contract with only 40000000 tokens, but then if i want to create more with the same name and symbol, is that feasible? Can the contract be updated, to mint more tokens?

results:
https://wizard.poa.network/crowdsale?addr=0x5adf785cA8BbaF6976b1633DB8E315529B2Df599&networkID=77

[icowizard_Sokol_0x36EE6Fd737342abaEe05AdB02F56bF4062c8B765.zip](https://github.com/poanetwork/token-wizard/files/1689967/icowizard_Sokol_0x36EE6Fd737342abaEe05AdB02F56bF4062c8B765.zip)
