### ISSUE TITLE
Transaction Failed during Mainnet deployment

### ISSUE THREAD

**Issue by astrocrypto** [poanetwork/token-wizard#535]
If you are reporting a problem with ICO Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

**Mainnet**

I received the bottom notification in my Metamask console

![screenshot](https://user-images.githubusercontent.com/35630998/35564554-dd1b0580-05ba-11e8-9b9d-aec245522271.png)

**What I Did*

The ICO Wizard is forked and reverted the pull request. This allowed me to deploy to the mainnet. The first 2 confirmations went through but at the third it crashed and stopped. I got the error message within the wizard "Transaction Failed"

---

**Comment by vbaranov** [comment]
@astrocrypto any logs from dev console in Google Chrome?

**Comment by astrocrypto** [comment]
I do not have the browser open anymore I am sorry...

**Comment by vbaranov** [comment]
Did the last actually transaction mined or not? Please give us the link to Etherscan to investigate.

**Comment by astrocrypto** [comment]
This is the link to the last transaction 
https://etherscan.io/tx/0x33fe699f268f85d91802bbf10ff1f5b4d7cc5e9be6a3979e0cb6284846b866b8

This is what I see in my Metamask:

![schermafbeelding 2018-01-30 om 12 53 21](https://user-images.githubusercontent.com/35630998/35565146-9ec4889a-05bc-11e8-8d34-8cc24d2db45d.png)

**Comment by fvictorio** [comment]
@astrocrypto Were you able to create a crowdsale on a testnet before doing it in the mainnet?

**Comment by astrocrypto** [comment]
I have tried it before with a different contract not exactly the same. I used the reserved token option this time.

**Comment by fvictorio** [comment]
Could you try to deploy in a testnet a crowdsale with the same configuration, and check if you get the same error?

The "500" error is weird. What are the chances that the node used by metamask (I thinks it's Infura?) had a problem just when this was being deployed?

**Comment by vbaranov** [comment]
The error is not reproducible and related to 3d-party service. Moreover persisting of crowdsale state is enabled now https://github.com/poanetwork/token-wizard/pull/598. Could be closed.
