### ISSUE TITLE
(Refactor) Consider removing all checks for contract type

### ISSUE THREAD

**Issue by fvictorio** [poanetwork/token-wizard#536]
The codebase has several places where it checks the "contract type" selected in step one (I guess crowdsale type would be a better name). But right now only one crowdsale type is supported. Plus, if another type is added in the future, I seriously doubt that having conditionals sprinkled everywhere is going to be the best approach.

So I think all these conditionals only make the code harder to maintain without giving any future benefit. I propose removing them, since 1) it's a fairly low risk change and 2) it's going to significantly increase the readability of the code.

@vbaranov @igorbarinov Thoughts on this?

**Comment by vbaranov** [comment]
Yes, let's remove these obsolete conditions
