### ISSUE TITLE
PUBLISH page hangs indefinitely after contracts creation, can't DOWNLOAD FILE

### ISSUE THREAD

**Issue by AdrianBond** [poanetwork/token-wizard#549]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

RINKEBY

### If you were able to create it, what is the URL of your crowdsale?

0x893Ed16fa2B5C61039cA4360e7CD71Fd58c235D2

### Do you have screenshots showing the problem?

Yes

### Do you see errors in the dev console? If yes, please include a screenshot

Yes

Using Brave browser on Mac OSX 10.12.6, no option to save, apparently. The errors read: "Failed to load resource: the server responded with a status of 404 () . logos@2x.210aafad.png, main.1a313fef.css"
![screen shot 2018-02-01 at 23 06 37](https://user-images.githubusercontent.com/35900181/35706182-1600e7fc-07a5-11e8-867e-b47c50bd76fd.png)
![screen shot 2018-02-01 at 23 01 20](https://user-images.githubusercontent.com/35900181/35706183-1639868e-07a5-11e8-8f97-6662be383de0.png)

---

**Comment by vbaranov** [comment]
Wizard aren’t supported in Brave yet. Do you have the same issue in Google Chrome?

**Comment by AdrianBond** [comment]
No, I haven't. Thank you for that invaluable information! Will try next in Google Chrome.
