### ISSUE TITLE
(Bug) Multiple-tiers crowdsale: Finalize button is enabled, when the 1st tier is finished

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#550]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Sokol

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.poa.network/manage/0xA07d7006e73203aCd6f855ABffa2f42E4D6F4F3A

### Do you have screenshots showing the problem?

Screenshot time: 02-02-2018 14:20

![screencapture-wizard-poa-network-manage-0xa07d7006e73203acd6f855abffa2f42e4d6f4f3a-1517570665558](https://user-images.githubusercontent.com/4341812/35730894-d677c1de-0824-11e8-851f-93342d10575d.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

**Comment by fernandomg** [comment]
solved as part of #565
