### ISSUE TITLE
Add wiki page how to distribute reserved tokens

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#553]
Relates to https://github.com/poanetwork/token-wizard/pull/537

**Comment by vbaranov** [comment]
https://github.com/poanetwork/token-wizard/wiki/Distribute-reserved-tokens

**Comment by igorbarinov** [comment]
@vbaranov 
- why button is “Distribute tokens” and not “Distirbute reserved tokens”
- where is this feature came from?

**Comment by vbaranov** [comment]
@igorbarinov 
> - why button is “Distribute tokens” and not “Distirbute reserved tokens”

I tried to shorten button name to fit the width of `Finalize Crowdsale` button. Nevetherless, there is an unambiguous description above the button `Reserved tokens distribution is the last step of the crowdsale before finalization. You can make it only after the end of the last tier. If you reserved more then 100 addresses for your crowdsale, the distribution will be executed in batches with 100 reserved addresses per batch. Amount of batches is equal to amount of transactions`. If you think, a short button name may confuse users, I'll change the name to `Distirbute reserved tokens`.

> - where is this feature came from?

This feature is introduced here https://github.com/poanetwork/ico/pull/14 as a result of security audit. It solves this problem:
> 4. Distributing of huge amount of reserved tokens can cause out gas problem for finalization of crowdsale.

**Comment by igorbarinov** [comment]
@hashguide what do you think about the name of the button?
for me and for you it was confusing that we have two buttons. 

Btw, @vbaranov distributed reserved tokens are not movable before finalize, right?

**Comment by vbaranov** [comment]
>Btw, @vbaranov distributed reserved tokens are not movable before finalize, right?

Right, all tokens are immovable before finalization including reserved

**Comment by igorbarinov** [comment]
- Do we have updated instruction for finalizing reserved tokens in our main Finalize page 
- Whats happening if a user Finalize crowdsale without finalizing reserved tokens

**Comment by vbaranov** [comment]
> - Do we have updated instruction for finalizing reserved tokens in our main Finalize page

Yes. Wiki post describing finalization was [updated](https://github.com/poanetwork/token-wizard/wiki/Finalize-crowdsale/_compare/df7b9db95857ff157b27c201a1c499615e05599f...cb17cd89caf93e732909c37117da20fdd3e73ad2) immediately after feature has appeared

> - Whats happening if a user Finalize crowdsale without finalizing reserved tokens

Finalizing before reserved tokens distributing is disabled in Dapp. If the user will try to do it on smart contracts level, the transaction will fail.

**Comment by igorbarinov** [comment]
@vbaranov thank you
@hashguide please read and think about the name

**Comment by TRIHRD** [comment]
Hi can you please integrate into ICO thanks mal  at MALPAINTA@gmail.com

**Comment by fvictorio** [comment]
Hi @TRIHRD. The issue tracker is for bugs and feature requests only. This is the third time you've left unrelated comments in a thread. If you have questions, please go to the [gitter channel](https://gitter.im/poanetwork/ico-wizard)

**Comment by fernandomg** [comment]
shall we change the button name to `distribute reserved tokens`? or leave it as it is? if so, we should close this issue.
