### ISSUE TITLE
Finalizing Crowdsale Error: No Crowdsale Found for Address

### ISSUE THREAD

**Issue by btcbtq** [poanetwork/token-wizard#558]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Mainnet
### If you were able to create it, what is the URL of your crowdsale?
https://wizard.oracles.org/invest?addr=0x3bd75061dc050fb1158be6BC423698f4bD702Df6&networkID=1
*Your answer*

### Do you have screenshots showing the problem?
![crowdsalelist](https://user-images.githubusercontent.com/34976171/35757210-f90dcc04-0822-11e8-9d06-60d40976a843.jpg)

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot
No
To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
Contracts registry was introduced not so long ago. Your crowdsale maybe is not listed there. So, you need to finalize your crowdsale with other options described in wiki. For example, with Myetherwallet usage.

**Comment by btcbtq** [comment]
Which option distributes reserved tokens on MyEtherWallet? Thank you for your help!

**Comment by vbaranov** [comment]
Your contracts are of previous version. So, reserved tokens distribution is in finalize method. Thus, you can simply call finalize, and after that tokens will be distributed and crowdsale will be finalized.
