### ISSUE TITLE
(Fix) Inaccurate finish of process if user reject transaction

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#569]
### Problem
User can't return to the start of wizard because no any clickable elements on the page. Should be UI that allow an user to start the wizard again.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Rinkeby

### If you were able to create it, what is the URL of your crowdsale?

n/a

### Do you have screenshots showing the problem?
![screenshot from 2018-02-06 19-58-51](https://user-images.githubusercontent.com/14067096/35897867-37e8e992-0b78-11e8-9428-09f34f218793.png)

After reload 
![screenshot from 2018-02-06 19-59-44](https://user-images.githubusercontent.com/14067096/35897890-5c81b3ec-0b78-11e8-8229-a372bb0d2d1e.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

[wizard.poa.network-1517976209842.log](https://github.com/poanetwork/token-wizard/files/1701694/wizard.poa.network-1517976209842.log)

---

**Comment by fernandomg** [comment]
@dennis00010011b I'll add a `Cancel` button in the progress popup, and if clicked display the display the alert for the deployment cancel.

Just to clarify: currently, refreshing the page will allow the user to continue the deployment (according to #598 changes)

**Comment by fvictorio** [comment]
@dennis00010011b Is this still valid?

**Comment by dennis00010011b** [comment]
@fvictorio 
No,  I can't reproduce this issue. It is fixed.
