### ISSUE TITLE
(Fix) Add validation to Reserved tokens->Value

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#570]
###  Problem
*Wizard accepts wrong  percentage value of reserved tokens: 0, negative, more than 100*
*Wizard accepts wrong  tokens value of reserved tokens: 0, negative*

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

![percents](https://user-images.githubusercontent.com/14067096/35898405-5e163eaa-0b7b-11e8-9c52-63f0ee4a2b15.png)

![tokens](https://user-images.githubusercontent.com/14067096/35898544-172acb9a-0b7c-11e8-8f29-62a6d9c81d2f.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

**Comment by fernandomg** [comment]
I don't see in the contracts if there's a restriction in the maximum percentage of tokens to be allocated. It looks that the percentage can be greater than 100% and it will work just fine.

@vbaranov please correct me if I'm wrong

**Comment by vbaranov** [comment]
Right, there is no maximum restriction

**Comment by dennis00010011b** [comment]
@fernandomg @vbaranov 
The reserved percentage will take from the total SOLD in all tiers. That's why percentage can not be more than 100%. The same with reserved amount in tokens. It can't be more than total supply.
please correct me if I'm wrong
See discussion about: https://gitter.im/poanetwork/ico-wizard
```

```

> abipod @abipod Feb 08 17:44
> Thank you so much! One more question, the total tokens on the invest page,
>  for example it says Total Tokens 100,000,000 is this the total tokens including the reserved tokens?
>  Or is the 100m only the tokens that will be sold, and after the sale another extra 
> (lets say 25%) reserved tokens will be created and the total supply will go up to 125m, 
> or the 100m in the invest page includes them all? 
> Because when I created my token I reserved 25% tokens, and then on 4 tiers 
> I put a total of 100m tokens for sale, and I am trying to figure out 
> if the 100m tokens include my 25%, then how am I going to be able to sell 100m tokens on the 4 tiers? 
> I dont know if you will be able to understand my question, I hope you do because
>  I am really confused at this part
> And sorry for the countless questions
> 
> Stephen Arsenault @hashguide Feb 08 20:07
> that number represents how many tokens are available during the current tier.
>  whatever is not sold in the tier is simply not minted. 
> The reserved percentage will take from the total SOLD in all tiers.

```


```

**Comment by fernandomg** [comment]
Despite there's no restriction to the maximum percentage, the minimum values should be validated.
