### ISSUE TITLE
(Fix) special symbols and numbers are allowed for ticker

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#572]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*Yes*

### Do you have screenshots showing the problem?

![specsymbolsfinal](https://user-images.githubusercontent.com/14067096/35899384-faeca75a-0b80-11e8-81c6-1c7f01d49db9.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

No

---

**Comment by fvictorio** [comment]
@vbaranov What characters should be allowed here? Only alphanumeric?

**Comment by vbaranov** [comment]
Yes
