### ISSUE TITLE
(Bug) Multiple-tiers crowdsale, countdown timer show time to the end of  latest tier

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#584]
### Step to reproduce:
1. Create 2  tiers.
 tier1 : start 02/08/2018 11:15pm   ,   end 02/08/2018 11:45pm
 tier2 : start 02/09/2018 11:15pm   ,   end 02/09/2018 11:45pm
2. Deploy tokens 
3. Observe countdown value in the final page
Expected result: countdown should indicate time left to the start of the first tier 
Actual result: countdown indicates time left to the end  of the second tier 

Crowdsale was created 02/08/2018 around 10:00am

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/manage/0xd0d45D5BcB4f546d06f88D93E97F24dbdA225662

### Do you have screenshots showing the problem?
Tier1
![screenshoot1518112140707](https://user-images.githubusercontent.com/14067096/36008692-73502294-0cfd-11e8-9fb4-28c6581e204e.png)

Tier2
![screenshoot1518112143549](https://user-images.githubusercontent.com/14067096/36008700-7c23e6b2-0cfd-11e8-9fb9-f6acee89a686.png)

![cuntdownfinal](https://user-images.githubusercontent.com/14067096/36008710-823205de-0cfd-11e8-8f5e-26d18041aa4d.png)
![countfinal](https://user-images.githubusercontent.com/14067096/36008716-85a2cb36-0cfd-11e8-9974-9723b83708a1.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by dennis00010011b** [comment]
Look like  this report is duplicate of https://github.com/poanetwork/token-wizard/issues/520

**Comment by fernandomg** [comment]
@dennis00010011b @vbaranov 

Just FYI, it'll count down to the next start or end of tier, and I added a legend under the time indicator to let the user know how much time last to the end of the current tier or how much time last to the start of the next one.

If end of current tier overlaps with the beginning of the next one, legend will indicate that it's counting down to the end of the current tier.

Also fixed the buggy behavior of the pie when left time was small.

And last, when countdown is under 5 minutes, it will display minues, and seconds only.

![image](https://user-images.githubusercontent.com/3315606/37305640-e017c5ce-2613-11e8-893f-c6c5b66621c2.png)

![image](https://user-images.githubusercontent.com/3315606/37305508-7023db5e-2613-11e8-8b58-9178eb77c04b.png)

![image](https://user-images.githubusercontent.com/3315606/37305529-7c68a2e6-2613-11e8-92a6-9f184828c33d.png)

I'll add tests and do the PR if everything looks ok for you.

**Comment by fvictorio** [comment]
LGTM :+1:

**Comment by dennis00010011b** [comment]
Looks good! May be would be better to show the number of tier instead words "current" , "next" and show total amount of tiers?
