### ISSUE TITLE
(Refactor) Manage screen and related components

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#585]
Currently manage screen is composed of elements that copy the behavior of similar elements used throughout the wizard.

Starting from this screen, it would be good to create reusable components and apply them throughout the wizard.

This will facilitate the testing and improve the robustness of the app.

**Comment by vbaranov** [comment]
@fernandomg could we close it, as we introduced final form for management page or refactor is still in progress?

**Comment by fernandomg** [comment]
Let's close it, as it was solved as part of the `final-form` migration. Thanks for the catch!
