### ISSUE TITLE
Reserved tokens & total supply issue

### ISSUE THREAD

**Issue by Febrero** [poanetwork/token-wizard#587]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

sokol.poa.network

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0xc2b9c59B303edeBCa9181837772748714D96Ed15&networkID=77

### Do you have screenshots showing the problem?

see below problem description please

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

ANSWER:
Crowdsale created fine, the problem is with the reserved amount and total supply. Problem explained below:

I've successfully created the crowdfunding, but on the parameters (attached) i defined that 40% of tokens would be reserved for the crowdsale. 

so basically the idea is
a. max supply: 100000000
b. offered in crowdfunding: 40000000 (or 40% of total supply)

my question is: is there a way to define only an X% amount of the total supply goes into crowdsale? If not, i can create a contract with only 40000000 tokens, but then if i want to create more tokens with the same name and symbol, is that feasible? Can the contract be updated to mint more tokens?

Another way to put the question:
![image](https://user-images.githubusercontent.com/25055383/36043176-4db7fa56-0dc6-11e8-81fd-7a56e053dca3.png)

Is the total supply of tokens in the screenshot referring to:
- Actual token total supply?
- Crowdsale total supply?

Meaning, if you reserve for example 60% of the tokens, then the actual total supply on the case above is 100000000 (100 million) tokens? Sorry if it's confusing!

**Comment by vbaranov** [comment]
Reserved tokens are not accounted on the crowdsale page. You will distribute them after the end of crowdsale.

>Is the total supply of tokens in the screenshot referring to Crowdsale total supply?

Yes

>so basically the idea is
a. max supply: 100000000
b. offered in crowdfunding: 40000000 (or 40% of total supply)

In this case, the total amount of tokens:
- will be equal 140000000, if hard cap will be sold
- will be less then 140000000, if hard cap will not be sold

>is there a way to define only an X% amount of the total supply goes into crowdsale?

Yes, let's do some math:
For example, you need 60% of tokens to be sold at maximum from total tokens amount 100000000.
```
TOKENS_TO_BE_SOLD = 0.6 * 100000000 - 60% of tokens to be sold
TOKENS_TO_BE_RESERVED = X * TOKENS_TO_BE_SOLD - X % tokens to be reserved
TOKENS_TO_BE_SOLD + TOKENS_TO_BE_RESERVED = 100000000 =>

0.6 * 100000000 + X * 0.6 * 100000000 = 100000000 => 0.6 * X = 0.4 => X ~ 0.67 =>

TOKENS_TO_BE_SOLD = 60000000 tokens (SUPPLY of step 2 of Wizard)
TOKENS_TO_BE_RESERVED ~ 67% (this is the % you need to indicate in percents in step 2), or simply set 40000000 tokens to reserve (it is the same than 67%)
```
