### ISSUE TITLE
(Bug) Whitelisted account can't buy maximum amount of tokens if it is not first transaction 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#589]
### Step to reproduce:
1. Create crowd-sale with whitelisted account, define min and max allowed amount.
I tested with parameters:
"whitelisting":true,
"mincap": 1,
"rate":100,
"supply": 200,
"whitelist":[
        {
          "address":"0x40cAa4BF6893dF91638305cFCf98CB8E7Fa8D17F",
          "min":2,
          "max":10
        },
2. Open crowdsale page as Investor, set whitelisted account in MetaMask and buy some amount between min and max.
3.Do next transaction, try to buy until  max amount (10 tokens).
Expected result : should be allowed to buy until max amount (10 tokens).
Actual result: I could buy total only 7.6 tokens (2.1 in first transaction and 5.5 in second)
When I tried to buy total less than 10 tokens (2.1+7) I got message:"transaction failed"
Expected result: Total allowed amount should be 10

Reproduced 3 times.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkebuy*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/invest?addr=0x22eedf995Da8CC23D9eD2a62E52603Efa0B068E7&networkID=4r*

### Do you have screenshots showing the problem?
![23](https://user-images.githubusercontent.com/14067096/36057909-587886be-0dca-11e8-9870-59bea8926f31.png)
![24](https://user-images.githubusercontent.com/14067096/36057914-6048ff0e-0dca-11e8-8aff-0be1fbf269ef.png)
file:/home/d/WebstormProjects/TetsingWizardPOA/results1518228315525/screenshoot1518228338405.png

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment]
Dennis also, please clarify how many decimals were in your token?

**Comment by dennis00010011b** [comment]
Decimals=3

**Comment by dennis00010011b** [comment]
Reproduced issue right now
I was able to buy : first transaction 10+second transaction 80=90
Wasn't allowed to buy more.
https://wizard.poa.network/invest?addr=0x7f830e8C17aC96AD4100d9d56E54DEa4425Cbc00&networkID=4
Input file
```
{ "account": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "privateKey": "03c06a9fab22fe0add145e337c5a8251e140f74468d72eab17ec7419ab812cd0",
  "networkID":4,

  "name": "T1RnWy02/10/18 00:00am",
  "ticker": "MSCqj",
  "decimals": 3,
  "reservedTokens":[
    {

    },
    {

    }],
  "walletAddress":"0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "gasprice": 40,
  "mincap": 1,
  "whitelisting":true,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "02/10/2018",
      "startTime": "00:15am",
      "endDate":"02/10/2018",
      "endTime":"00:29am",
      "rate":100,
      "supply": 200,
      "whitelist":[
        {
          "address":"0x40cAa4BF6893dF91638305cFCf98CB8E7Fa8D17F",
          "min":10,
          "max":100
        },
        {
          "address":"0x42f0143F2E9Ab64CA3811bbA08E40D798C18E7f4",
          "min":8,
          "max":55
        }]
    }]


}
```
![screenshoot1518250195448](https://user-images.githubusercontent.com/14067096/36060182-3bfc5888-0df9-11e8-8ea3-f33e414d68da.png)
![33](https://user-images.githubusercontent.com/14067096/36060215-d10246a4-0df9-11e8-9231-74d9fadb3843.png)

![screenshoot1518250188287](https://user-images.githubusercontent.com/14067096/36060224-1cc0205c-0dfa-11e8-9ea2-cc79d319532f.png)

**Comment by dennis00010011b** [comment]
Manage page.
Min=0, max=10
Should be: min-10, max=100

https://wizard.poa.network/manage/0x7f830e8C17aC96AD4100d9d56E54DEa4425Cbc00

![43](https://user-images.githubusercontent.com/14067096/36060294-806af3ce-0dfb-11e8-861c-32accb44f49d.png)
