### ISSUE TITLE
(Bug) stuck tx status

### ISSUE THREAD

**Issue by lindsmcw** [poanetwork/token-wizard#603]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Main network

### If you were able to create it, what is the URL of your crowdsale?

Not finished

### Do you have screenshots showing the problem?

Yes
![image](https://user-images.githubusercontent.com/9313857/36342916-fd59eee8-1450-11e8-8109-aece1d0dff4f.png)

### Do you see errors in the dev console? If yes, please include a screenshot
![image](https://user-images.githubusercontent.com/9313857/36342978-a0a6254e-1451-11e8-8a6c-72dfc8b2a4a6.png)
![image](https://user-images.githubusercontent.com/9313857/36342988-cc88b262-1451-11e8-9b42-c51c6d21a0fd.png)
![image](https://user-images.githubusercontent.com/9313857/36343024-37a73f96-1452-11e8-8df9-29fc6e71c018.png)
 at f.performUpdateIfNecessary (main.7c06d6f5.js:1)

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---
The issue is there were 17 transactions required through the metamask network and it stopped after the 11th one. Metamask doesn't show the submit button for the next one.. how can I continue with this?

**Comment by vbaranov** [comment]
The first error from the screenshot is ignored and it shouldn't block deployment process. You can see, that deployment continued after this error. Anyways, could you clarify some details for investigation:

1. Could you attach Zip archive of logs - it is hard to restore chronology from screenshot
2. Why do you say 17 transactions? If you have only 1 tier, you need to sign only 14 txs. I see, that you are trying to create crowdsale with 1 tier.
3. Did you do any manipulations with MetaMask to repeat some of the transactions?

**Comment by lindsmcw** [comment]
1) Hi, I don't have that page open anymore, as it was stuck. Not able to do
anything, so I just saved this info then the window was closed:


main.7c06d6f5.js:1 stepThree ƒ i(){var t,e,n,r;E(this,i);for(var
o=arguments.length,a=Array(o),s=0;s<o;s++)a[s]=arguments[s];return
e=n=T(this,(t=i.__proto__||Object.getPrototypeOf(i)).call.apply(t,[this].concat(a))),n.storeRef=fu…
stepTwo ƒ i(){var t,e,n,r;E(this,i);for(var
o=arguments.length,a=Array(o),s=0;s<o;s++)a[s]=arguments[s];return
e=n=T(this,(t=i.__proto__||Object.getPrototypeOf(i)).call.apply(t,[this].concat(a))),n.storeRef=fu…
main.7c06d6f5.js:1 key name VALIDATED
main.7c06d6f5.js:1 key walletAddress VALIDATED
main.7c06d6f5.js:1 key rate VALIDATED
main.7c06d6f5.js:1 key supply VALIDATED
main.7c06d6f5.js:1 key startTime INVALID
main.7c06d6f5.js:1 isValid false
main.7c06d6f5.js:1 key name VALIDATED
main.7c06d6f5.js:1 key walletAddress VALIDATED
main.7c06d6f5.js:1 key rate VALIDATED
main.7c06d6f5.js:1 key supply VALIDATED
main.7c06d6f5.js:1 key startTime VALIDATED
main.7c06d6f5.js:1 key endTime VALIDATED
main.7c06d6f5.js:1 key updatable VALIDATED
main.7c06d6f5.js:1 key tier VALIDATED
main.7c06d6f5.js:1 isValid true
3main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 e
main.7c06d6f5.js:1 Array(1)
main.7c06d6f5.js:1 Array(1)
3main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 e
main.7c06d6f5.js:1 Array(6)
main.7c06d6f5.js:1 Array(6)
Array(6)
main.7c06d6f5.js:1 pricingStrategy ABI Encoded params constructor:
00000000000000000000000000000000000000000000000000005af3107a4000
2main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 token ABI Encoded params constructor:
00000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005526967656c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000352474c0000000000000000000000000000000000000000000000000000000000
2main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 ***Deploy safeMathLib contract***
main.7c06d6f5.js:1 abi e
main.7c06d6f5.js:1 gas is estimated 164675
21main.7c06d6f5.js:1 Contract deployment transaction
0xe77a7045a43f110dba8713c37c2919cc43439f71c51c5d4634f98c25cfdafc7e is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract deployment transaction
0xe77a7045a43f110dba8713c37c2919cc43439f71c51c5d4634f98c25cfdafc7e is mined
from Promise
8main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 abi e
main.7c06d6f5.js:1 gas is estimated 2407207
main.7c06d6f5.js:1 Object
8main.7c06d6f5.js:1 Contract deployment transaction
0x15810d7ca8154635ea0bde985c5a5c3fc711574bddd4c9eb5ff4f4ff62acdc07 is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract deployment transaction
0x15810d7ca8154635ea0bde985c5a5c3fc711574bddd4c9eb5ff4f4ff62acdc07 is mined
from Promise
2main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 abi e
main.7c06d6f5.js:1 gas is estimated 400115
main.7c06d6f5.js:1 Object
6main.7c06d6f5.js:1 Contract deployment transaction
0x9329743a2dfdae7d47e7e30d7bb897dd6502e5111bfba87eabeb451066184d6e is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 Contract deployment transaction
0x9329743a2dfdae7d47e7e30d7bb897dd6502e5111bfba87eabeb451066184d6e is mined
from polling of tx receipt
2main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 e
main.7c06d6f5.js:1 Array(10)
main.7c06d6f5.js:1 Array(10)
2main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 abi e
main.7c06d6f5.js:1 gas is estimated 3515435
371main.7c06d6f5.js:1 Contract deployment transaction
0xcf8b2bd0ae23b0cdf2af5961d29f06e3993386d0bab36c128fd825bfaf1917ed is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Error: Failed to check for transaction receipt:
{}
    at Object.u [as _fireError] (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:210503)
    at https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:248102
    at a (https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1529954)
    at i._settlePromiseFromHandler (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1503397)
    at i._settlePromise (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1504241)
    at i._settlePromise0 (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1504943)
    at i._settlePromises (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1506202)
From previous event:
    at i.p [as _captureStackTrace] (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1469681)
    at i._then (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1499031)
    at i.then (
https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:1497399)
    at https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:804479
    at https://wizard.oracles.org/static/js/main.7c06d6f5.js:1:883810
    at <anonymous>
(anonymous) @ main.7c06d6f5.js:1
14main.7c06d6f5.js:1 Contract deployment transaction
0xcf8b2bd0ae23b0cdf2af5961d29f06e3993386d0bab36c128fd825bfaf1917ed is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 Contract deployment transaction
0xcf8b2bd0ae23b0cdf2af5961d29f06e3993386d0bab36c128fd825bfaf1917ed is mined
from polling of tx receipt
main.7c06d6f5.js:1 ***Deploy crowdsale contract*** 0
0x008E42C4e21119Bd4147De2853AEFb39689bfB1e
main.7c06d6f5.js:1 [mobx.array] Attempt to read an array index (0) that is
out of bounds (0). Please check length first. Out of bound indices will not
be tracked by MobX
e.get @ main.7c06d6f5.js:1
30main.7c06d6f5.js:1 Contract method transaction
0xb098ced9a049165f1286f84f462c02dec58d2d7e215f653421dbf6d13adabea2 is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract method transaction
0xb098ced9a049165f1286f84f462c02dec58d2d7e215f653421dbf6d13adabea2 is mined
from Promise
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 e
main.7c06d6f5.js:1 Array(2)
main.7c06d6f5.js:1 Array(2)
main.7c06d6f5.js:1 finalizeAgent ABI encoded params constructor:
000000000000000000000000a28a074f76674788b5ecdc78af48b44f3b95a4af000000000000000000000000008e42c4e21119bd4147de2853aefb39689bfb1e
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 abi e
main.7c06d6f5.js:1 gas is estimated 842049
16main.7c06d6f5.js:1 Contract deployment transaction
0x74d8312e3190a3702cb44a91f55aa5c60478a7fbaf654fa94b5fe47ca50d89ff is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract deployment transaction
0x74d8312e3190a3702cb44a91f55aa5c60478a7fbaf654fa94b5fe47ca50d89ff is mined
from Promise
main.7c06d6f5.js:1 ***Deploy finalize agent contract***
0x8f619D6C7cA3d1Eb5B13a7f86916C82dd8DE34CB
main.7c06d6f5.js:1 ###setTier for Pricing Strategy:###
main.7c06d6f5.js:1 attach to pricingStrategy contract
main.7c06d6f5.js:1 Object
80main.7c06d6f5.js:1 Contract method transaction
0xcd004d39ece4f5b3d846c3854e1bf309624ba81d9a34848a798f7775ced9f1fb is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract method transaction
0xcd004d39ece4f5b3d846c3854e1bf309624ba81d9a34848a798f7775ced9f1fb is mined
from Promise
main.7c06d6f5.js:1 ###setReservedTokensListMultiple:###
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 attach to token contract
92main.7c06d6f5.js:1 Contract method transaction
0xfadf02e796f050f2ffe66443505617616bc547286b7534dd0aa75470e643df73 is still
pending. Polling of transaction once more
main.7c06d6f5.js:1 Contract method transaction
0xfadf02e796f050f2ffe66443505617616bc547286b7534dd0aa75470e643df73 is mined
from Promise
main.7c06d6f5.js:1 ###updateJoinedCrowdsales:###
main.7c06d6f5.js:1 attach to crowdsale contract
main.7c06d6f5.js:1 input: e
main.7c06d6f5.js:1 Object
main.7c06d6f5.js:1 Array(2)
n.handleError @ main.7c06d6f5.js:1
main.7c06d6f5.js:1 Contract method transaction undefined is mined from
Promise
main.7c06d6f5.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at new e (main.7c06d6f5.js:1)
    at f._constructComponentWithoutOwner (main.7c06d6f5.js:1)
    at f._constructComponent (main.7c06d6f5.js:1)
    at f.mountComponent (main.7c06d6f5.js:1)
    at Object.mountComponent (main.7c06d6f5.js:1)
    at f.performInitialMount (main.7c06d6f5.js:1)
    at f.mountComponent (main.7c06d6f5.js:1)
    at Object.mountComponent (main.7c06d6f5.js:1)
    at f._updateRenderedComponent (main.7c06d6f5.js:1)
    at f._performComponentUpdate (main.7c06d6f5.js:1)
    at f.updateComponent (main.7c06d6f5.js:1)
    at f.receiveComponent (main.7c06d6f5.js:1)
    at Object.receiveComponent (main.7c06d6f5.js:1)
    at Object.updateChildren (main.7c06d6f5.js:1)
    at m._reconcilerUpdateChildren (main.7c06d6f5.js:1)
    at m._updateChildren (main.7c06d6f5.js:1)
    at m.updateChildren (main.7c06d6f5.js:1)
    at m._updateDOMChildren (main.7c06d6f5.js:1)
    at m.updateComponent (main.7c06d6f5.js:1)
    at m.receiveComponent (main.7c06d6f5.js:1)
    at Object.receiveComponent (main.7c06d6f5.js:1)
    at f._updateRenderedComponent (main.7c06d6f5.js:1)
main.7c06d6f5.js:1 Uncaught TypeError: Cannot read property 'getHostNode'
of null
    at Object.getHostNode (main.7c06d6f5.js:1)
    at f.getHostNode (main.7c06d6f5.js:1)
    at Object.getHostNode (main.7c06d6f5.js:1)
    at f.getHostNode (main.7c06d6f5.js:1)
    at Object.getHostNode (main.7c06d6f5.js:1)
    at f._updateRenderedComponent (main.7c06d6f5.js:1)
    at f._performComponentUpdate (main.7c06d6f5.js:1)
    at f.updateComponent (main.7c06d6f5.js:1)
    at f.receiveComponent (main.7c06d6f5.js:1)
    at Object.receiveComponent (main.7c06d6f5.js:1)
    at Object.updateChildren (main.7c06d6f5.js:1)
    at m._reconcilerUpdateChildren (main.7c06d6f5.js:1)
    at m._updateChildren (main.7c06d6f5.js:1)
    at m.updateChildren (main.7c06d6f5.js:1)
    at m._updateDOMChildren (main.7c06d6f5.js:1)
    at m.updateComponent (main.7c06d6f5.js:1)
    at m.receiveComponent (main.7c06d6f5.js:1)
    at Object.receiveComponent (main.7c06d6f5.js:1)
    at f._updateRenderedComponent (main.7c06d6f5.js:1)
    at f._performComponentUpdate (main.7c06d6f5.js:1)
    at f.updateComponent (main.7c06d6f5.js:1)
    at f.performUpdateIfNecessary (main.7c06d6f5.js:1)



   -  2) Why do you say 17 transactions? If you have only 1 tier, you need
   to sign only 14 txs. I see, that you are trying to create crowdsale with 1
   tier.


This was the first time using it.. I forgot to click the + to make further
tiers. I thought I could do that after this first "pre-ico" was made.


   - 3) Did you do any manipulations with MetaMask to repeat some of the
   transactions?

No, it was very slow.. all the transactions were taking around 10 minutes,
one took over 30 minutes (about the 3rd).
I stepped away from my desk for 2-3 minis, when I came back I noticed a
transaction had finished but there was no prompt for the next transaction..
so it got stuck.

Thanks,
-Lindsay
off to work now. Back in about 8.5 hrs.

**Comment by lindsmcw** [comment]
The log doesn't make any sense to me, and it's the only information I have left from the attempt to make the token. I guess some things were done as it got to step 7, but I don't know how to access any of it. It cost me about $7-$10 before it got stuck. How can I check if my token was registered and how would I issue tokens etc?

**Comment by vbaranov** [comment]
All contracts were created. But your crowdsale is not alive yet.
To finish deployment process you need to continue manually:
1. https://github.com/poanetwork/token-wizard/wiki/Set-mint-agent
2. https://github.com/poanetwork/token-wizard/wiki/Set-finalize-agent
3. https://github.com/poanetwork/token-wizard/wiki/Set-release-agent
4. https://github.com/poanetwork/token-wizard/wiki/Transfer-ownership

Set of your contracts to implement these steps: [restore-crowdsale.zip](https://github.com/poanetwork/token-wizard/files/1736782/restore-crowdsale.zip)
This is the link to your crowdsale: https://wizard.poa.network/crowdsale?addr=0x008E42C4e21119Bd4147De2853AEFb39689bfB1e&networkID=1

It will work after steps 1-4 will be finished.

This is the only way to finish stuck crowdsale now. In the future, we'll implement https://github.com/poanetwork/token-wizard/pull/598

**Comment by lindsmcw** [comment]
Thanks for that information.
I'll go through each of those 4 steps.
Am not sure what you mean here:  "Set of your contracts to implement these
steps: restore-crowdsale.zip
<https://github.com/poanetwork/token-wizard/files/1736782/restore-crowdsale.zip>
".
In that zipped folder I can see three files 'crowdsale', 'finalize_agent'
and 'token' they are not associated with any file type. Am I meant to open
those files, and which program do I open them with?

**Comment by vbaranov** [comment]
Please look through the links 1-4. All needed information to execute transactions 1-4 you'll find in the attached zip archive to make your crowdsale alive.

**Comment by lindsmcw** [comment]
Hi,
I did those 4 steps above. I think correctly. However when I clicked on the
crowdsale link: https://wizard.poa.network/crowdsale?addr=
0x008E42C4e21119Bd4147De2853AEFb39689bfB1e&networkID=1
and clicked -> Invest. then input 1 token (also tried 0.00001). Any amount
I tried it said "transaction has failed" please retry.
Can I buy them myself?
Also, the price says. 10,000 (tokes/eth) which seems high if that is in
ethereum.. how could I change that?

**Comment by vbaranov** [comment]
Yes, you can. Your tier is not whitelisted, as I see.

>I did those 4 steps above.
All transactions, you sent, are correct. But you missed the last one: https://github.com/poanetwork/token-wizard/wiki/Set-mint-agent. From this instruction, you need to send 2 txs. I see only one. The second one is to set crowdsale contract as a mint agent of token contract.

**Comment by lindsmcw** [comment]
As this was my first token. If you can answer some of these qns that would
be good.
1) Is it possible to do an ICO with wizard.oracles with this token or do
all the tiers need to be added in the intial start up?
2) After this pre-ico sale how can I generate more tokens?
3) In general how do I manage this token? and what options does the owner
of a token have? Eg setting the token price.
4) I have some ideas for this token such as charities it can support and
benefits for token holders, any recommendation for marketing?
5) What are the essentials for a token eg. white paper, website, support,
funds availble etc.
Any help would be appreciated.

**Comment by lindsmcw** [comment]
Can I still do that step. I tried going back and doing it, but in this
step:
In Select a function combo choose setMintAgent method
There is no option for setMintAgent - it's not in the dropdown.

**Comment by vbaranov** [comment]
Yes, you still can. You should do it on token contract with token contract ABI. The input parameter is crowdsale address.

**Comment by lindsmcw** [comment]
something is going wrong when I try to write this. The GAS amount is too
high. It has max charge around $245 USD.

**Comment by vbaranov** [comment]
Please show me myetherwallet page with filled input and also indicate the signer address.

**Comment by lindsmcw** [comment]
[image: Inline image 1]
[image: Inline image 2]

**Comment by vbaranov** [comment]
I don't see screenshots. Please upload to github.

**Comment by lindsmcw** [comment]
![image](https://user-images.githubusercontent.com/9313857/36384976-e3c84a14-15dc-11e8-9114-62b372a1a328.png)
![image](https://user-images.githubusercontent.com/9313857/36384984-e8adbbb8-15dc-11e8-8c74-6faadf2229a5.png)

**Comment by vbaranov** [comment]
>The second one is to set crowdsale contract as a mint agent of token contract.

1. you need to set token contract address to *Contract address field*
2. you need to set crowdsale contract address to *addr* field

**Comment by lindsmcw** [comment]
Ok, that makes sense. Read it incorrectly before. 1:30am here. $2.32 is
better than $295 I had before.

**Comment by lindsmcw** [comment]
I tried to contribute again on the crowdsale page. How many minutes should
it take? I clicked 1 token then contribute. It's just saying POA network
'do not refresh the page' for over 5 mins now.

**Comment by vbaranov** [comment]
If no errors in dev console you should wait. Slow option for contribution transaction gas price was chosen: it is slower, but cheaper for contributor.

**Comment by lindsmcw** [comment]
I closed that window and tried again. 
Works now. Just got 10 tokens, including the gas price for under $2.

**Comment by vbaranov** [comment]
Perfect.
Answers to your technical questions about Token Wizard platform:

>1) Is it possible to do an ICO with wizard.oracles with this token or do
all the tiers need to be added in the intial start up?

All the tiers need to be added in the initial start up. More about wizard strategy: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Strategy.

>2) After this pre-ico sale how can I generate more tokens?

You can reserve them with https://github.com/poanetwork/token-wizard/wiki/Set-reserved-tokens (supported feature) or you can mint them at any time (unsupported in-box feature for now).

>3) In general how do I manage this token? and what options does the owner
of a token have? Eg setting the token price.

https://github.com/poanetwork/token-wizard/wiki/Change-rate or even better https://www.youtube.com/watch?v=F35ZQd55TJY

**Comment by lindsmcw** [comment]
Thanks for your help. If you have a token you are selling let me know about it.

**Comment by vbaranov** [comment]
https://poa.network/tokens

**Comment by lindsmcw** [comment]
The public sale on that page says sold out. I tried to send some ether to
the address on that page, but the GAS price was too high .. about $58 usd.

**Comment by lindsmcw** [comment]
Hi,
When I do a search on https://etherscan.io/token-search

   for this token 0xa28a074f76674788b5ecdc78af48b44f3b95a4af


   it comes up with:


   Token Attributes Found:
    totalSupply = 10000000000000000000
    name = Rigel
    symbol = RGL
    decimals = 18

Is that normal to have such a large totalSupply? Can I modify this ?
I was about to run the function, setreservedlisttokensmuliple is that ok to
do that now or should the total supply be modified first?

**Comment by lindsmcw** [comment]
I think I get it now. if there are 10 tokens as balance the total supply
will be 10 to the power of decimals. so 10 to the power of 18. Which is
that number.

**Comment by vbaranov** [comment]
Token is mintable. Initial token supply is 0.
Current totalSupply = 10000000000000000000 means, that somebody bought 10 tokens. Other zeros - is the number of decimals.

**Comment by lindsmcw** [comment]
Ok thanks. Will do some research into difference between mintable and
non-mintable.

**Comment by lindsmcw** [comment]
I tried  https://github.com/poanetwork/token-wizard/wiki/Set-reserved-tokens
to reserve tokens.
I tried with both a metamask address and myetherwallet CX address. When I
click write an error shows:
(error_04) This is not a valid wallet file.

**Comment by vbaranov** [comment]
You should do it with the address, which is the `owner()` of token contract. And you can set reserved tokens only once.

**Comment by lindsmcw** [comment]
I tried it with the original address that I used (metamask) but it didn't
work. Is it because metamask is not classified as a wallet?

**Comment by lindsmcw** [comment]
I tried to set the reserved tokens again. This time the wallet address wasn't an issue but it had a very high GAS amount, which would have costed over $270 USD if I continued (rejected it).
Here is a screen shot of the top part of the screen. 
![image](https://user-images.githubusercontent.com/9313857/36469097-ca00df46-1731-11e8-8fd0-d695b1da05b4.png)

**Comment by lindsmcw** [comment]
I took the contract address and ABI from the 'token' file, is that correct?

**Comment by vbaranov** [comment]
This is correct. Please check the owner() property. Is it the same address which are trying to confirm transaction?

**Comment by lindsmcw** [comment]
How can I check owner() property? where am I looking? In the ABI there are no addresses. 
I checked etherscan and the token holder is the same address I tried.

**Comment by lindsmcw** [comment]
I used my wallet address (in the pic replaced with 'my address'). 
![image](https://user-images.githubusercontent.com/9313857/36470093-6bdacb44-1735-11e8-8807-5629c67847db.png)

**Comment by lindsmcw** [comment]
I've also tried two addresses separated with a comma. 
Where I put 0,0 in tokens 35,5  in 'inPercentageUnit and 0,0 in 'inPercentageDecimals'
Where I put one address or two addresses. The gas price was still over $270 USD.

**Comment by vbaranov** [comment]
The owner() property you can check in myetherwallet. Choose it in combobox. Is it the same address, which unlocked in Metamask?

**Comment by vbaranov** [comment]
Are you trying to confirm tx with this address 0x4141e041466c6ee97ad610651075ae5e7a03c810 ? It is the owner

**Comment by vbaranov** [comment]
Oh, you have already set reserved tokens. You can do it only once. It is indicated here: https://github.com/poanetwork/token-wizard/wiki/Set-reserved-tokens-in-percents
>Note: PLEASE BE CAREFUL, YOU CAN SET RESERVED TOKENS LIST ONLY ONCE.

**Comment by lindsmcw** [comment]
Yes, that is my Metamask address, that I used initially. In that screenshot above that is what I used as (my address).

**Comment by vbaranov** [comment]
Please read above. You have already set reserved tokens. You can do it only once:

![image 2018-02-21 11-54-11](https://user-images.githubusercontent.com/4341812/36471028-06c04572-16fe-11e8-9930-9cb972f377c7.png)

**Comment by lindsmcw** [comment]
Ok, I must have done that as part of the initial wizard? 
So it doesn't actually allocate any tokens to my account yet. It will just reserve a percentage is that right? So if there were 10,000 tokens in the pre-sale, and I reserved 50% then 5000 cannot be bought?  I can't recall what percentage I reserved.

**Comment by lindsmcw** [comment]
I am wanting to get some tokens so I can send to some ppl. Do I have to wait till the pre-sale is over before the tokens are allocated? or can I mint them? Am not sure how to min them yet.

**Comment by lindsmcw** [comment]
Also how can I look at the token code? Is it fully ERC20 compatible? Once the website is completed and other preparation ready, would this token be able to be submitted to an exchange such as cryptopia? Or would I need to add some functions? Is it too late to add functions to the token after it has been deployed?

**Comment by vbaranov** [comment]
@lindsmcw too many unrelated to the initial issue questions. Let's go to https://gitter.im/poanetwork/ico-wizard for discussion. But first, please take a look to these articles:
demo: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Demo
strategy: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Strategy
contracts verification: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts
distributing of reserved tokens: https://github.com/poanetwork/token-wizard/wiki/Distribute-reserved-tokens
finalization: https://github.com/poanetwork/token-wizard/wiki/Finalize-crowdsale
You can find here the answers to most of your questions.

**Comment by lindsmcw** [comment]
Ok thanks.
