### ISSUE TITLE
(Bug) persist-crowdsale-state-#529: deployment stopped(button"Skip transaction" appears) after 7th transaction if crowdsale has a reserved addresses 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#604]
Issue related new feature,
test page: https://5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com/
### Steps to reporoduce:
1. Start wizard https://5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com/
2. Create crowdsale with one or more reserved addresses
3.Start deployment, confirm seven transaction 
4. Observe the modal
Expected result: deployment should continue, 8th transaction should start
Actual result : after 7th transaction button"Skip transaction" is displayed, process is stopped and wait a confirmation
Reproduced 5 times
Scenario file:
{ "account": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "privateKey": "03c06a9fab22fe0add145e337c5a8251e140f74468d72eab17ec7419ab812cd0",
  "networkID":4,

  "name": "T1RnWn_0005.json",
  "ticker": "test",
  "decimals": 3,
  "reservedTokens":[
    {
    "address" :  "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
    "dimension": "percentage",
    "value": 99.9999
  },
    {
      "address" :"0x41B4073E966c169dB22185805A951A0f1b805320",
      "dimension": "percentage",
      "value": 11.11
    }
  ],
  "walletAddress":"0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "gasprice": 40,
  "mincap": 1,
  "whitelisting":false,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "02/18/2018",
      "startTime": "10:45am",
      "endDate":"02/18/2018",
      "endTime":"03:30pm",
      "rate":100,
      "supply": 200,
      "whitelist":[]
    }]
}

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*https://5a87189fefbe5d658ef89ee4--ico-wizard.netlify.com/invest?addr=0x2F61E9802868120c8C282d577126F0166Ff9b233&networkID=4*

### Do you have screenshots showing the problem?

![screenshot from 2018-02-17 14-50-50](https://user-images.githubusercontent.com/14067096/36346662-ae0df98c-13f7-11e8-901d-3e10c5874187.png)
![screenshot from 2018-02-17 14-50-13](https://user-images.githubusercontent.com/14067096/36346663-af79cb84-13f7-11e8-847a-fd9caa061cdb.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*no*

---

**Comment by fvictorio** [comment]
Thanks @dennis00010011b, I'll look into it.

**Comment by fvictorio** [comment]
Hi @dennis00010011b, I cannot reproduce this. I tested the deploy preview in Rinkeby, using the same data that you posted (except start/end dates and wallet address, that should not be significative).

Could you please make a screencast reproducing this bug, so that I can check if I'm doing the same steps?

**Comment by vbaranov** [comment]
@dennis00010011b @fvictorio as I see in test setup token decimals = 3  < reserved tokens mantissa (99.9999). We have the open issue https://github.com/poanetwork/token-wizard/issues/592. It seems it is doesn't relate to https://github.com/poanetwork/token-wizard/pull/598

**Comment by dennis00010011b** [comment]
@vbaranov @fvictorio 
I cannot reproduce this with decimals more than reserved tokens mantissa.

**Comment by TRIHRD** [comment]
Are you sure you have enough 000 s 100,000,000 capx thanks mal

**Comment by TRIHRD** [comment]
Just received my TREZOR will take me all day to configure ...thanks for the work you are all doing mal
