### ISSUE TITLE
(Question) How to create crowdsale with token wizard

### ISSUE THREAD

**Issue by zero2gold** [poanetwork/token-wizard#607]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Mainnet*

### If you were able to create it, what is the URL of your crowdsale?

*unable to create*

### Do you have screenshots showing the problem?

*No*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*My funds where deducted from metamask 3 timess for nothing*

![metamask](https://user-images.githubusercontent.com/36641610/36390966-de7a35e6-15a4-11e8-80a6-fa96a686039f.png)

I was charged 3 times in metamask while using Token wizard, this is theft and i need something done about this fast.

**Comment by vbaranov** [comment]
Some questions to understand what are you trying to do:
1. Are you trying to create crowdsale with token wizard?
2. How many transactions did you sign?
3. Did you sign all needed transactions to create crowdsale?
4. What does it mean "Illegal Metamask Deduction"? You confirm all actions in Metamask with your own account.

**Comment by vbaranov** [comment]
@zero2gold any details?

**Comment by zero2gold** [comment]
I was trying to create a crowdsale, after siging 3 transactions the third and 4th didnt go through and kept hanging, when i tried to increase the gas and sign it deducted the amount from my account twice and still didnt not continue with the siging of the rest of the transactions. I was left hanging there for over 1 hour

**Comment by zero2gold** [comment]
about $24 was deducted for doing nothing

**Comment by zero2gold** [comment]
Is it safe to try the same crowdsale from scratch again after this issue

**Comment by zero2gold** [comment]
When the system tells me its going to cost 0.05 eth to make the crowdsale is this the finalsum or it will start increasing once the crowdsale starts?

**Comment by vbaranov** [comment]
You shouldn’t do any manipulations with MetaMask except signing transactions during deployment process including increasing gas price. If you saw any errors in Chrome dev console, attach them to investigate. If no errors, you should wait. Deployment process in Mainnet deployment can be slow (tenth of minutes) with slow gas price option.

**Comment by zero2gold** [comment]
Can i start the crowdsale again, if the system tells me it will cost 0.05 ether will it be more than that?

**Comment by vbaranov** [comment]
>Can i start the crowdsale again, if the system tells me it will cost 0.05 ether will it be more than that?

If you are talking about alert like this:

![screen shot 2018-02-20 at 14 56 18](https://user-images.githubusercontent.com/4341812/36422709-56601e46-164e-11e8-8c15-03238a1b332c.png)

it says you
- how many transactions you should sign to set up your crowdsale
- how many estimated gas you'll spend in total for these transactions with your gas price option selected.

You can see in any testnet: Kovan, Rinkeby, Ropsten, Sokol first how much your crowdsale will cost, if you have any doubts. Also, watch the demo [how wizard works](https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Demo) and review [wizard strategy](https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Strategy)
