### ISSUE TITLE
Why send ETH to contract address, can not get Token?

### ISSUE THREAD

**Issue by c0deCn** [poanetwork/token-wizard#608]
https://etherscan.io/tx/0xd51f94b51835fdafe2b52159db702d911bae9f9e0be72c8ae66ab933475cf79c

Please help me to see this TX

**Comment by vbaranov** [comment]
Direct sending ETH to crowdsale smart-contract is disabled preventing from sending it from exchanges. The contribution is available with methodID: https://github.com/poanetwork/token-wizard/wiki/Investment#invest-from-metamask-by-method-signature
