### ISSUE TITLE
(Bug) Manage page: Button "Finalize" enabled after the  finalization was done

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#616]
### Step to reproduce:
1. Create crowdsale
2. Invest the amount that is equals total supply
3. Open manage page as  Owner of crowdsale
4. Distribute tokens (if available)
5. Finalize the crowdsale
6. Observe button "Finalize"
Expected result:button "Finalize" should be disabled and unclickable.
Actual result:button "Finalize" enabled and clickable

Scenario
```{

  "name": "simple.json",
  "ticker": "test",
  "decimals": 18,
  "reservedTokens":[
    {
    "address" :  "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
    "dimension": "percentage",
    "value": 99
  },
    {
      "address" :  "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
      "dimension": "tokens",
      "value":333
    }
  ],
  "walletAddress":"0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
  "gasprice":40,
  "mincap": 1,
  "whitelisting":false,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "",
      "startTime": "",
      "endDate":"",
      "endTime":"",
      "rate":100,
      "supply": 20,
      "whitelist":[]
    }]
}
```

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/crowdsale/?addr=0x5De864093498a12094051acB3A0a2eA9d322e440&networkID=77*

### Do you have screenshots showing the problem?
Video   *https://drive.google.com/open?id=1XLwN_Kbyj4-EHchQGBGZxj-UoxEjcHSb*

![screenshot from 2018-02-21 09-47-49](https://user-images.githubusercontent.com/14067096/36496794-445af84c-16ee-11e8-90ca-f53889ea3112.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fernandomg** [comment]
@dennis00010011b I just tried to reproduce this bug, but I wasn't able to do so.

Settings are the same, except for the `walletAddress` and `rate`.

You can check it here:
https://wizard.poa.network/manage/0x9982bCCb508C19E61cf683307768d3F88Fda55Cc

I used a publicly known address: `0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1` whose private key is: `4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d`.

Check if you're able to see `Finalize` button enabled and if not, try to re-reproduce the bug with that address, so it's easy to verify it from our side.

Thanks!

**Comment by dennis00010011b** [comment]
@fernandomg 
I can't reproduce this issue too.

**Comment by fvictorio** [comment]
@dennis00010011b Maybe what happened was that, after finalizing and refreshing, the button showed as enabled (but if you refreshed again, it would be correctly disabled).

Something similar happens sometimes in the invest page: you buy N tokens, the page is automatically refreshed, but the shown balance is not correct. If you refresh again it shows the correct number.

My guess is that there is some kind of delay between the receipt of the transaction plus the refresh, and web3 or metamask being aware of that change in the contract state.

Not sure if there's something we can do. Maybe waiting a little after the transaction is confirmed, and then doing the refersh? @vbaranov what do you think?

**Comment by vbaranov** [comment]
>My guess is that there is some kind of delay between the receipt of the transaction plus the refresh, and web3 or metamask being aware of that change in the contract state.

I have the same feeling about that.

>Not sure if there's something we can do. Maybe waiting a little after the transaction is confirmed, and then doing the refresh?

Yes, let's do a small delay (`500 ms`) before refresh.
