### ISSUE TITLE
(Feature) Stats section

### ISSUE THREAD

**Issue by pablofullana** [poanetwork/token-wizard#620]
As a (new) User, I'd like to see general stats about Token Wizard, so I can have a sense about its overall usage.

I think that having a new section/component in the UI to show some stats will add value to the site.

- number of created crowdsales
- number of ongoing crowdsales
- number of completed crowdsales
- total raised funds

Completely open for discussion.

**Comment by vbaranov** [comment]
I support this idea. And as we have already introduced Registry for crowdsales before here https://github.com/poanetwork/token-wizard/pull/404, we can listen [Added()](https://github.com/poanetwork/ico/blob/master/contracts/Registry.sol#L11) event to get all crowdsales created with Token wizard on Mainnet. We could create additional page at wizard which can be accessible from the [main Wizard page](https://wizard.poa.network/) and from [landing page](https://poa.network/wizard)
