### ISSUE TITLE
reserved tokens not allocated

### ISSUE THREAD

**Issue by pe6o32** [poanetwork/token-wizard#628]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x89B70af23023500419E52fC8b73Db002b217E9da&networkID=3

### Do you have screenshots showing the problem?

no

### Do you see errors in the dev console? If yes, please include a screenshot

no

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

no errors

---
The problem is that after finalizing the crowdsale the reserved tokens never get allocated. I tried also accessing the finalize method manually from myetherwallet but it seems to be already executed.

**Comment by vbaranov** [comment]
You have no reserved address for your token: 

![screen shot 2018-02-25 at 21 28 17](https://user-images.githubusercontent.com/4341812/36644966-eee6d0e2-1a72-11e8-8587-5e8eef03bb2d.png)

I guess you forgot to click "+" button at the configuring of reserved tokens in step 2 of wizard. Relates to https://github.com/poanetwork/token-wizard/issues/486.
