### ISSUE TITLE
(Bug) Add validation to decimal :  if  field is empty

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#634]
Related https://github.com/poanetwork/token-wizard/issues/632
### Problem:
User able to proceed with wizard if decimal field is empty. As a result deployment can't be finished.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Kovan, Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*weren't able *

### Do you have screenshots showing the problem?

![screenshot from 2018-02-27 12-31-09](https://user-images.githubusercontent.com/14067096/36753484-2288bf7a-1bbb-11e8-94dc-7abf70a1f054.png)
![screenshot from 2018-02-27 12-33-45](https://user-images.githubusercontent.com/14067096/36753496-2c3fd68e-1bbb-11e8-8be6-8cb1ba9b2823.png)
[wizard.poa.network-1519763968231.log](https://github.com/poanetwork/token-wizard/files/1764610/wizard.poa.network-1519763968231.log)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

[wizard.poa.network-1519763968231.log](https://github.com/poanetwork/token-wizard/files/1764612/wizard.poa.network-1519763968231.log)

---

**Comment by fernandomg** [comment]
@dennis00010011b I couldn't reproduce it in production.

**Comment by dennis00010011b** [comment]
@fernandomg It still possible if user return back from step 3. Then decimal field is empty  but user can click button 'Continue and proceed.
https://github.com/poanetwork/token-wizard/issues/635

**Comment by fernandomg** [comment]
@dennis00010011b oh, I see. So this should be solved as part of the solution of #637 then.

**Comment by fernandomg** [comment]
This bug was fixed as part of https://github.com/poanetwork/token-wizard/pull/705
