### ISSUE TITLE
(Bug) Decimals value is  lost if user returns back from step3 to step2

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#635]
Related #632
### Step to reproduce:
1. Open wizard, go to step 2
2. Fill out fields name, ticker, decimals
3. Click button "Continue"
4. Return back to step 2(click browser's button "Back" or keys "Alt+Left Arrow")
5. Observe fields decimals 
Expected result :fields decimals  should contain values  which was entered (like field Name and Ticker)
Actual result: fields decimals is empty.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*n/a*

### If you were able to create it, what is the URL of your crowdsale?

*n*/a

### Do you have screenshots showing the problem?

https://drive.google.com/open?id=1YJ7AQGoRnsG0jqwe4lYBCqcTNxoSYN7E

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fvictorio** [comment]
I think a lot of things will break if you go back to a previous step.

@vbaranov Is this a feature that we should support? If not, maybe a simpler solution would be to just not allow going back (maybe by instructing react-router to not push the step pages to the history, if that's possible).

**Comment by vbaranov** [comment]
>Is this a feature that we should support?

as we have no *back* button in Wizard UI we shouldn't support this feature, imo. But it would be user-friendly to switch between steps before deployment. I added this feature request: https://github.com/poanetwork/token-wizard/issues/637.

>If not, maybe a simpler solution would be to just not allow going back (maybe by instructing react-router to not push the step pages to the history, if that's possible).

I am ok with this quick solution if it will work.

**Comment by fvictorio** [comment]
Closing this in favor of #637.
