### ISSUE TITLE
(Feature) add *back* button to switch to previous step before deployment started

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#637]
**Problem**:  A user has no supported ability to return to the previous step before deployment. Some use cases: 
- user decided to reserve more tokens at crowdsale setup step
- user decided to change token ticker, name at crowdsale setup step

**Solution**:  Add *back* button on the left of *continue* button for second and third steps of wizard

**Comment by fvictorio** [comment]
@vbaranov Some thoughts on this.

As far as I know, the good practice here is to just use the browser history. Even when there are "back" buttons in the UI, I think they just call the `window.history.back` method. So I guess we can't avoid the issue of properly handling the browser history.

I know I said in another issue that a quick fix was to use react-router to avoid pushing the steps to the history stack, but that was a way of completely avoiding the possibility of going back. If we want that possibility, then taking advantage of the browser's history is the way to go.

There's a good chance that this will be easy to do: maybe just initializing the inputs with the values in the stores is enough. But I wouldn't be surprised if we found issues with the internal consistency of the app state.

If you are OK with this approach, I will give it a try.

**Comment by fvictorio** [comment]
Closed by #705. The follow-up issue is #717.
