### ISSUE TITLE
problem with ico-wizard

### ISSUE THREAD

**Issue by happyse27** [poanetwork/token-wizard#643]
the ico wizard keeps hanging at this stage at https://wizard.oracles.org/4
![image](https://user-images.githubusercontent.com/20754985/36829171-d5b602a8-1d58-11e8-8630-14e3b799bd59.png)

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by happyse27** [comment]
rinbeky network used. error no, just hang there at above screen

**Comment by dennis00010011b** [comment]
Look at MetaMask icon in top right corner of screenshot. There are  6 transactions wait for submitt. You have to submit a transaction every step for continue the deployment

**Comment by happyse27** [comment]
Got it thanks. created smart contract

![image](https://user-images.githubusercontent.com/20754985/36834108-b55c76d6-1d6c-11e8-8a76-d619fabdffc7.png)

![image](https://user-images.githubusercontent.com/20754985/36834147-d8b23616-1d6c-11e8-9e06-f14ffd7c6bf4.png)

https://etherscan.io/tx/0xc8f352a41053e377c75f1d4ca461f06dd4122a33c1cdd2df546b6f6dc85ed5b7

https://etherscan.io/address/0xb8953db3509b302d0b759badf1210b7f18d539e4
But i cant manage to retrieve back the smart contract that i created.

**Comment by happyse27** [comment]
not sure why for above?

**Comment by vbaranov** [comment]
You signed only first tx. You could see the alert before deployment stage with the number of transactions you need to sign. You need to sign all of them to finish deployment process. Please take a look to the demo https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Demo.

**Comment by happyse27** [comment]
Thanks. But signed only first tx. means i need to send in the ethereum to the crowdsale after i created the smart contract?

**Comment by happyse27** [comment]
![image](https://user-images.githubusercontent.com/20754985/36879417-a7703430-1dfe-11e8-8d7a-a37823e24c91.png)

Thanks. I saw the video you given on signing tx. But I am always stuck at https://wizard.oracles.org/3 and metamask does not prompt signing the transaction to design.

I tried to load the step 4 by opening to create the crowdsale, but the new windows screen just hang there. 
![image](https://user-images.githubusercontent.com/20754985/36879768-4866cbd2-1e00-11e8-8b82-7526a205c357.png)

I have already logged in to metamask. 

Kindly assist. Thanks

**Comment by kmmr12** [comment]
Hi So trying to submit a crowd on the token wizard via Meta Mask. Everything was working fine until I got to this step. Now it can't get passed the step to submit the crowd sale. I tried reloading the webpage bt I keep getting error saying transaction has failed please retry.
![tokenwizard1]
(https://user-images.githubusercontent.com/14298602/63715069-05464000-c811-11e9-91a6-086b21b35b76.png)
