### ISSUE TITLE
(Bug) Unable to start deployment with low gas price

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#645]
### Steps for reproduce:
1. Open Wizard https://wizard.poa.network/
2. Click button "New crowdsale"
3. Click button "Continue"
4.Fill out "Name", "Ticker", "Decimals"(I used decimals=12)  with correct data
5. Click button "Continue"
6. Fill out ""Rate", "Supply" with correct data (others fields by default)
7. Set checkbox GasPrice=Safe and Cheap (2 GWei). Click button "Continue"

Expected result : deployment should start or any warning should be present 
Actual result: nothing happens, button "Continue" just non-clickable
The same results if gasprice less than 19.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Kovan, Sokol, Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*n/a*

### Do you have screenshots showing the problem?

https://drive.google.com/open?id=17aU7s6V4Y48YnHQ442BiABBhn4Q0eeRp

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fvictorio** [comment]
This is a regression bug, I'll fix it ASAP.
