### ISSUE TITLE
(Feature) Add warning and pause deployment if user accidentally change MetaMask account while deployment

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#647]
Inspired by https://poanetwork.slack.com/archives/G8HRTP6JZ/p1519910256000437
###  Problem:  
if user accidentally change the metamask account while deployment the deployment continues, option "skip transaction" is  available for next 3-4 transaction and deployment freezes even if user returns back to right account.
###  Possible solution: 
  1. Should be warning : "Not owner. Unable to continue ..........etc."
  2. Deployment should be paused until user switches to right Metamask account.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/invest?addr=0x719c2571Af05B64a8c8f17E69c7720BC727368AD&networkID=4*

### Do you have screenshots showing the problem?

*https://drive.google.com/open?id=1NNIZsGv3hZMzmXRIk9tdg_90zBErkpjs*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fvictorio** [comment]
This issue and https://github.com/poanetwork/token-wizard/issues/593 may be related. The problem is not the same, but the solution is similar (handling metamask events). See my comment there for a possible approach
