### ISSUE TITLE
Can't create crowdsale

### ISSUE THREAD

**Issue by happyse27** [poanetwork/token-wizard#648]
Thanks. I saw the video you given on signing tx. But I am always stuck at https://wizard.oracles.org/3 and metamask does not prompt signing the transaction to design.

![image](https://user-images.githubusercontent.com/20754985/36880074-c3b39dbe-1e01-11e8-9d6d-3eb222a7d4a9.png)

I tried to load the step 4 by opening to create the crowdsale, but the new windows screen just hang there.

![image](https://user-images.githubusercontent.com/20754985/36880086-d18efc94-1e01-11e8-8381-4c7f2de52186.png)

I have already logged in to metamask.

Kindly assist. Thanks

**Comment by dennis00010011b** [comment]
@happyse27  It may be problem with gas price https://github.com/poanetwork/token-wizard/issues/645.   
In the step 3 in section "Gas price"  set checkbox "Custom" and enter value 20 or more. After that  click button "Continue" and deployment should start.

**Comment by happyse27** [comment]
![image](https://user-images.githubusercontent.com/20754985/36881733-ae59584c-1e0a-11e8-9f3c-d85cdd935406.png)

Hi, after this step it does not work and Cant go to step 5
![image](https://user-images.githubusercontent.com/20754985/36881755-cbc37188-1e0a-11e8-9ccb-88cbd3cfc6e2.png)
 see above. and it prompted below.

Please advise how to go to step 5 and also verify in etherscan.io thanks

**Comment by dennis00010011b** [comment]
Could you please provide input data? May be you have started deployment with empty decimals field. Also it is not recommended to refresh page and skipping transaction during deployment.

**Comment by happyse27** [comment]
thanks. i restarted the whole process and got it.

![image](https://user-images.githubusercontent.com/20754985/36883866-05c16072-1e18-11e8-8c93-d30ebde41911.png)

And i am charged 48USD for a smart contract creation testing. Not too friendly. Putting low gas is half an hour wait at least: see below

![image](https://user-images.githubusercontent.com/20754985/36883839-e3b8cf74-1e17-11e8-9659-ee7a298d0c15.png)

![image](https://user-images.githubusercontent.com/20754985/36883902-46112cb6-1e18-11e8-9c2f-267a4a6876eb.png)

**Comment by fvictorio** [comment]
> And i am charged 48USD for a smart contract creation testing.

For testing purposes, it may be better to use one of the testnets ([Rinkeby](https://faucet.rinkeby.io/), [Sokol](https://faucet-sokol.herokuapp.com/), etc.)

**Comment by happyse27** [comment]
Hi,

 I managed to create smart contract. And sent some ethers.

 1)  Refer to below : when i retrieve smart contract this page seemed to be not retrieveable.

 
![image](https://user-images.githubusercontent.com/20754985/36929059-f4e7c91c-1ec6-11e8-9554-086304cb80c1.png)

 2) contributions when crowdsale is still on cant work afrer each account's first successful contribution
![image](https://user-images.githubusercontent.com/20754985/36929085-464dd47c-1ec7-11e8-9fd4-c47ef176073c.png)

 successful one:
https://rinkeby.etherscan.io/tx/0x043de554412d3e958345bf83f41194ec57f5f1f0b9b3313a7f54a35022972003

 unsuccessful one:
https://rinkeby.etherscan.io/tx/0xfbe3bebadab7a28594311b0e56e262bdded0a8bc30b5dba6722c03ce82e6c259

**Comment by happyse27** [comment]
3) i am confused, send ether to token address in crowdsale page or crowdsale address in crowdsale page (please have some tooltips. thanks)

**Comment by happyse27** [comment]
4) https://wizard.oracles.org/manage/0x8AD02Fe547120f0a3610229C9960C5aA57Bdc2C7

This contract did not send back the reserved tokens for 0x692aC590417Bf0f241c5E08AC283BCB0dD83E562 10000 and 0x08D1A7B85eF5c8b01b59661F983845Dc02F634f1 20%

**Comment by vbaranov** [comment]
@happyse27 

1. Are you sure your Metamask is unlocked and you are connected to Rinkeby? If yes, see logs in Chrome dev console.
2. You made contributions in a wrong way. A user can contribute only with methodID. Please read instruction how to contribute https://github.com/poanetwork/token-wizard/wiki/Investment
3. Please read carefully instruction above.
4. I don't see that you distributed reserved tokens. Please read instruction how to distribute https://github.com/poanetwork/token-wizard/wiki/Distribute-reserved-tokens

If you still have any questions, please create a new issue. 1 issue for 1 question. But I recommend you first try to find answers to any of your questions in our wiki https://github.com/poanetwork/token-wizard/wiki.
