### ISSUE TITLE
how to reflect ethereum collected in ico and the tokens left in wordpress?

### ISSUE THREAD

**Issue by happyse27** [poanetwork/token-wizard#652]
hi Support,

 I know it is not relevant. But how to do these above? i know using web3, tried cant work. Tried ico progress viewer plugin does not work

 know it is not relevant, but need some kind assistance.

Thanks
Andrew

**Comment by vbaranov** [comment]
It is unclear how can I help you there. Anyways, It is outside of Token Wizard support.
