### ISSUE TITLE
how to withdraw remaining tokens unsold and ether desposit in crowdsale?

### ISSUE THREAD

**Issue by happyse27** [poanetwork/token-wizard#657]
Hi Support,

 I realized that the ico wizard somehow does not take care of the two things above? 

 How do we take care of that?

Thanks
Andrew

HP : 96302109

**Comment by happyse27** [comment]
btw, i have successfully created crowdsale test and managed simulated to buy and crowdsale ended successfully.

**Comment by happyse27** [comment]
any news? Can ico wizard set minimum cap of ether contribution?

And also, the crowdsale ether collected and token unsold how to withdraw from the smart contract?

**Comment by fvictorio** [comment]
Hi @happyse27. The issue tracker is for reporting bugs with the application. If you have questions, please ask them in the [gitter channel](https://gitter.im/poanetwork/ico-wizard). Thanks.
