### ISSUE TITLE
Can not contribute to the campaign 

### ISSUE THREAD

**Issue by seogram** [poanetwork/token-wizard#663]
I deployed my token successfully on Rinkeby network but when try to contribute I am getting the following error :
bluebird.js:1468 Warning: a promise was created in a handler but was not returned from it
    at y (https://wizard.poa.network/static/js/main.e6d39743.js:1:1516518)

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Rinkeby

### Do you see errors in the dev console? If yes, please include a screenshot

![image](https://user-images.githubusercontent.com/27703830/37151439-ca62195a-22d5-11e8-8ee4-bad275e0d319.png)

**Comment by fernandomg** [comment]
Hey @seogram, I've just tried it and worked fine. I went to: https://wizard.poa.network/invest?addr=0x3849De718D75f8eC30d084a0F4bf846c28F190Bc&networkID=4

And bought 120 Tokens with `0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0` account.

![image](https://user-images.githubusercontent.com/3315606/37151978-70a575fc-22b6-11e8-9d6f-f2400f2ca051.png)

Try refreshing the page

**Comment by vbaranov** [comment]
@seogram do you still have a problem with contribution to your test crowdsale?

**Comment by seogram** [comment]
It is solved now , thanks
