### ISSUE TITLE
Smart contract code unable to verify on etherscan

### ISSUE THREAD

**Issue by OidLife** [poanetwork/token-wizard#666]
The zip file your system supplied us, when we go to verify the code, it will not verify on etherscan. 
The system states “Error! Unable to generate Contract ByteCode and ABI” In addition, we found a published fix online that states a workaround to this issue but that did not fix the problem either. Any information I can provide, please let me know.  

Update: Another error is stated when verifying. Says optimization error about it stated "=NO" when in our txt file you provided us, it states "true".

**Comment by vbaranov** [comment]
@OidLife 

1. Which network do you use? mainnet?
2. Did you see verification guide https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts ?
3. Please attach screenshot of verification page with all filled fields

**Comment by OidLife** [comment]
We were able to get it to verify finally. However Etherscan is showing bugs in solidity but gave it the thumbs up as verified. " Warning: The compiled contract might be susceptible to ZeroFunctionSelector (very low-severity), DelegateCallReturnValue (low-severity), ECRecoverMalformedInput (medium-severity), SkipEmptyStringLiteral (low-severity) Solidity compiler bugs."

**Comment by drdonjuan** [comment]
Hello Oidlife,

I'm facing the same problem. Could you please help me in that, how did you manage to fix it? May I have your phone number or email address to get lesson from you? Mine is 00447513662854 just give ma miss call and I will call you back. Much appreciated.

**Comment by cellan** [comment]
this  solidity version don't match```
