### ISSUE TITLE
(Bug) Long token's name is overlapped with ticker's name

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#668]
Step to reproduce:
1. Set token's name with maximum length
2. Create crowdsale. Observe the invest page.

Expected result: token's name should displayed 
Actual result: token's name is overlapped with ticker's name

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/invest?addr=0x1C8Ca9743bc414e48Cc23b503D1E4B27e0C28CC5&networkID=77*

### Do you have screenshots showing the problem?

*
<img width="1440" alt="screen shot 2018-03-08 at 11 38 23" src="https://user-images.githubusercontent.com/14067096/37172657-492873ac-22c6-11e8-8cff-5fd1d2bb40c4.png">
*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by fvictorio** [comment]
Two possible fixes come to mind:

1. Moving the "Ticker" value to its own row.
2. Adding ellipsis to the name (so it would look like "123456789012..." (and a tooltip that shows the full name)

The only problem with option 1 is that I don't know how it can affect the look of the page when embedded in an iframe.

@fernandomg, @vbaranov, thoughts?

**Comment by fernandomg** [comment]
I prefer to go with the option 1, as there are cases where name can use the whole row...

![image](https://user-images.githubusercontent.com/3315606/37473897-e68c1e78-284d-11e8-89e0-5316b751f5f3.png)

I'll review how that affects e2e tests and iframe height.

@vbaranov, are you Ok with this approach?

**Comment by dennis00010011b** [comment]
@fernandomg It won't affect to e2e tests
