### ISSUE TITLE
(Bug) Wrong rate value (long mantissa)

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#670]
Related https://github.com/poanetwork/token-wizard/pull/631
Step to reproduce:
1. Create crowdsale with parameters: decimals=6, rate=1500
2. Proceed until invest page
3. Observe rate value on crowdsale page
4. Observe rate value on mange page

Actual result: rate should be 1500
Expected result: rate is 1500.0000000000016   (13 digits after comma)
Reproduced with rate =1750
Not reproducible if rate has round value like 10, 100, 1000 etc.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/crowdsale?addr=0xd90E605427bdf4B2A7cB8AD3DD6986dC7c13D366&networkID=77*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-08 at 12 17 22" src="https://user-images.githubusercontent.com/14067096/37174756-60203e0e-22cc-11e8-9595-1a4ecd090a0f.png">
<img width="1440" alt="screen shot 2018-03-08 at 10 49 34" src="https://user-images.githubusercontent.com/14067096/37174798-799e6efa-22cc-11e8-9f31-aef568c59e91.png">
<img width="1440" alt="screen shot 2018-03-08 at 11 36 27" src="https://user-images.githubusercontent.com/14067096/37174801-7b6b59d2-22cc-11e8-95ff-17f9b551dea2.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by fernandomg** [comment]
This is no longer an issue

@dennis00010011b can you revalidate?

**Comment by dennis00010011b** [comment]
This issue is  not reproducible anymore
