### ISSUE TITLE
(Bug) Unable to buy minimal (defined by decimal) value

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#671]
Step to reproduce:
1. Create crowdsale with parameters: decimals=3, rate=1.5, mincap=0
2. Open crowdsale page and try to buy amount 0.001
Expected result: 
  - should be allowed to buy 0.001 tokens (as defined by decimal)
  - warning shouldn't displayed 
Actual result: 
  - Warning present:"number of tokens to buy should be positive and should not exceed 2 decimals"
 - Minimal allowed purshase is 0.01

Not reproducible with round value of rate:
decimals=3, rate=1000, mincap=0

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/invest?addr=0x4b971686d11d2DDEC813823c2Cd292D687a1D265&networkID=77*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-08 at 12 52 52" src="https://user-images.githubusercontent.com/14067096/37176885-92628d30-22d2-11e8-8828-cc6f1805c4b0.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by fvictorio** [comment]
@vbaranov should we allow non-integer rate values?

@dennis00010011b you input "3" as decimal value but the error message said "2", is that correct? Because that may be another bug.

**Comment by dennis00010011b** [comment]
@fvictorio Yes, it is correct. Decimals is 3 but message said '2' in this case.  
I think these two  bugs arise from  the same root

**Comment by fernandomg** [comment]
@vbaranov @dennis00010011b is it valid to use a fractional rate?

**Comment by vbaranov** [comment]
Fractional rate is not the real case and leads to complexity, imo. Let's limit to integers.
