### ISSUE TITLE
(Bug) Multitier: Wallet address fields are empty  for tiers #2,3,..

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#673]
### Step to reproduce:
1. Create crowdsale with 3 tiers.
2. Proceed till Step 4
3. Observe crowdsale contract, fields 'Wallet address' for tiers #2,#3
Expected result: 
  - wallet address should displayed for every tiers OR wallet address should displayed once for entire crowdsale

Actual result: fields 'wallet address' are empty for tiers 2,3

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/invest?addr=0x215088b2177109AD7f0975A3d9F54831e888a5E7&networkID=77*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-08 at 19 37 03" src="https://user-images.githubusercontent.com/14067096/37189613-29b77ccc-230a-11e8-8590-076b35f76d12.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fvictorio** [comment]
In my opinion, the main issue here is not that those values are empty, but that the wallet address should not be shown in each tier. Instead it should be shown as a global value. At least that's the way it's configured in step three.

On the other hand, the deployed contracts do have a wallet address per tier, if I remember correctly. If we want this view (the step 4 after the deply) to reflect the smart contracts state, maybe the correct solution is just to fix the empty inputs as described.

**Comment by vbaranov** [comment]
>In my opinion, the main issue here is not that those values are empty, but that the wallet address should not be shown in each tier. Instead it should be shown as a global value. At least that's the way it's configured in step three.

yes, I agree, that wallet address should be a configuration of a crowdsale, not a tier.
