### ISSUE TITLE
(Bug) Unprecise value of total supply after modification of tier

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#674]
Steps for reproduce:
1. Create modifable crowdsale with parameters:
 - decimals 18
 - tier 1: rate 1000, supply 1000
 - tier 2: rate 500, supply 500
 - tier 3: rate 250, supply 250

2. Change tier 1: rate =5000, supply = 5000.
3. Open invest page, observe value of supply.

Expected result : total supply should be 6250
Actual result:       total supply is 6249.999999999999  (12 digits)

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/invest?addr=0xA72fEaffbd084e1e512B5Bc856638124568b0e60&networkID=77*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-08 at 20 19 48" src="https://user-images.githubusercontent.com/14067096/37194725-67bdb2ce-2324-11e8-8864-e78613c6dd2f.png">
<img width="1440" alt="screen shot 2018-03-08 at 22 16 12" src="https://user-images.githubusercontent.com/14067096/37194760-a299b294-2324-11e8-9a71-640cdddd5f7e.png">

<img width="1440" alt="screen shot 2018-03-08 at 22 20 12" src="https://user-images.githubusercontent.com/14067096/37194734-729a3b04-2324-11e8-9b53-5f5a7afe7618.png">

<img width="1440" alt="screen shot 2018-03-08 at 23 04 13" src="https://user-images.githubusercontent.com/14067096/37194873-2ab9a904-2325-11e8-95b0-8b50668d5f52.png">
### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by fvictorio** [comment]
@dennis00010011b Does this happen if you use those values directly in the crowdsale creation?

**Comment by dennis00010011b** [comment]
@fvictorio 
No. It happens after changing  tier in manage page .
See one more screenshot, crowdsale page right after creation


<img width="1440" alt="screen shot 2018-03-08 at 20 34 16" src="https://user-images.githubusercontent.com/14067096/37223865-b69fec24-2386-11e8-92f1-554097350b22.png">
