### ISSUE TITLE
error while "Associate Crowdsale address to current account"

### ISSUE THREAD

**Issue by Tusharsb** [poanetwork/token-wizard#688]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
ropsten. i ran a local instance of testrpc using https://github.com/trufflesuite/ganache-cli

### If you were able to create it, what is the URL of your crowdsale?
http://34.216.200.61:3000/

### Do you have screenshots showing the problem? Do you see errors in the dev console? If yes, please include a screenshot
![associate_crowdsale_address_to_current_account](https://user-images.githubusercontent.com/1430472/37400741-dc22344c-27ab-11e8-825a-a98d699495e9.png)

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.
N/A

---

**Comment by fvictorio** [comment]
I updated https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Local-Dev-Version with these instructions.

**Comment by Tusharsb** [comment]
Thanks @fvictorio . This creates another problem. I stopped my ganache. And ran:
```
npm run ganache
npm run deployRegistry
npm start
```
I logged out of my metamask. Successfully logged into the private network created by `npm run ganache` command above. 

And on 4th step I get the following error:
![no contract would deploy now](https://user-images.githubusercontent.com/1430472/37402091-41b5a1f0-27b0-11e8-9bb1-0f29bb7e0a0f.png)

My metamask also is giving this problem:
![inaccurate nonce detected by metamask](https://user-images.githubusercontent.com/1430472/37402113-5bcbfb20-27b0-11e8-80a4-8b400f63fdf1.png)

**Comment by fvictorio** [comment]
Try disabling and enabling MetaMask (right click in the MetaMask icon, manage extensions, uncheck "Enabled" and then check it again). Then load the private key again and see if that works.

**Comment by Tusharsb** [comment]
with `npm run ganache` I am able to deploy zero contracts. so i stopped the ganache which ran after `npm run ganache`. then ran ganache again (using `ganache-cli` in my terminal. copied the contract address from ganache into `.env` file against the key `3` (the key for ropsten) )

With `ganache-cli` instead of `npm run ganache` I am atleast able to go till 4 out of 12 contract deployment steps in step4 sucessfully. Not able to successfully deploy the 5th contract as in my first screenshot

**Comment by Tusharsb** [comment]
Sorry. But what you mean by 'Unlock the account' created by ganache ?

**Comment by fvictorio** [comment]
Import the private key in metamask. For example, the private key of the first account is `4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d`.

**Comment by Tusharsb** [comment]
> Import the private key in metamask
Yes I was doing that.

> To be extra sure, follow these steps in order:
I followed all these steps in order and finally the issue is resolved. All contracts deployed on blockchain run by ganache. Thanks @fvictorio 

Another amateur question: i specified 'ropsten` in `/src/components/Common/config.js` and chose Custom RPC in my Metamask. When I try pressing Invest button to reach crowdsale page I get the following error. If ganache is run using `npm run ganache` what network should i fill in `/src/components/Common/config.js` and what network I should pick in Metamask ?
![network mismatch](https://user-images.githubusercontent.com/1430472/37406110-6420c7cc-27bc-11e8-89ed-5473021b7210.png)

**Comment by fvictorio** [comment]
Oh, if you want to use a testnet, it should be a lot easier (just `npm start` and select that testnet in MetaMask, no need to run ganache).

I recommend you don't edit `Common/config.js` just yet, first make sure that everything works.

Right now the supported testnets are Ropsten, Rinkeby, Kovan and Sokol.

**Comment by fvictorio** [comment]
Closing this since it's not an issue. If you still have problems, please go to our [gitter channel](https://gitter.im/poanetwork/ico-wizard).

**Comment by Tusharsb** [comment]
Shall someone want to make token wizard work with ganache, check the instructions [here](https://github.com/Tusharsb/token-wizard/wiki/Run-token-wizard-with-Ganache---testrpc)
