### ISSUE TITLE
 CrowdsaleTokenExt Errors

### ISSUE THREAD

**Issue by KoneroDeveloper** [poanetwork/token-wizard#690]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*
Mainnet

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*
https://wizard.poa.network/crowdsale?addr=0x5a4f22fB8fdf877ca3e607C46FeB09be1017Ee65&networkID=1

### Do you have screenshots showing the problem?

*Your answer*
Yes
![crowdsale error](https://user-images.githubusercontent.com/36621244/37420887-3892d22a-27b8-11e8-9d48-6136bbd0f14e.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*
I have been able to verifry the rest of the files except the 'CrowdsaleTokenExt' 
I also used eth to buy the token to my metascan eth address and it was successful however when you check Konero (XKO) on etherscan you  see 2 Konero xko name appear and you get this view
![konero 1](https://user-images.githubusercontent.com/36621244/37421362-63b8e1a0-27b9-11e8-810f-bb987af340d9.png)

and this

![konero 2](https://user-images.githubusercontent.com/36621244/37421390-796cf95a-27b9-11e8-897b-0d5909c51b89.png)

My total supply is 10 million i dont know why its showing 100 only. I used the same Current account to purchase the 100 token.

Finaly how do i transfer all the token to my seserved account should the crowdsale be unsuccessful in getting to target or hardcap ?

Thank you.

---

**Comment by vbaranov** [comment]
>My total supply is 10 million i dont know why its showing 100 only. I used the same Current account to purchase the 100 token.

Token form Token Wizard is mintable. You see the amount of sold tokens.

>Finaly how do i transfer all the token to my seserved account should the crowdsale be unsuccessful in getting to target or hardcap ?

There is no refund strategy for Token Wizard yet

Regarding to verification issue:
1. attach zip summary files for crowdsale
2. attach a screenshot of all filled fields for verification of Token contract before you click _Verify_ button

**Comment by KoneroDeveloper** [comment]
Please examine the website https://www.konero.co   i was able to get source code through etherscan and uploaded it to the website  but i believe marketing has been one of my problems in getting reesult in the crowdsale. Can i extend the date of the crowdsale to another month so i can focus more on marketing and advertising it?

**Comment by vbaranov** [comment]
>Can i extend the date of the crowdsale to another month so i can focus more on marketing and advertising it?

https://github.com/poanetwork/token-wizard/wiki#managing-the-crowdsale
