### ISSUE TITLE
ICO Token Wizard issues (Mozilla Firefox)

### ISSUE THREAD

**Issue by TheGillonaire** [poanetwork/token-wizard#696]
If you are reporting a problem with Token Wizard, please include the following information:

I went through the wizard and it said it was 42 transactions @ 0.05ETH 

after getting to 30th transaction the website froze or kicked me out 

I had to redo it

After getting to very end I am trying to save the file and it will not save

I also tried to click continue and it will not continue 

I also cannot verify on etherscan the contract

### Which network did you use?

I don’t think I got this far yet

### If you were able to create it, what is the URL of your crowdsale?

Was not able to get past page 4(tried and paid twice)

### Do you have screenshots showing the problem?

I can provide a video since it’s the buttons 

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@TheGillonaire 

We need additional info to understand what is your case:
1. any related screenshot
2. any related video of the problem if you have
3. logs from Chrome dev console
4. which network did you use?

**Comment by TheGillonaire** [comment]
I will repost the video. I used Firefox since my metamist want working on chrome. 

I don’t think I got far enough to use a network

**Comment by fvictorio** [comment]
@TheGillonaire If you send transactions and spent ETH, then you used a network.

I recommend you try to use the app in a testnet first, to see how things work and avoid using real ETH.

**Comment by TheGillonaire** [comment]
https://youtu.be/D64QzSd8sCU

Please tell me if I’m doing something wrong

**Comment by vbaranov** [comment]
>To open the dev console in Google Chrome, press F12, or go to View -> Developer -> Developer Tools, and open the Console tab
If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

**Comment by vbaranov** [comment]
Could you click to any line in logs, save it as archive and attach to issue? It is very hard to investigate your problem by logs from video

**Comment by TheGillonaire** [comment]
I know I’m sorry. Give me a second I will send to you.

**Comment by TheGillonaire** [comment]
[mobx.array] Attempt to read an array index (3) that is out of bounds (3). Please check length first. Out of bound indices will not be tracked by MobX main.95e9ab71.js:1:74681
TypeError: e is undefined[https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type] main.95e9ab71.js:1:864206

firefox will not let me save that way

**Comment by vbaranov** [comment]
Token wizard is not tested on Mozilla Firefox yet. This is why everywhere in wiki we recommend to use Google Chrome. If you can repair your Metamask in Chrome, try the same crowdsale configuration there in any Testnet and let us know the result, we will appreciate it.

**Comment by TheGillonaire** [comment]
Do I need to pay again?? Your site does not have a way for me to pick up where I left off

**Comment by vbaranov** [comment]
If you will choose any tetnet: Kovan, Rinkeby, Ropsten in Metamask you will not use real ether.

**Comment by TheGillonaire** [comment]
I just need the download file from page 4. I made it to page 5 to publish using chrome but for some reason page 4 will not display on chrome and page 4 in Firefox will not let me click download. Don’t worry about it. I was just trying to do this while my developer was at his full time job... he will do it for us.. he understands WAY more then the average person and I feel I am average lol. Thanks
