### ISSUE TITLE
(Bug) Use proper way to instantiate web3 objects

### ISSUE THREAD

**Issue by rstormsf** [poanetwork/token-wizard#706]
Whenever you use 
```
new web3.BigNumber(X)
```
X should be a STRING, not a number.

example:

```
new web3.BigNumber('0.02714285714285714') //success
new web3.BigNumber(0.02714285714285714) //error
```

```
Uncaught Error: new BigNumber() number type has more than 15 significant digits: 0.02714285714285714
```
@fernandomg @pablofullana 

hence why the UI can't load the screen
https://wizard.oracles.org/crowdsale?addr=0x603a69c48a3175e99C06581feFC7a8D22D6ad894&networkID=1
(mainnet)

https://github.com/poanetwork/token-wizard/blob/28b179e29f2fddc3013f3b1e52fbdc5b9f57b0c8/src/components/Common/BigNumberInput.js#L52
`value.toString()` should be

**Comment by dennis00010011b** [comment]
Reproduced it once 
Parameters: decimals=18, rate=1401, supply=51578
Purshase=6+0.000000000000011

<img width="1440" alt="screen shot 2018-03-15 at 22 47 35" src="https://user-images.githubusercontent.com/14067096/37506833-f1c8da32-28a8-11e8-9fa8-82a936f964b3.png">
<img width="1440" alt="screen shot 2018-03-15 at 22 48 25" src="https://user-images.githubusercontent.com/14067096/37506835-f34afe30-28a8-11e8-8ccf-cf83e2323475.png">

[wizard.oracles.org-1521179283492.log](https://github.com/poanetwork/token-wizard/files/1818145/wizard.oracles.org-1521179283492.log)
