### ISSUE TITLE
(Bug) Countdown timer shows time relative to local machine time

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#713]
### Steps to reproduce:
 1. Create crowdsale
 2. Check the countdown timer
 3. Change local time to future or past
 4. Check indication of countdown timer 

Actual result: Countings of timer depends of local machine time T=(Local time - Start time). User actually can not invest even if timer shows that crowdsale is started.
Expected result : Countings of timer should be relative of world global time :T=(Global time- Start time)

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/invest?addr=0x60Fe370A241CE50c02d6F0F9562f5197E175e036&networkID=77*

### Do you have screenshots showing the problem?

https://drive.google.com/open?id=1o7fkSVeOsKe9il0VbWaAt2vj35W-7_UN

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment]
Indeed, let's check whether it works with different time zones. @dennis00010011b could you make such tests and notify us of the results?

**Comment by dennis00010011b** [comment]
I have tested scenarios where  investors buy from from different timezones. There weren't any issue

**Comment by fvictorio** [comment]
I'm closing this for now then. Thanks @dennis00010011b.
