### ISSUE TITLE
https://kovan.etherscan.io/tx/0x42073576a160206e61b4d9b70b436359b8d220f8b88c7c272c77023513c62c3d

### ISSUE THREAD

**Issue by STORcoin** [poanetwork/token-wizard#715]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Kovan*

### If you were able to create it, what is the URL of your crowdsale?

*https://etherscan.io/address/0x1c8696c336b9297f390a2a3cfa04c25395c57a2e*

### Do you have screenshots showing the problem?

*Your answer
[Token Wizard page.pdf](https://github.com/poanetwork/token-wizard/files/1823234/Token.Wizard.page.pdf)
*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*We are done with the crowdsale but don't know the next step to see the total number of coins issued.  Should they show up in the etherscan account?  We issued 100,000,000 but don't see them.  What is the next step after the crowdsale is done*

---

**Comment by STORcoin** [comment]
I see the small amount issued in etherscan as a single transaction, but I don't see the balance of the coins.

**Comment by vbaranov** [comment]
ERC20-compatible token created with Token wizard is mintable with zero initial supply. You can see only sold amount.
Total amount of tokens = sold amount + reserved tokens.
Find your token in https://etherscan.io/tokens by token contracts address.
Steps after crowdsale is ended:
https://github.com/poanetwork/token-wizard/wiki/Distribute-reserved-tokens
https://github.com/poanetwork/token-wizard/wiki/Finalize-crowdsale

**Comment by STORcoin** [comment]
Thank you very much.  It wasn't clear how to get back to the final step and now I have completed it.  Thanks again!!!
