### ISSUE TITLE
Transaction Error

### ISSUE THREAD

**Issue by agripamp** [poanetwork/token-wizard#721]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Kovan Testnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x9D1a1EAe0c56540D2DDc232C13Ad3856b64D8131&networkID=42

### Do you have screenshots showing the problem?

![capture](https://user-images.githubusercontent.com/37555847/37772168-baa45620-2dd1-11e8-9c16-2a2d7ea4b9ed.PNG)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

I have tried to buy tokens from Metamask, including MethodID: 0xa6f2ae3a field and got the above result. I also tried to buy them with MEW and below are"error" shown on dev console.

Can anyone please point what I am doing wrong?

Thanks and regards

---
![image](https://user-images.githubusercontent.com/37555847/37772373-54caf1e6-2dd2-11e8-9ad2-f04ef3e2a5f6.png)

**Comment by vbaranov** [comment]
@agripamp Your test crowdsale is finished. Could you repeat this error with a new alive one? As about your finished crowdsale, you have set global min cap = 1 token. Were you trying to buy more or equal than this value when the error happened?

**Comment by agripamp** [comment]
Thank you Victor. 
You tell me what is relevant for the matter, maybe I did a bit of mess around.
I run another crowdsale now: https://wizard.oracles.org/invest?addr=0x500C18abF0c18F677795450de9DF2089DdF3EC33&networkID=42
The following is all crowdsales I have runned. You can see **same token address** for two of them, created under different testnet. 
![image](https://user-images.githubusercontent.com/37555847/37825271-1ba0a040-2e87-11e8-8c2b-a748b1e9af03.png)
For new crowdsale FLY minimum purchase is also 1 token, but I could buy through Metamask, small quantity
![image](https://user-images.githubusercontent.com/37555847/37825713-ae051780-2e88-11e8-8028-7fe6667b38d3.png)

By MEW still getting same error and can´t finalize the purchase. Neither could add the token FLY in the Kovan net, since says that already exists (COW on Rinkeby)
![image](https://user-images.githubusercontent.com/37555847/37825611-61c7b490-2e88-11e8-850b-344397be6186.png)

**Comment by agripamp** [comment]
I could also capture a flash screen shot that come up on MEW after reject the purchase
[MEW.docx](https://github.com/poanetwork/token-wizard/files/1841262/MEW.docx)

**Comment by vbaranov** [comment]
So, you have no problem with contributing, right? I've successfully contribute to your test crowdsale. I see, that your crowdsale is valid. `eror_21` in MEW, perhaps, mean, that you filled in with incorrect token address. Token address id is indicated in `crowdsale`, `invest` pages and in your summary crowdsale files.

**Comment by agripamp** [comment]
What way did you use it? Did you tried MEW? I could make it  now  through MEW, I increased to 2 eth to send and it works. Indeed, I assume if I fill with less than 1 unit, then the wallet warns me with all that bulk of red messages, and reject it

**Comment by vbaranov** [comment]
Show the screenshot from MEW with filled values which then causes the problem.

**Comment by agripamp** [comment]
Yea, is actually a very tiny amount which I can´t adquiere one token
![image](https://user-images.githubusercontent.com/37555847/37837039-14eee250-2eac-11e8-9a1a-2fd1df6d1f25.png)

**Comment by vbaranov** [comment]
You have a global min cap = 1 token. You are trying to buy less than 1 token:

![screen shot 2018-03-26 at 12 30 44](https://user-images.githubusercontent.com/4341812/37898504-a382a4ba-30f1-11e8-9f6d-174f9f18ed39.png)
