### ISSUE TITLE
Has this been used in a production ICO before?

### ISSUE THREAD

**Issue by goktugyil** [poanetwork/token-wizard#724]
Has this code been used in a production ICO before or is it in beta? 

What do I need to do to use this wizard in an ICO?

**Comment by vbaranov** [comment]
> Has this code been used in a production ICO before or is it in beta?

yes, it is in beta https://github.com/poanetwork/token-wizard#disclaimer
yes, it has been used in production https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Projects

>What do I need to do to use this wizard in an ICO?

take a look at the helpful demo: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Demo
