### ISSUE TITLE
(Fix) Stop countdown if hard cap is reached immediately

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#726]
Relates to https://github.com/poanetwork/token-wizard/pull/720#pullrequestreview-106585780

**Comment by fernandomg** [comment]
@vbaranov @dennis00010011b @mariano-aguero

After going back and forth thinking about the UX and the scalability of the solution, I think that the clock counter should be left unmodified; giving the user clear information about the current status of the Crowdsale.

Along this line of thinking,

I had contemplated when the `Crowdsale` is sold out
![image](https://user-images.githubusercontent.com/3315606/43483176-34f891fe-94e1-11e8-9884-4a22a429f4e4.png)

...or when a `Tier` (that is not the last tier) is sold out as well.
![image](https://user-images.githubusercontent.com/3315606/43483191-41462070-94e1-11e8-8931-f53d0c3d45c3.png)

Maybe it would be helpful to add an alert message on page load informing the user about that situation.

Please let me know your thoughts.

**Comment by dennis00010011b** [comment]
@fernandomg 
> ...when the Crowdsale is sold out

In this case you can reset timer to 0 and set timer's status "CROWDSALE HAS ENDED"
<img width="281" alt="screen shot 2018-07-31 at 13 08 52" src="https://user-images.githubusercontent.com/14067096/43484379-0b6e1a70-94c3-11e8-91d6-17705975d3c6.png">

**Comment by mariano-aguero** [comment]
PR #1066 closed
