### ISSUE TITLE
After Edit ICO Wizard Don't save it show an error message, Just Need Change ICO Start date and End Date! and save.

### ISSUE THREAD

**Issue by bitstump** [poanetwork/token-wizard#727]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Metamask*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/crowdsale?addr=0x9E96c74a4e074cb95F4299A661317E8a30244e55&networkID=1*

### Do you have screenshots showing the problem?

*![transaction has failed](https://user-images.githubusercontent.com/37717353/37855522-dbac4bb8-2f19-11e8-8894-d7f12f9db5c5.PNG)
*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
If a user modifies multiple dates at management page we need to change the sequence of the transactions: the first should be a transaction to modify the latest date and the last should be a transaction to modify the earliest date.

**Comment by vbaranov** [comment]
Relates to #752 too

**Comment by vbaranov** [comment]
Fixed in https://github.com/poanetwork/token-wizard/pull/766
