### ISSUE TITLE
(Bug) Unable to change start and end time in the same action 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#728]
Inspired https://github.com/poanetwork/token-wizard/issues/727

Step to reproduce:
 1. Create modifiable crowdsale with 1 tier, start and time should be in the future
2. Open manage page as a owner
3. Change end time, set value in the future
4. Change start time, set value in the future
5. Click button 'Save'
 Expected result: two transaction should be done, start and end time should be changed
Actual result: error message 'TRANSACTION HAS FAILED, PLEASE RETRY'

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Sokol*

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x437Bcd81c0a0Dcacd3305DA2cf76886851b8FCC3&networkID=77

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-24 at 01 56 14" src="https://user-images.githubusercontent.com/14067096/37862422-d48723f4-2f09-11e8-8906-7668934af695.png">

<img width="1440" alt="screen shot 2018-03-24 at 01 59 33" src="https://user-images.githubusercontent.com/14067096/37862434-fbac696c-2f09-11e8-8df4-6703d7f3a243.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

(https://github.com/poanetwork/token-wizard/files/1844219/wizard.oracles.org-1521883454179_1.log)
<img width="1440" alt="screen shot 2018-03-24 at 02 24 54" src="https://user-images.githubusercontent.com/14067096/37862478-9a3816ee-2f0a-11e8-9f1d-52ebacc47e22.png">

---

**Comment by dennis00010011b** [comment]
@fvictorio 
 It still reproducible https://drive.google.com/open?id=1o7fkSVeOsKe9il0VbWaAt2vj35W-7_UN

<img width="1440" alt="screen shot 2018-04-03 at 09 15 11" src="https://user-images.githubusercontent.com/14067096/38261624-9ab5eea8-371f-11e8-9dbb-eee23727cab6.png">

**Comment by fvictorio** [comment]
That's weird. I'll try again with dates more similar to those, but I don't know what else we may be doing differently.

**Comment by fvictorio** [comment]
@dennis00010011b Could you tell me the original start and end dates, and the values to which you changed them?

**Comment by fvictorio** [comment]
Ok, @fernandomg explained it to me: the problem is when you have, for example, start and end on 1 and 5 of some month, and edit them to be 6 and 10 (the start date is moved after the end date). The problem is that the start date transaction is performed first, but it's invalid because the end date wasn't modified yet.
