### ISSUE TITLE
Crowdsale page on website

### ISSUE THREAD

**Issue by KoneroDeveloper** [poanetwork/token-wizard#730]
How do i get the crowdsale page to appear on my website homepage without click to go to the crowdsale page?

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
You could display wizard crowdsale page in iframe on any of your site page: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
