### ISSUE TITLE
(Bug) Unable to add first whitelisted address from manage page  

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#735]
Situation where user enabled the whitelisting but decided to add it later.
Step to reproduce:
1. Create crowdsale : whitelisted, modifiable. Don 't add whitelisted addresses.
2. Open manage page as an owner
3. Add whitelisted address: fill out fields address, min, max, click button "+".
4. Observe button 'Save'
Expected result: button 'Save' should be enabled
Actual result : button 'Save' disabled, user can't add whitelisted address
User can add whitelisted address only in conjuction with other update(ex:start time)

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Test RPC*

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale/?addr=0xB44ecBB322Ee186f09Fe89f9DDB2C1E733e36fF4&networkID=77

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-03-26 at 13 42 28" src="https://user-images.githubusercontent.com/14067096/37933395-e6079efe-30ff-11e8-9aed-3ee183252fdb.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by mariano-aguero** [comment]
@dennis00010011b , I try to reproduce the problem without success
I can add whitelisted addresses whithout problem
Can you confirm this?

Attach images
![issue 735-button-save-disabled-ii](https://user-images.githubusercontent.com/1144028/42238896-b3069006-7ed8-11e8-8c21-44184a765eeb.png)
![issue 735-button-save-disabled](https://user-images.githubusercontent.com/1144028/42238897-b3325b46-7ed8-11e8-8ce9-8cd32547240e.png)

**Comment by fernandomg** [comment]
It worked fine to me as well
