### ISSUE TITLE
source code dose not exist unable to verify

### ISSUE THREAD

**Issue by Ne000** [poanetwork/token-wizard#753]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*MAINNET*

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

* https://wizard.oracles.org/invest?addr=0x0c2d3117AD9Be69E5cEF2800d253E806f29741D6&networkID=1 *

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Not Sure*

Hi please could you help me with my ICO I created with POA. The token I created Data Sovereignty Coin 0xbE34145f13334cB2a76b834194788AD5824342b9 would not verify on etherscan. Below is my communications with etherscan who tell me the source code was unable to produce the basic ERC20 token I followed the procedure on the githud video on the topic I downloaded the file and I tried to verify using the videos on your GitHub. I need your expert help in fixing this problem. Please Help.

i will now copy and past my emil communications with etherscan help

From: Etherscan Helpdesk <contact@etherscan.io>
Sent: Friday, March 23, 2018 10:11:17 AM
To: crypto-king@outlook.com
Subject: Re: Support / Technical Issue 
 
Hi Crypto-king,
Thank you for your email. 
1. Regarding your first question, the source code was unable to produce the basic erc20 token. only the basic math operation function with safety check only.
You can check here how the function of the other source code.
https://etherscan.io/address/0xd26114cd6EE289AccF82350c8d8487fedB8A0C07#code
https://etherscan.io/address/0xd4fa1460f537bb9085d22c7bccb5dd450ef28e3a#code

2.  Regarding "Sorry! The Compiled Contract ByteCode for 'SafeMathLibExt' does NOT match the Contract Creation Code for [0xbE34145f13334cB2a76b834194788AD5824342b9]." 
Please check your code and make sure that your source code function called the creator address. 

Regards
- Etherscan Team [Aizel]

On Thu, 22 Mar at 8:06 PM , Crypto-king <crypto-king@outlook.com> wrote: 
Hi 
Why don't you just answer the questions I asked. 
Thank you.
Get Outlook for Android 

From: Etherscan Helpdesk
Sent: Thursday, March 22, 11:25
Subject: Re: Support / Technical Issue
To: crypto-king@outlook.com

Hi Crypto-king,
Thank you for your email. That source code that you send is not yours, to begin with, it's the SafeMathLibExt source.
Regards
- Etherscan Team [Aizel]
On Thu, 22 Mar at 7:07 PM , Crypto-king <crypto-king@outlook.com> wrote: 
Hi 
Is the contract source code the only problem?what is wrong with the contract source code?
Thank you.
Get Outlook for Android 
From: Etherscan Helpdesk <contact@etherscan.io>
Sent: Thursday, March 22, 2018 10:51:27 AM
To: crypto-king@outlook.com
Subject: Re: Support / Technical Issue 
 
Hi Crypto-king,
Thank you for your email. The issue is you need to contact contract wizard team. The source code is originated SafeMathLibExt. 
Regards
- Etherscan Team [Aizel]

On Thu, 22 Mar at 6:43 PM , Crypto-king <crypto-king@outlook.com> wrote: 
Hi what is the problem exactly?  You asked for all this information what did you discover? 
Get Outlook for Android 

From: Etherscan Helpdesk
Sent: Thursday, March 22, 07:34
Subject: Re: Support / Technical Issue
To: crypto-king@outlook.com

Hi Crypto-king,
Thank you for your email.It appears that your contract source code originated from SafeMathLibExt.You may check with your contract developer regarding your contract source code.
Regards
- Etherscan Team [Aizel]

---

**Comment by vbaranov** [comment]
@Ne000 You didn't attach neither your summary files from step 4 of Wizard nor the screenshot of filled inputs of verification page. I don't know what is your specific problem exactly. But I successfully verified your token contract https://etherscan.io/address/0xbE34145f13334cB2a76b834194788AD5824342b9#code. 
Please see the instruction how to verify contracts: https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts and helpful videos from @hashguide again.
