### ISSUE TITLE
i have problem with timer

### ISSUE THREAD

**Issue by RokMikuz** [poanetwork/token-wizard#754]
timer is only displaying minutes and seconds, but it should display days also.

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.poa.network/manage/0x026Ae2C37A44c9b2415d91ef74A6885ED4e13027

### Do you have screenshots showing the problem?

![screen shot 2018-03-29 at 10 55 01](https://user-images.githubusercontent.com/37638244/38079657-c2e6acde-333f-11e8-8a12-fc8228146ed6.png)

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
Another user [has the same problem ](https://forum.poa.network/t/wrong-start-time-on-crowdsale-invest-page/951)with timer (the crowdsale will start in June, but it shows 3 days): https://wizard.oracles.org/invest?addr=0x21ED7C5bcc78Bd719EE65D95eC65510C81D218da&networkID=1 @fvictorio @fernandomg could you take a look?
