### ISSUE TITLE
Contract Creation and ICO creation issue

### ISSUE THREAD

**Issue by masalathis** [poanetwork/token-wizard#759]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Rinkeby

### If you were able to create it, what is the URL of your crowdsale?

Contract created, crowdsale did not and did not receive download file.

### Do you have screenshots showing the problem?

Yes

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*yes*

---

**Comment by masalathis** [comment]
[wizard.oracles.org-1522658076342.log](https://github.com/poanetwork/token-wizard/files/1867593/wizard.oracles.org-1522658076342.log)
![capture](https://user-images.githubusercontent.com/34694122/38189722-61763d82-362f-11e8-949e-c77776c8d62c.JPG)

**Comment by vbaranov** [comment]
There are no errors in the logs. It seems you didn't wait for the response from the 3d transaction and you refreshed the page. In this case, if all 3 transactions are mined successfully you can skip transactions in Metamask, skip it in Token wizard and continue with the next steps and confirm all other transactions.
