### ISSUE TITLE
Stuck while deploying contract

### ISSUE THREAD

**Issue by Agritoken** [poanetwork/token-wizard#773]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

No, just https://wizard.oracles.org/4

### Do you have screenshots showing the problem?

![image](https://user-images.githubusercontent.com/37555847/38433458-d97bd210-39c2-11e8-848f-bb5a147510f7.png)

### Do you see errors in the dev console? If yes, please include a screenshot

I see one error now. After refresh several times this page, still getting on

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@Agritoken could you 
>if you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

**Comment by Agritoken** [comment]
I´m not sure if is what you need, but is what I got. Let me know. Txs

[wizard.oracles.org-1523034601336.zip](https://github.com/poanetwork/token-wizard/files/1884945/wizard.oracles.org-1523034601336.zip)

**Comment by Agritoken** [comment]
I re-run a new crowdsale process and I think issue was in relation to MinCap field, which was blank. Once I filled then works fine. The issue has been stated by other user also. 
If you consider so, this can be closed. Thanks
