### ISSUE TITLE
Is the percentage setup this way?

### ISSUE THREAD

**Issue by matthewlal** [poanetwork/token-wizard#776]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Sokol

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.poa.network/crowdsale/?addr=0x51F895d5421eBaCCA19bd847ED8eDe9a77c89DDC&networkID=77

### Do you have screenshots showing the problem?

I didn't screenshot how much I reserved.

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

I didn't look.

---

I reserved 10000 tokens on one address, and 20% on another address. After some testing it is clear that the percentage gives me a percentage of how much of the coin I have in my wallet. For example, I purchased 10 tokens and reserved 20%, my final amount when distributing the tokens was 12 tokens. On the other account however I had 0 tokens, but when the reserved tokens were distributed I received the 10000 tokens.

Is the percentage reserved tokens designed this way?

**Comment by vbaranov** [comment]
Reserved tokens in percentage are calculated from the sold amount. 
Example:
1000 tokens are sold in total through the crowdsale
address _A_ is reserved for 20% of tokens.
also, address _A_ has bought 10 tokens through the crowdsale
The total amount of tokens in address _A_ will be 10 tokens + 0.2 * 1000 tokens = 210 tokens
