### ISSUE TITLE
(Bug) local deployment in Windows doesn't work

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#780]
Local deployment in Windows should be double checked. It doesn't work by following these steps https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Local-Dev-Version#prerequisites

**Comment by ksystemsio** [comment]
I got it to build in Ubuntu server 14.x.x with "**npm run build**", after:

$   git clone https://github.com/poanetwork/token-wizard.git wiz
$   cd wiz
$   git submodule update --init --recursive --remote
$   npm install
$   cp .env.example .envgit clone https://github.com/poanetwork/token-wizard.git wiz
cd wiz
git submodule update --init --recursive --remote
npm install
cp .env.example .env

I then moved the build directory in a Win 7 partition and, in Git Bash on Win 7, and ran the following:

$   **npm install -g serve**
C:\Users\turtle\AppData\Roaming\npm\serve -> C:\Users\turtle\AppData\Roaming\npm\node_modules\serve\bin\serve.js
+ serve@6.5.4
added 130 packages in 8.082s

$   **serve -s build**
serve: Running on port 5000

I am now able to change the css, js and html parameters before launching the ICO on the MainNet with the landing page I want to have and all the MetaMask stuff sorted out. Thanks POA Network, you are doing a great job for the community, and the future of humanity.

Mickael LEVY
CEO @ K SYSTEMS LTD
Website: https://ksystems.io
Telegram Channel: https://t.me/ksys1
Twitter: @ksystemsio @mickaelksys
Gitter: https://gitter.im/ksystemsio/Lobby
ERC-20 Token: KSYS
