### ISSUE TITLE
Stuck on Tx status paid ether now whole thing gone

### ISSUE THREAD

**Issue by Gio300** [poanetwork/token-wizard#792]
If you are reporting a problem with Token Wizard, please include the following information:
Idk which network.. tried to make sound coin. I'm dealing with many professional music artists. 
### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

I just clicked new crowdsale

### If you were able to create it, what is the URL of your crowdsale?

Website isn't up yet. That's why I set the crowdsale out for a month

### Do you have screenshots showing the problem?

No.. I'm stick on Tx status screen.. I paid already.. it keeps asking for more money

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

Idk

---

**Comment by Gio300** [comment]
i went ahead and payed for a new crowdsale with your website token wizard.. now i have an error on that

**Comment by vbaranov** [comment]
@Gio300 
>i went ahead and payed for a new crowdsale with your website token wizard.. now i have an error on that

What error? in Chrome dev console? Could you attach log:
>To open the dev console in Google Chrome, press F12, or go to View -> Developer -> Developer Tools, and open the Console tab

>If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

Did you pass through the whole deployment process? Have you got the URL of your crowdsale?

**Comment by vbaranov** [comment]
Closed due no answers

**Comment by Gio300** [comment]
As far as I know the crowdsale is good. Thank you
