### ISSUE TITLE
WaveX

### ISSUE THREAD

**Issue by Gio300** [poanetwork/token-wizard#793]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Kovan*

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0x68F2f9c2221E7Ed262490127936A56Cae292f76d&networkID=1

### Do you have screenshots showing the problem?

well it shows the wrong amount for the goal.. and on other computers besides my own it doesnt show a countdown or any information for the crowdsale

### Invalid crowdsale address is indicated in config and/or in query string /is the error message i see.. cannot access tools or any other page

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

i am unable to access anything besides the page.. no options.. f12 does not work

---

**Comment by vbaranov** [comment]
> well it shows the wrong amount for the goal

What value do you expect for the goal? I see _10400 ETH_

![screencapture-wizard-oracles-org-crowdsale-2018-04-16-12_24_44](https://user-images.githubusercontent.com/4341812/38800939-2de32690-4171-11e8-8175-1e1d153b8387.png)

>and on other computers besides my own it doesnt show a countdown or any information for the crowdsale

Related issue https://github.com/poanetwork/token-wizard/issues/755. User should have MetaMask to display the whole data in invest page.

**Comment by Gio300** [comment]
I redid the crowdsale a third time.. this time the only problem seems to be
it's showing that it's not active.. possibly because my metamask is in main
network and I don't know how to switch it to kovan. Thank you so very much
for replying.. my apologies for making these errors.. but I really really
need your help

**Comment by Gio300** [comment]
The goal is 100,000 ether.. I was able to change that on the third one I did after these last two.. but now it's still not showing up with a time limit until crowdsale begins.. it just says crowdsale has ended.. :(

**Comment by Gio300** [comment]
On my computer screen it shows as having 14 days.. but if I bring up another browser or use my cell phone.. it says crowdsale has ended

**Comment by vbaranov** [comment]
@Gio300 your crowdsale not in Kovan, you have created it in Mainnet `&networkID=1`

>On my computer screen it shows as having 14 days.. but if I bring up another browser or use my cell phone.. it says crowdsale has ended

Without Metamask you will not see the full data of crowdsale

**Comment by vbaranov** [comment]
And you can manage any tier of your crowdsale https://github.com/poanetwork/token-wizard/wiki#managing-the-crowdsale before tier is started if you set up a tier as modifiable.
