### ISSUE TITLE
(Fix) Check status of transactions

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#794]
**Problem**: Token Wizard doesn't check statuses of transactions (invest, management, finalize). It checks the correctness of transaction only based on gas estimations.
**Solution**: check the status of every transaction. And if it is not true return an error alert.

**Comment by fernandomg** [comment]
@vbaranov Could you please explain this issue a bit more in details?

As far as I understand, all the `tx` uses the `sendTxToContract` method, which ends up validating the `status` for the transaction's `receipt`.

Thanks!

**Comment by vbaranov** [comment]
@fernandomg you are right. It is already implemented.
