### ISSUE TITLE
Did not get constructor argument for crowdsale

### ISSUE THREAD

**Issue by drdonjuan** [poanetwork/token-wizard#801]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
The answer is here:

https://forum.poa.network/t/no-contructor-arguments-abi-given-for-crowdsaletokenext-file/960/2?u=viktorbaranov

**Comment by drdonjuan** [comment]
Sorry mate, your reply was not helpful. 
This is the contract address and nothing shows under this contract

0x7B81ded99dF53C243eA3b2627c03f2CF52906CE7

**Comment by drdonjuan** [comment]
![image](https://user-images.githubusercontent.com/38373159/39058817-ee53e34c-44cd-11e8-9ff1-e2e057b026e6.png)

**Comment by drdonjuan** [comment]
Hello
I figured that out how to get the constructor argument. Thanks. However,

The second problem is, for a simple contract made with (a) allowing modification, (b). Disabling white list , I'm unable to get 5 text/5 .sol files. I've seen steve videos and he got a total of 10 files. The one I'm missing is "FlatpricingExt.Txt" and "FlatpricingExt.Sol"

I need help on this.
