### ISSUE TITLE
Contract verify failed on Ropsten test network

### ISSUE THREAD

**Issue by afxgroup** [poanetwork/token-wizard#803]
Hello,
i’m trying to verify the contracts i’ve created on ropsten network (because there is an issue on kovan) but with no luck… i’ve tested also the method present on youtube when i get an error with the ABI code but with no luck:

I have 4 files generated by token wizard:

001_SafeMathLibExt (can be verified)
003_CrowdsaleTokenExt (cannot be verified)
005_MintedTokenCappedCrowdsaleExt (cannot be verified)
007_ReservedTokensFinalizeAgent (cannot be verified)

On 003_CrowdsaleTokenExt there isn’t neither an ABI in the txt file but if i try to verify it with no ABI i get a missing construct error

Another related question. I’ve created a test token. To test it the verification is a mandatory step? Or theorically i can sell the token without the verification?

Thank you

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Ropsten

### If you were able to create it, what is the URL of your crowdsale?

This is the crowdsale address 0xd56edbf6d4117bbf8a539cdb43222bb169137d56

### Do you have screenshots showing the problem?

Just the error that the ABI is wrong

### Do you see errors in the dev console? If yes, please include a screenshot

no errors
---

**Comment by vbaranov** [comment]
@afxgroup see answers here https://forum.poa.network/t/verify-the-contracts-code/1043/2
