### ISSUE TITLE
Repeatedly problem with verifying contract : Constructor argument does not match

### ISSUE THREAD

**Issue by drdonjuan** [poanetwork/token-wizard#804]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Main network

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0xa703ae15669AdEd2E89D598F7D63db9ecc413901&networkID=1

### Do you have screenshots showing the problem?

![error](https://user-images.githubusercontent.com/38373159/39084768-1484eeea-458b-11e8-9517-181965eb5937.jpg)

---

I'm trying to verify my CrowdsaleTokenExt contract. It gives me an error as below
Sorry! The Compiled Contract ByteCode for 'CrowdsaleTokenExt' does NOT match the Contract Creation Code for Address 0xCA049Af7e60cAf1cbf41c0d14B4Dd648C3aF24Dc.

If you want to advise me to get the construction arguments from the hash Tx , 
Contract was created during TxHash# 0x0cb1b8efe4f0c90ce2f83c70ea687de59233b34599833313eb176798da8739bd
Just to tell you that I've tried and copied everything after "0029" and put it in constructor argument and found the same problem.

What I've noticed is as below;

In the above screen shot I've attached there is a box showing
 "ByteCode on the Blockchain (what we are looking for):" 
and below there is another box showing
 " Your Compiled Bytecode + Constructor Argument if any (what you provided):
What I've noticed is, 

In   "ByteCode on the Blockchain (what we are looking for):"   box, just before the constructor code the Byte code is little different which is "55e87dcd56002900000000000"
AND
In  " Your Compiled Bytecode + Constructor Argument if any (what you provided):  box, just before the constructor code the Byte code is as this "947f7e0b8d002900000" 

Check it please, which they require is different from what I provided. I'm sure that mistake is here which I can't understand.

**Comment by vbaranov** [comment]
@drdonjuan you are using another verification link. Try `https://etherscan.io/verifyContract`

**Comment by vbaranov** [comment]
Please reopen this issue if you will still have problems with verification

**Comment by drdonjuan** [comment]
Thanks for your help and it worked for Minted token and crowd sale contract. Bundle of thanks. However I have another small issue/.
For, Null finalize agent contract name: NullFinalizeAgentExt
I've received an error " Error! The Library Name (SafeMathLibExt) and Address (E2c9B0fd4302e7BC65CE5E68A0032FCED0950E92) was provided but not used in the contract"
In steve video, he mentioned except "SafeMathLibExt" , we have to provide library details in all other contracts. Kindly help on this. Check the screen shot of error mentioned below.

Problem 2: After completion of 3rd step while creating the token, I have downloaded all the files and there are 2 files which were missing in the downloaded Zip file. These are related to "Pricing Strategy"
However, these files where there in step 4 downloadable page. So I just copy pasted the all the ABI and other codes and saved in files. The problem is, I've the contract but unfortunately I cant find the contract address, contract name and constructor argument in the copied codes. Kindly check the attached files which I copy pasted.


[PRICING STRATEGY CONTRACT ABI.txt](https://github.com/poanetwork/token-wizard/files/1941092/PRICING.STRATEGY.CONTRACT.ABI.txt)
[PRICING STRATEGY CONTRACT SOURCE CODE.txt](https://github.com/poanetwork/token-wizard/files/1941093/PRICING.STRATEGY.CONTRACT.SOURCE.CODE.txt)



![image](https://user-images.githubusercontent.com/38373159/39168977-fc321aac-47a6-11e8-8110-a660bb425ee9.png)

**Comment by vbaranov** [comment]
@drdonjuan 
>For, Null finalize agent contract name: NullFinalizeAgentExt
I've received an error " Error! The Library Name (SafeMathLibExt) and Address 

`NullFinalizeAgent` doesn't utilize SafeMathLibExt. You can see it in helpful video instructions for verification from @hashguide.

>Problem 2: After completion of 3rd step while creating the token, I have downloaded all the files and there are 2 files which were missing in the downloaded Zip file. These are related to "Pricing Strategy"
However, these files where there in step 4 downloadable page

This was a bug. We already fixed it. This is your verified pricing strategy contract: https://etherscan.io/address/0xe7bca81d8c19eabaeae2f5313e8e76298c49b0ab#code
