### ISSUE TITLE
Contract Finalized but No reserved token

### ISSUE THREAD

**Issue by Bitacium** [poanetwork/token-wizard#806]
I finalized the contract but my reserved token is not showing up in my ERC20 address. Whats going on and why do we have to go through all these issues its frustrating. must the contract be verified before you finalize? could this be the reason im not seeing the reserved token in my address? I did not send any transaction through as the goal is to transfer all token to the reserved account.

---

**Comment by vbaranov** [comment]
@Bitacium 
>must the contract be verified before you finalize?

no

- What is the address of your crowdsale? 
- Which network?
- Didn't you forget to press "+" button when you configured reserved tokens?

**Comment by Bitacium** [comment]
my crowdsale address
0x07179606326825dBC7B51D28D55552Fc617C6b94

Mainnet

I didnt press the + sign

**Comment by Bitacium** [comment]
I forgot to press the + sign

**Comment by Bitacium** [comment]
Is there a solution?
