### ISSUE TITLE
Local Installation Issues and missing arguments in CrowdsaleTokenExt

### ISSUE THREAD

**Issue by mbensi** [poanetwork/token-wizard#807]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Kovan

### If you were able to create it, what is the URL of your crowdsale?
Running on localhost.

### Do you have screenshots showing the problem?
Yes.

### Do you see errors in the dev console? If yes, please include a screenshot
![error](https://user-images.githubusercontent.com/1534196/39100954-afb1b3dc-4692-11e8-818a-3a028c931ab7.PNG)

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.
NA

When I select the Contract Address after Choose Contract, and click Continue, I get to the page: http://localhost:3000/manage/0x2de06B7CC4a4675Fc29eEE292bf965e55EE187f3
showing the error in the picture.

Note: newbie here, bare with me, please.

After installing locally (based on https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-How-to-run), and changing the config.js pointing to Kovan and my previously created online Crowdsale address, I could not get the contract to show (always errors loading it and getting HTML instead of JSON). I set a breakpoint and saw that the contracts names were null.

Then I noticed: in the public/contracts folder there was only  SafeMathLibExt_flat (abi bin and sol).
To fix the registry with Ganache (https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Local-Dev-Version#prerequisites) I copied the files Registry_flat (abi bin and sol) from the token-wizard-test-automation folder and  

However I still cannot edit the crowdsale as mentioned in the error (as the sale contracts are still missing locally).

So I tried to verify the contracts that I've donwloaded from the previously created online Crowdsale, on https://kovan.etherscan.io/verifycontract, and after verifying SafeMathLibExt no problem, when I tried to verify CrowdsaleTokenExt (previously obtained from https://wizard.poa.network/) I noticed that it is missing the arguments section altogether.
And obviusly the verification fails.

So I was hoping to create the abi and bin files by verifying them online but I can't.

Am I missing something obvious?
Help appreciated, 
Thanks!

**Comment by vbaranov** [comment]
@mbensi 

>So I tried to verify the contracts that I've donwloaded from the previously created online Crowdsale, on https://kovan.etherscan.io/verifycontract, and after verifying SafeMathLibExt no problem, when I tried to verify CrowdsaleTokenExt (previously obtained from https://wizard.poa.network/) I noticed that it is missing the arguments section altogether.
And obviusly the verification fails.

Contracts are not verified in Kovan. Related issues: https://github.com/poanetwork/token-wizard/issues/679, https://github.com/poanetwork/token-wizard/issues/716, https://github.com/poanetwork/token-wizard/issues/802. But there are no problems with verification in any other networks. We applied the fix for missing arguments for CrowdsaleTokenExt contract: https://github.com/poanetwork/token-wizard/pull/808.

As about local deployment, what is your OS?

**Comment by mbensi** [comment]
Thanks for the reply.
My OS is Windows 10; I also have Ubuntu installed as a Windows App, from which I get bash (as most documentation is Linux based, it makes it easier to follow).

I tried to verify on the Novak network based on this video: https://www.youtube.com/watch?v=IDFFptAi8-4

But if I understand correctly now, I can verify the contracts on the main etherscan.io, and so generate the missing files that I can use later in the Kovan test network?

About the missing arguments, does that mean that when #808 is closed I can pull the latest code and solve the issue (getting the missing FlatPricingExt and the CrowdSaleExt with arguments)?

Thanks much!

**Comment by vbaranov** [comment]
We are working on Windows local deployment fixes right now in the frames of this issue https://github.com/poanetwork/token-wizard/issues/780.

>But if I understand correctly now, I can verify the contracts on the main etherscan.io, and so generate the missing files that I can use later in the Kovan test network?

The problem is that verification of crowdsale contracts from Token Wizard in Kovan doesn't work. You can use Rinkeby, Ropsten for verification testing. Verification should work there correctly, as in Mainnet too.

>About the missing arguments, does that mean that when #808 is closed I can pull the latest code and solve the issue (getting the missing FlatPricingExt and the CrowdSaleExt with arguments)?

Right, you will get the full set of arguments for new crowdsale creation

**Comment by mbensi** [comment]
Thanks again, I appreciate your hard work!

**Comment by mbensi** [comment]
Wow, you rock!
Latest code works like a charm on Windows 10!
Thanks much, really impressed by your work.
