### ISSUE TITLE
(Feature) enable/disable whitelists for any tier

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#812]
**Problem**: disabling/enabling of whitelist is a property of the whole crowdsale in the current implementation

**Solution**: After migration to Auth_os framework, we should implement disabling/enabling of whitelists as a property of tier (not as a property of the whole crowdsale). So, users will be able to have whitelisted and non-whitelisted tiers in one crowdsale.

**Comment by fernandomg** [comment]
Continuing with this approach, shouldn't we implement `minCap` in a per-tier basis?

Or it will be global to all tiers that have whitelist disabled?

**Comment by vbaranov** [comment]
Yes, it is a good idea. But it is not implemented in Auth_os application yet. We could implement global minCap in a per-tier basis with the next version of `CrowdsaleConsole` application.
