### ISSUE TITLE
(Tests) Add tests for Stores

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#818]
Refer to https://github.com/poanetwork/token-wizard/issues/499#issuecomment-383696851

**Comment by vbaranov** [comment]
List of stores:

* [ ] ContractStore
* [x] CrowdsalePageStore
* [ ] CrowdsaleStore
* [ ] DeploymentStore
* [x] GasPriceStore
* [ ] GeneralStore
* [ ] ReservedTokenStore
* [ ] StatsStore
* [ ] StepTwoValidationStore
* [x] TierStore
* [ ] TokenStore
* [ ] Web3Store
