### ISSUE TITLE
(Tests) Add tests for Common components

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#819]
Refer to https://github.com/poanetwork/token-wizard/issues/499#issuecomment-383696851

**Comment by vbaranov** [comment]
**List of common components** (
* [x] - covered with unit tests,
* [ ] - not covered with unit tests
)

* [x] AddressInput
* [x] BigNumberInput
* [ ] CrowdsaleEndTime
* [ ] CrowdsaleRate
* [ ] CrowdsaleList
* [ ] CrowdsaleStartTime
* [ ] DisplayField
* [ ] DisplayTextArea
* [ ] DutchAuctionBlock
* [ ] Error
* [ ] InputField
* [ ] InputField2
* [ ] Loader
* [ ] MinCap
* [ ] ModalContainer
* [ ] NoWeb3
* [x] NumericInput
* [ ] PreventRefresh
* [x] RadioInputField
* [x] ReservedtokensInputBlock
* [x] ReservedTokensItem
* [ ] StepNavigation
* [ ] Supply
* [ ] TierBlock
* [x] TokenDecimals
* [x] TokenName
* [x] TokenSupply
* [x] TokenTicker
* [ ] TxProgressStatus
* [ ] WhenFieldChanges
* [ ] WhitelistInputBlock
* [ ] WhitelistItem
