### ISSUE TITLE
COntract not verifying

### ISSUE THREAD

**Issue by Bitacium** [poanetwork/token-wizard#823]
Hello Igor,

My crowdsale is over on the mainnet and i have been trying to verify the contracts and its not working. Only the SafeMathLib  was verified, the rest did not, each time i try iget this message

Note: Contract was created during Txn# [0x10c720e4b0d7ed5f52d07be6cde79701569478f190361b5331858eb1dcf2201b]
Result: Does not match the input creation bytecode found at this address

Sorry! The Compiled Contract ByteCode for 'CrowdsaleTokenExt' does NOT match the Contract Creation Code for [0x50c675E4E885a7343dab56b434AC79a1752a203D].

Contract name(s) found: 'CrowdsaleTokenExt' , 'ERC20' , 'ERC20Basic' , 'MintableTokenExt' , 'Ownable' , 'ReleasableToken' , 'SafeMath' , 'SafeMathLibExt' , 'StandardToken' , 'UpgradeAgent' , 'UpgradeableToken'
Unable to Verify Contract source code.
Tip: The Contract appears to have been compiled with Optimization=NO, but you have set Optimization=Yes for the source code verification.

This is my Crowdsale Contract Address
0x5FE01ae56b74b8a2802b7eBa754839F289220734

**Comment by vbaranov** [comment]
Please use updated guide for verification https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts. You don't need to put a colon before `SafeMethLibExt` due to changes in Etherscan verification process.

>On the page generated during contract creation i see pragma solidity ^0.4.8; but on the downloaded file i see Compiler Version: 0.4.11

You should use 0.4.11 as indicated in the guide for every smart-contract.

**Comment by Bitacium** [comment]
Will follow your instruction and try it again. will post the result here
