### ISSUE TITLE
Transferring tokens from POA network token wizard to metamask

### ISSUE THREAD

**Issue by drdonjuan** [poanetwork/token-wizard#827]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Main network

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/invest?addr=0xa703ae15669AdEd2E89D598F7D63db9ecc413901&networkID=1

### Do you see errors in the dev console? If yes, please include a screenshot

No problem.

QUESTION: How can I transfer the tokens from POA network wizard to meta mask? I've started my crowd sale and public wants to invest, therefore I want to send them tokens rather than providing them the link to invest on.

**Comment by vbaranov** [comment]
I've just created FAQ section. You can find there answers to your questions:

https://github.com/poanetwork/token-wizard/wiki/FAQ#4-what-is-the-total-supply-of-token-created-by-token-wizard

https://github.com/poanetwork/token-wizard/wiki/FAQ#5-i-dont-want-to-create-crowdsale-but-i-need-to-create-erc20-token-could-i-do-it-with-token-wizard

**Comment by drdonjuan** [comment]
Dear Victor,


Thanks for the useful link.

However, the info in the link does not answer my query in the following link ,


https://github.com/poanetwork/token-wizard/issues/836


________________________________

**Comment by drdonjuan** [comment]
Please ignore my previous reply. That was supposed to be for #836

**Comment by miordache93** [comment]
Hello,

Recently I've transferred from Binance all my POA holdings to Trust Wallet, then I've tried to withdraw them to my personal bank account or to convert them but I was unable to find this crypto in the trade panel. After this I've tried to transfer again to metamask. The transactions appears to be successfully but I don't see any POA in Metamask..

Any help here? :/
