### ISSUE TITLE
(Wizard2.0-Bug) Unable to buy fractional amount

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#834]
Steps for reproduce:
1. Open wizard https://5ae0d38fc9659230d752d6bc--architect-coin-64174.netlify.com/
2. Create crowdsale with valid parameters.
3. Open invest page and buy amount 0.1

Expected result:
 - user should be able to buy fractional amount if decimals != 0

Actual result:
- user is not able to buy fractional amount
- transaction is reverted

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?
https://5ae0d38fc9659230d752d6bc--architect-coin-64174.netlify.com/invest?exec-id=0xa27e8acd6084a5d147f5966b0a5c1b895948a4e16aa37d0e7919403e988f09dd&networkID=3
### Do you have screenshots showing the problem?
Decimals = 6
ExecID: 0x11492f99fb5b4cb78a29a4aec577fa2d780ff521e4d03850183db6b88fd520e2
TX: https://ropsten.etherscan.io/tx/0x6f0f9d7b17389d22e503dd3c4ef0f186f644e5af6fb89f43a91a71757ef65b5f

Decimals = 18
ExecID: 0xa27e8acd6084a5d147f5966b0a5c1b895948a4e16aa37d0e7919403e988f09dd
TX: https://ropsten.etherscan.io/tx/0xff9f4a38dcab56b5829ed5ce71dd46850b3239cc722d9b1976ed07dec71b5c7d

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment]
@dennis00010011b I have created test 1-tier crowdsale without white list and global min cap and successfully bought 0.1 tokens: https://5ae0d38fc9659230d752d6bc--architect-coin-64174.netlify.com/crowdsale?exec-id=0xc349f005434c9050cc384da6ef7e152cf340a2ccbbe078f1e32294f114cda8fe&networkID=3. Could you specify how could I repeat the problem?

**Comment by fernandomg** [comment]
@dennis00010011b @vbaranov I managed to reproduce the issue.

_I'm checking if there's a error with the math around `supply/rate` values, at the moment of crowdsale creation_

## Crowdsale with errors

https://5ae0d38fc9659230d752d6bc--architect-coin-64174.netlify.com/crowdsale/?exec-id=0x4ef0e9a288348a63ce7bc752941e984ebfa6f40e02ee8930fbf45644d3fb9df1&networkID=3

|rate|supply|decimals|reservedTokens|whitelist|
|-:|-:|-:|:-:|:-:|
|1000000|130|2|yes|yes|

I tried to buy:
- `0.1`: https://ropsten.etherscan.io/tx/0xb4cf2c105ddc25a17e35dbacc6a9635287dfbbc532c252a4b0bbff6993ca3208
- `10.9`: https://ropsten.etherscan.io/tx/0x67e36f0df4a463ad68e31715f42d0cc7bb658f4c7ed5e640449e32dd4c4c60df
- `1`: https://ropsten.etherscan.io/tx/0x9d63c44481055ffc793c5da7bf3cc79dc31d4d31ccc17339eff6d165a728b12c
... and so on. All tx failed.

You can see there's an StorageException event triggered: https://ropsten.etherscan.io/tx/0xb4cf2c105ddc25a17e35dbacc6a9635287dfbbc532c252a4b0bbff6993ca3208#eventlog

---
## Successful Crowdsale
https://5ae0d38fc9659230d752d6bc--architect-coin-64174.netlify.com/crowdsale/?exec-id=0xd0e4fd328bd69941bee643c6fcc8bd0de8baa4e369ea01df05a25b5cfbc5bddc&networkID=3

In the other hand, I created a crowdsale similar to the one that Victor created, and was able to buy `0.1` without problem.

|rate|supply|decimals|reservedTokens|whitelist|
|-:|-:|-:|:-:|:-:|
|1000|1000000|18|no|no|

- `0.1`: https://ropsten.etherscan.io/tx/0xba95813743c4532c2486ed4aa733b1e497b19bc7e003c581d4f508346cd05fbe

**Comment by vbaranov** [comment]
@fernandomg the errors in your case can be related to enabled whitelist. The related issue: https://github.com/poanetwork/token-wizard/issues/835

**Comment by fernandomg** [comment]
Can confirm.

Bought `10.1` and then tried to buy `0.1` and it failed.

It looks like it's not taking into account `minCap` goal:

> _Minimum amount of tokens to buy. **Not the minimal amount for every transaction**: if minCap is 1 and a user already has 1 token from a previous transaction, they can buy any amount they want._

**Comment by dennis00010011b** [comment]
Issue isn't reproducible if whitelist enabled but mincap = 0
