### ISSUE TITLE
Token contract registration on main network is having a bug

### ISSUE THREAD

**Issue by drdonjuan** [poanetwork/token-wizard#836]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Main network

I'm trying to register a Token on main network. I'm using normal gwi. The problem is, meta mask asks for first time only for fees. There are several contracts to be paid but it does not proceed further and does not ask for fees anymore , so the contract registration is stuck for whole day. I tried in both. Safe and normal gwi.

Is there any bug ?

**Comment by vbaranov** [comment]
@drdonjuan 
I'm not sure I understand your problem at all.
Do you have a screenshot of your problem?
Do you see errors in Chrome Dev Console?
How many transactions did you sign successfully?
What is the address did you use to confirm transactions?

**Comment by drdonjuan** [comment]
please see the screen shot. It is stuck here. I do not receive any pop up from meta mask to proceed with the contract transactions.


![image](https://user-images.githubusercontent.com/38373159/39359778-723e15e8-4a2c-11e8-9dea-c4e75538e24f.png)

**Comment by vbaranov** [comment]
If there are errors in Google Chrome Dev Console, please attach log to the issue:

>To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

>If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

In other case (you don't see any errors) just refresh the page, Metamask popup should appear.

**Comment by drdonjuan** [comment]
Have a look please. There is a screen shot and a text file. There is only one option to save the console which is ".txt"

![image](https://user-images.githubusercontent.com/38373159/39365485-49b1ed0a-4a42-11e8-8d7d-5b3213132af6.png)
[wizard.oracles.org-1524836285178.log](https://github.com/poanetwork/token-wizard/files/1955319/wizard.oracles.org-1524836285178.log)

**Comment by vbaranov** [comment]
It looks like the problem with MetaMask. Are you logged in MetaMask? If yes, try to logout/login and refresh the page with step 4.

**Comment by drdonjuan** [comment]
Hi Victor, actually I did it already twice but it does not resolve.
Your guess is right. The problem is with meta mask because I'm trying to transfer funds from Meta mask to IDEX.market but it is not going through. Metamask pops up for asking permission but the transaction does not process. Similarly, for the POA wizard, only one time metamask pops up to take permission to submit and after that no response.
May I have your email address? I would like to give you my teamviewer address privately so that you connect to me, if you are not bothered?? Thanks.

**Comment by vbaranov** [comment]
MetaMask is beyond of our support. Try to logout/login in MetaMask and configure your crowdsale again.

**Comment by drdonjuan** [comment]
Hi Victor, I have switched my Metamask from Chrome to Firefox and it works fine now.
I successfully paid for all the contracts through meta mask.
I'm at 4th page
Check the screen shot. Now, the problem is , I cannot download the file of the whole contract. I tried several times by clicking and even I refrshed it but that download button does not work. Seems like disabled.
Is there any way we can download all these files?
![image](https://user-images.githubusercontent.com/38373159/39384933-7f0cf7be-4a7f-11e8-95ec-9b24f56065c2.png)

**Comment by drdonjuan** [comment]
Dear Victor,

I'm sure there is a bug in POA wizard. I'm unable to download the contracts file. I tried in google chrome and in firefox as well.

It used to work fine a week ago because I successfully registered one contract previously last week.

**Comment by vbaranov** [comment]
Please open an issue regarding files download, attaching logs from developer console. Also, I recommend you to set up your crowdsale in any testnet first: Sokol, Kovan, Rinkeby, Ropsten before live crowdsale in Mainnet to be sure, that it works, as you expect. Also, source code of crowdsale contracts in testnet will be absolutely the same, that in Mainnet

**Comment by vbaranov** [comment]
Please describe all parameters of your crowdsale to repeat this error.

**Comment by drdonjuan** [comment]
![image](https://user-images.githubusercontent.com/38373159/39461020-103fc4b4-4d19-11e8-85c1-8199ab55693f.png)
[wizard.oracles.org-1525117561240.log](https://github.com/poanetwork/token-wizard/files/1962978/wizard.oracles.org-1525117561240.log)

**Comment by drdonjuan** [comment]
Dear Victor,
I've resolved all the issues.
The key to resolving any console problem related to Metamask is to uninstall it and reinstall it. Better to check on  test net as you advised and then go to main network. Everything went fine after that.
Kindly close the ticket and thank you so much.
