### ISSUE TITLE
manual disbursement of token

### ISSUE THREAD

**Issue by Bitacium** [poanetwork/token-wizard#841]
How do you disburse token manually without using the crowdsale system. Manually selling it to contributor who pays into multisig wallet. Do we put all the tokens in reserve and disburse from there?

**Comment by vbaranov** [comment]
https://github.com/poanetwork/token-wizard/wiki/FAQ#5-i-dont-want-to-create-crowdsale-but-i-need-to-create-erc20-token-could-i-do-it-with-token-wizard
