### ISSUE TITLE
Cannot mint tokens

### ISSUE THREAD

**Issue by ksystemsio** [poanetwork/token-wizard#843]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Your answer*

### If you were able to create it, what is the URL of your crowdsale?

*Your answer*

### Do you have screenshots showing the problem?

*Your answer*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@ksystemsio it is unclear what is your problem. Use gitter channel for such questions: https://gitter.im/poanetwork/ico-wizard.

**Comment by ksystemsio** [comment]
Sorry, did not complete the form...

I solved it by adding my wallet address (creator) to the mintAgents, I was then able to mint tokens to my address. I am still not able to transfer tokens from a wallet to another, but I guess this is due to the fact that the crowdsale contract in not finalized yet, am I correct?

**Comment by vbaranov** [comment]
Yes, this is correct
