### ISSUE TITLE
How to embed crowdsale page

### ISSUE THREAD

**Issue by russlex** [poanetwork/token-wizard#852]
Hi Everyone!
I have a few questions:

1. It is possible to embed a crowdsale page with a progress bar of raised funds on any website? How to do this?
2. How to set soft cap of crowdsale?
3. Whats mean function " MAX_INVESTMENTS_BEFORE_MULTISIG_CHANGE"
4. It is possible to change the multisig address  to which funds will be sent?

Thank you in advance for your reply!

**Comment by vbaranov** [comment]
Hi,

>1. It is possible to embed a crowdsale page with a progress bar of raised funds on any website? How to do this?

Use iframe.

> 2. How to set soft cap of crowdsale?

Token Wizard's crowdsale soft cap is 0. Strategy with refund and soft cap is not implemented yet in Token Wizard but it is in our roadmap https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Roadmap

> 3. Whats mean function " MAX_INVESTMENTS_BEFORE_MULTISIG_CHANGE"

MAX_INVESTMENTS_BEFORE_MULTISIG_CHANGE = 5 - the threshold value to be able to change wallet address, where funds will be collected. It gives the owner ability to change wallet address in the emergency if the number of investors not so big.

> 4. It is possible to change the multisig address to which funds will be sent?

Yes. Owner of crowdsale smart-contract can change wallet address where funds will be collected with method `setMultisig`, if the number of investors is less or equal to MAX_INVESTMENTS_BEFORE_MULTISIG_CHANGE
