### ISSUE TITLE
(DutchCrowdsale) Owner's balance equals minRate after creation of crowdsale

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#857]
Wizard URL: https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/
Steps:
1. Create Dutch crowdsale with parameters: decimals=, supply= (Step 2), minCap=0, 
1 tier:  minRate=200, maxRate=400,Supply=800 
2. Look to owner's balance

  Expected result: 
 - owners balance should be 0 (since no tokens were sold)

Actual result:
 - owner's balance equals minRate

ExecID: 0xa773fb9c98609db7b8bba35171b6cd2a0a6be9404a5eebd3fea7cf131d0b894c

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/invest?exec-id=0xa773fb9c98609db7b8bba35171b6cd2a0a6be9404a5eebd3fea7cf131d0b894c&networkID=3*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-07 at 19 53 21" src="https://user-images.githubusercontent.com/14067096/39735960-c57e561a-5232-11e8-8776-b76e917d1e0b.png">
<img width="1440" alt="screen shot 2018-05-07 at 20 18 31" src="https://user-images.githubusercontent.com/14067096/39736262-11a46a60-5234-11e8-86ef-b8ececafd01f.png">
<img width="1440" alt="screen shot 2018-05-07 at 20 19 10" src="https://user-images.githubusercontent.com/14067096/39736263-1320f1f6-5234-11e8-9aa0-7e491ecf4d80.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@dennis00010011b token is allocated in Dutch Auction strategy. For example, if tokens' supply = 1000 and crowdsale supply = 800. Owner's balance = tokens supply - crowdsale supply = 200. If crowdsale supply is zero, then owner owns all tokens.

**Comment by vbaranov** [comment]
@dennis00010011b do you have any doubts on this?

**Comment by dennis00010011b** [comment]
@vbaranov No, it works as expected.
