### ISSUE TITLE
(DutchCrowdsale) Extra tokens are transfered to owner's account

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#860]
Wizard URL: https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/
I  faced with this issue  only once , still can't reproduce it .

Steps:
1. Create crowdsale: decimals=18, supply=1000(Step2), mincap=100, 1 tier: duration=13min, minRate=10000, maxRate=20000
2. Open invest page Invest page and buy 1 token as a owner.
3. Observe token's balance

 Expected result:
 - balance should be 1 token

Actual result:
 - balance is 500.529956470088211919

Tx: https://ropsten.etherscan.io/tx/0x56330d30ac99c9f9dc1bb110e4cf167ef6b3148a8d860a2f560c7feb7a5a747f

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/invest?exec-id=0x6495fa152ee38d90a28ccd3a2bc00040ec45577fea5cb6c99a97c07648a399ac&networkID=3*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-07 at 23 36 26" src="https://user-images.githubusercontent.com/14067096/39741946-9ad7b5a0-5250-11e8-9985-7ed250005a43.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
I believe it is related to https://github.com/poanetwork/token-wizard/issues/857#issuecomment-387333682: owner's balance = tokens'supply - crowdsale suply

**Comment by dennis00010011b** [comment]
It is not issue ,works as expected
