### ISSUE TITLE
(Bug) wrong amount of tokens in success alert if a user tries to buy more than hard cap of a tier

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#872]
**Problem**: the same as #847, but when a user tries to buy more than a hard cap of a tier

**Solution**: check remaining tokens to buy in a tier and amount, that user is trying to buy and show the lowest value from those in the message.

**Comment by dennis00010011b** [comment]
I reproduced it.
Test URL: localhost, branch 2.0, latest commit https://github.com/poanetwork/token-wizard/commit/6500c2733c2d02ad96ebaba73694f6da99704072
Exec ID: 0x4bf24291dc0fec5122dcc11687e17af38cdd575c7fbdef8d22ece9639c06f922
Network: Ropsten
<img width="1440" alt="screen shot 2018-05-19 at 16 04 55" src="https://user-images.githubusercontent.com/14067096/40273927-2f617634-5b7f-11e8-9dbd-c388ff752c87.png">
<img width="1440" alt="screen shot 2018-05-19 at 16 05 08" src="https://user-images.githubusercontent.com/14067096/40273931-31e5ef48-5b7f-11e8-9274-67e3775b1602.png">



 Crowdsale data:
```
{ "name": "simpleManual.json",
  "ticker": "Mcap",
  "decimals": 18,
  "reservedTokens":[ ],
  "walletAddress":"0x0e036E74F31aDDb9e0ADcB80dEA9Ed1E187DFe50",
  "gasprice": 400,
  "mincap": 10,
  "whitelisting":false,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "",
      "startTime": "",
      "endDate":"",
      "endTime":"",
      "rate":1000,
      "supply": 100,
      "whitelist":[]
    }]}
```
