### ISSUE TITLE
(Bug) Multitier: Incorrect initialization of second tier start/end time

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#873]
Tested with  https://github.com/poanetwork/token-wizard , branch 2.0, 
commit 36a6446136ece5e5a2f8a8ada1e9dbe7089f517b
Steps:
1. Create 2 tiers crowdsale; break time should be between tiers
2. Open manage page and compare tier's schedule with given

Expected result:
 - tiers schedule should be as it was given by user

Actual result:
 - no break time between tiers

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*localhost*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-11 at 10 39 10" src="https://user-images.githubusercontent.com/14067096/39938691-9e1c482e-5508-11e8-8089-464fb83ce7b2.png">
<img width="1440" alt="screen shot 2018-05-11 at 10 39 16" src="https://user-images.githubusercontent.com/14067096/39938708-ab1df0c2-5508-11e8-8a6b-cabebecdb58c.png">
<img width="1440" alt="screen shot 2018-05-11 at 10 39 44" src="https://user-images.githubusercontent.com/14067096/39938786-ea73681a-5508-11e8-92f8-f8e4f0ec6d14.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
@dennis00010011b there is no way to create breaks between tiers after migration to auth_os. The next tier should start immediately after the previous tier was finished. Regarding this issue, I think, we could add an additional ui validation that end time of the previous tier should be the same as the start time of the next tier. And also it would be nice if these dates would be joined: if one date is changed, the other date should change automatically.
