### ISSUE TITLE
(Bug) Owner can't open manage page

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#876]
Tested with https://github.com/poanetwork/token-wizard , branch 2.0,
commit 36a6446

Steps:
1.Create 2 tiers crowdsale: allow modify, 1 whitelisted address for each tier
2. Open manage page as a owner and observe

Expected result:
 - owner should be allowed to see crowdsale parameters on manage page

 Actual result : 
 - no crowdsale parameters presents for owner
 - manage page has regular view for others accounts

Exec ID 0xde86e42acb80985cc6dbb47e231825bb070d140ccce4a27363db55ffb398e430

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

Exec ID 0xde86e42acb80985cc6dbb47e231825bb070d140ccce4a27363db55ffb398e430

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-11 at 12 54 31" src="https://user-images.githubusercontent.com/14067096/39944184-8c1dc064-551a-11e8-9bda-f9e629f801bc.png">

<img width="1440" alt="screen shot 2018-05-11 at 12 57 56" src="https://user-images.githubusercontent.com/14067096/39944321-1620edc2-551b-11e8-8965-f39c0c68527a.png">

### Do you see errors in the dev console? If yes, please include a screenshot

[logOwner.log](https://github.com/poanetwork/token-wizard/files/1996683/logOwner.log)

---

**Comment by dennis00010011b** [comment]
Also reproducible with parameters:
{
  "name": "TestSuite2.json",
  "ticker": "test2",
  "decimals": 18,
  "reservedTokens":[
    {
      "address" :"0xecDFec71AbCD5a612eAf9169B19E907eAA2717d9",
      "dimension": "percentage",
      "value": 250
    },
    {
      "address" :  "0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
      "dimension": "tokens",
      "value":100000000
    }

  ],
  "walletAddress":"0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
  "gasprice": 1,
  "mincap": 1,
  "whitelisting":true,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "startDate": "01/01/2030",
      "startTime": "01:11",
      "endDate":"01/01/2031",
      "endTime":"02:22",
      "rate":20000,
      "supply": 250,
      "whitelist":[
        {
          "address": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
          "min": 50,
          "max": 150
        }
      ]
    }]
}

**Comment by vbaranov** [comment]
@dennis00010011b I am able to see management page for exec-id 0xde86e42acb80985cc6dbb47e231825bb070d140ccce4a27363db55ffb398e430 without errors:
![screencapture-localhost-3000-manage-0xde86e42acb80985cc6dbb47e231825bb070d140ccce4a27363db55ffb398e430-2018-05-14-12_15_55](https://user-images.githubusercontent.com/4341812/39988681-aeedb470-5770-11e8-8c27-729df3d865c8.png)

Could you try it once more from 2.0 branch?

Also, I've created another crowdsale with the similar parameters (exec-id: 0xd8c48a00822ea00f427e0a185f19f8a44729dfb50734804cc4c8f1dc18851299). And I have no issues with it too.

**Comment by dennis00010011b** [comment]
@vbaranov I can't reproduce it now with branch 2.0
