### ISSUE TITLE
Contract verification troubleshoot

### ISSUE THREAD

**Issue by typico46** [poanetwork/token-wizard#877]
![screen](https://user-images.githubusercontent.com/39285062/40030369-7f8911be-57ea-11e8-8be1-255fd961b06d.PNG)
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

Mainnet

### If you were able to create it, what is the URL of your crowdsale?

https://wizard.oracles.org/crowdsale?addr=0x0506C5aF0a76afeA100aB3E48eBcCFD5DD9c7Aa5&networkID=1

### Do you have screenshots showing the problem?

---
I got the some issue as is desribed in this video https://www.youtube.com/watch?v=f7Gz648ivhQ but the solition 
with copying bydecode from etherscan page that transaction doesnt work. Please help
![vystrizek](https://user-images.githubusercontent.com/39285062/40030321-3fc8bfc0-57ea-11e8-8d21-0fc4564fdb62.PNG)

**Comment by vbaranov** [comment]
@typico46 please check carefully verification page with the screenshot from [verification wiki](https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts). Something should be mismatched. If you can confirm that everything is filled as in the screenshot, and the issue still exists, let us know.
