### ISSUE TITLE
(Bug) Wizard switches from Dutch to Minted if network changed in metamask

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#883]
Test URL: https://5af9cf4ae39e7c72cbae16bd--architect-coin-64174.netlify.com/
Also reproducible with local deployment

Steps to reproduce:
1. Open test URL
2. Select Dutch Auction
3. Proceed to Step2
4. Change network in Metamask

Expected result:
 - wizard should stay on Dutch Auction strategy

Actual  result:
 - wizard switches from Dutch to Minted strategy

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
*from Kovan to Ropsten but issue actual for any network*
### If you were able to create it, what is the URL of your crowdsale?
*n/a*
### Do you have screenshots showing the problem?

*https://drive.google.com/open?id=1HXEMpc5vmEpe9JPGUA0ALEMCE7Xpq4Nc*

### Do you see errors in the dev console? If yes, please include a screenshot
No

---

**Comment by vbaranov** [comment]
Relates to #828

**Comment by fernandomg** [comment]
This issue was solved as part of the: https://github.com/poanetwork/token-wizard/pull/1104
