### ISSUE TITLE
(Bug) Dutch: Mincap isn't presented either on Publish page and in  file 'DutchCrowdsale_data.txt'

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#885]
Problem: since DutchAuction crowdsale has the minCap then minCap value should be shown on Publish page and in file 'DutchCrowdsale_data.txt'

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*
### If you were able to create it, what is the URL of your crowdsale?

https://5afc64f60733d568662edfc7--architect-coin-64174.netlify.com/invest?exec-id=0x9f78aac7a67474c7ed22aab1e8e93917c559e97426c496213a0bdc9785fb1d29&networkID=3*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-16 at 21 40 44" src="https://user-images.githubusercontent.com/14067096/40157176-8c1cdbc2-5952-11e8-8086-396940cb0bff.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by vbaranov** [comment]
Global min cap was added to the summary file.
If crowdsale is whitelisted, global min cap is equal to 0. And it is not displayed in the summary file and publish page. Also, whitelist data was added to the file (see #886)
