### ISSUE TITLE
reserved address

### ISSUE THREAD

**Issue by russlex** [poanetwork/token-wizard#890]
Hi,
It is possible to check the reserved addresses of the reserved token after the contract has been completed during ICO ?

**Comment by vbaranov** [comment]
Yes, you can. You could do it with MyEtherWallet, for example. Connect to your token contract (address and ABI are in your summary files) from publish page.
There are some methods:
1. `isAddressReserved(address)` - checks if address is reserved. It returns `true` or `false`
`areTokensDistributedForAddress(address)` - are reserved tokens distributed to this address or not. Returns `true` or `false`
2. `getReservedTokens(address)` - returns how many tokens are reserved for this address in tokens * 10^token_decimals
3. `getReservedPercentageUnit(address)` - returns how many tokens are reserved in percents * 10^percentage_decimals_amount_in_percents. If you reserved integer amount in percents, then `getReservedPercentageUnit(address)` will return this amount
4. `getReservedPercentageDecimals(address)` - returns how many decimals in percents of reserved tokens. For, example, if you reserved 10,51%, it will return 2.
