### ISSUE TITLE
please assist me

### ISSUE THREAD

**Issue by SoccerCoins** [poanetwork/token-wizard#892]
hi

I am trying to validate my token  wizard contract here: https://etherscan.io/verifyContract

Having some issues is there a guide somewhere i can use please?

also can tokens be bought directly from the contract address here: 

0xe33a11ae66f8a17f7bbfb3b7d7b1d60a18970379

again is there a guide and if they are bought directly will the bonus amounts apply or must it go through the wizard
--

**Comment by vbaranov** [comment]
Verification guide:
https://github.com/poanetwork/token-wizard/wiki/Token-Wizard-Verifying-Contracts

Contribution guide:
https://github.com/poanetwork/token-wizard/wiki/Contribution-to-crowdsale

FAQ section:
https://github.com/poanetwork/token-wizard/wiki/FAQ

If anything is unclear use [Token wizard gitter](https://gitter.im/poanetwork/ico-wizard) to ask your questions
