### ISSUE TITLE
(Feature) Enable mincap modifying  if whitelisting enabled 

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#912]
#### Problem:  ####
Now tiers have individual whitelist disable/enable option but mincap remains common for all tiers.
Global mincap modifying disabled  and mincap is zero if whitelisting is enabled for any tier. 
 As a result all tiers without whitelisting have mincap = 0

#### Solution: ####
 Enable global mincap modifying if whitelist enabled for any tier. Other way is make the individual mincap for each tier

**Comment by vbaranov** [comment]
Depends on Auth_os update

**Comment by fernandomg** [comment]
As of the changes introduced in #973, Dutch Auction will behave as stated in the [auth-os readme](https://github.com/auth-os/applications/tree/master/TokenWizard/crowdsale/DutchCrowdsale):

> `ConfigureSale.updateGlobalMinContribution`: Allows the admin to define a minimum purchase size during the sale. Purchasers that have not already participated will need to buy this amount at a minimum.

.

Same for [Minted Capped strategy](https://github.com/auth-os/applications/tree/master/TokenWizard/crowdsale/MintedCappedCrowdsale):

> `ConfigureSale.updateTierMinimum`: If the targeted tier was configured to allow updates, this function will allow the sale admin to update a tier's minimum purchase size. Any purchaser during the targeted tier, if they have not already purchased in the sale, must purchase at a minimum the amount of tokens set here. The targeted tier must not be the current tier, or an already-passed tier.


---
That being said, this PR should be closed after #973 merge.
