### ISSUE TITLE
(Bug) Minted-Multitier: Can't modify next tier if previous tier  has began

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#914]
Test URL : localhost with latest commit of branch 2.0 : https://github.com/poanetwork/token-wizard/commit/962130704e30e1a8b49bd97bc385f8f231b5639f

Steps:
1. Create crowdsale with 3 tiers, allow modify and whitelist for each tier
2. Wait until 2nd tier begins
3. Open manage page as an owner and try to add whitelist (or change end time)

Expected result:
 - owner should be able modify tier before its start

Actual result:
 - owner can't  modify 3rd tier if 2nd tier has began, but it is possible if  only 1st tier has began
 - error message (see movie)
 - transaction reverted (Tx: https://ropsten.etherscan.io/tx/0x9772b0f434dc93814b0b3e93bc1982a592c0579f0929e4deb1b968dd104adf1a)

Exec ID : 0x899b3b16bb1e6c37ae3de9c5c189f25ae322ed8ee643f6ef0edfe32bcf750e0b

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/invest?exec-id=0x899b3b16bb1e6c37ae3de9c5c189f25ae322ed8ee643f6ef0edfe32bcf750e0b&networkID=3*

### Do you have screenshots showing the problem?

*https://drive.google.com/open?id=1TOKDHnaaiV2-u2Nd78WTn5EU3435syL3*

<img width="1440" alt="screen shot 2018-05-24 at 17 32 18" src="https://user-images.githubusercontent.com/14067096/40520106-92feaf66-5f78-11e8-8e72-bef187b1d898.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment]
I faced with the same bug. Should be fixed at Auth_os application side.

**Comment by vbaranov** [comment]
@dennis00010011b could we close it? It should work in 2.0.
