### ISSUE TITLE
(Bug)Minted-Manage page: incorrect initialization of end time for 2nd tier

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#919]
Test URL: localhost with PR https://github.com/poanetwork/token-wizard/pull/915

Steps:

1. Create crowdsale
2. Open manage page as an owner
3. Change end time of 1 tier for 5 minute later than start time.
4. Submit two transaction

Actual result:
  - end time of 2nd tier earlier than end time of 1st tier

Crowdsale parameters
```
{
"name": "scenarioE2eMintedWhitelist",
"ticker": "test",
"decimals": 18,
"reservedTokens":[
{
"address" :"0xecDFec71AbCD5a612eAf9169B19E907eAA2717d9",
"dimension": "percentage",
"value": 250
},
{
"address" : "0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
"dimension": "tokens",
"value":100000000
}
],
"walletAddress":"0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
"gasprice": 1,
"mincap": 1,

"tiers":[
{
"name":"###1",
"allowModify": true,
"isWhitelisted":true,
"startDate": "1600000",
"startTime": "16600000",
"endDate":"23/02/2050",
"endTime":"12:34",
"rate":20000,
"supply": 250,
"whitelist":[
{
"address": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
"min": 50,
"max": 150
},
{
"address": "0x9E963042D581D262AdE4E31541360e7FDAeE70C6",
"min": 50,
"max": 150
}]},
{
"name":"###2",
"allowModify": true,
"isWhitelisted":true,
"startDate": "",
"startTime": "",
"endDate":"",
"endTime":"",
"rate":10000,
"supply": 200,
"whitelist":[
{
"address": "0xdDdC96314b7f16cB243Cb07e1dE081CA367095E7",
"min": 25,
"max": 250
}]}]}
```
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*Exec ID: 0x7193beb3acd157734871e1c53d15497167af16b8ee9c9996581a58444503c3a3*

### Do you have screenshots showing the problem?

<img width="1440" alt="40557298-89327d82-6004-11e8-8de8-17f4623f9537" src="https://user-images.githubusercontent.com/14067096/40597225-fa4a210e-61f4-11e8-877d-601deaadc8c8.png">

<img width="1440" alt="40558392-06ca1c02-6008-11e8-843b-72fa7c4467b8" src="https://user-images.githubusercontent.com/14067096/40597226-fc26368e-61f4-11e8-975a-2c5598143289.png">

### Do you see errors in the dev console? If yes, please include a screenshot

*No*
---

**Comment by vbaranov** [comment]
@dennis00010011b I can't repeat this issue. Could you repeat it with the latest code? Btw, `startDate`, `startTime` and `endDate`, `endTime` are empty for the 2nd tier in your config. Maybe, this could cause the issue?

**Comment by dennis00010011b** [comment]
@vbaranov 
Issue  still reproducible. Ropsten, exec ID: 0x2a655b2fc213c39a5039536ee346543c115d284f48949d24357be8d411f3e0eb
<img width="1440" alt="screen shot 2018-05-28 at 11 38 32" src="https://user-images.githubusercontent.com/14067096/40626212-df1f45fe-626b-11e8-8da8-792ca11be2df.png">

You can open manage page as an owner, private key: ba98116a7d4b98f22f113c59448b9cc69f916d75f35d51f088b64b483fd0b8ca

Empty value of start/end time means values by default
Value like '360000' means an adjust 360000ms  from current moment

**Comment by dennis00010011b** [comment]
@vbaranov 
I reproduced it again .
``` ExecID:0x12447769c20f74d47572d99647f69b5eea0095531fd6508df5d3a87a2c51b7ff, Ropsten```

Record:
https://drive.google.com/open?id=1uk7ypwYwQxmi__o_k1ZoWVIi5Ai3qU1L
