### ISSUE TITLE
(Bug) Dutch-Publish page: total supply is displayed in wei

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#928]
total supply should be  displayed in tokens

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*ganache*

### If you were able to create it, what is the URL of your crowdsale?

*ganache*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-29 at 16 16 04" src="https://user-images.githubusercontent.com/14067096/40690427-e19d6752-635b-11e8-97b4-2100396f06f1.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No

---

**Comment by vbaranov** [comment]
@dennis00010011b please check it once more. I can't reproduce it. This field displays the value from step 2 of Wizard from token total supply input.

**Comment by dennis00010011b** [comment]
not reproducible
