### ISSUE TITLE
(Bug) Dutch with minCap: investor can't buy maxCap

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#929]
Steps:

1.Create crowdsale with parameters
```
{
  "name": "scenarioE2eDutchMincapLongjson",
  "ticker": "test",
  "decimals": 18,
  "totalSupply":1000,
  "walletAddress":"0xdDdC96314b7f16cB243Cb07e1dE081CA367095E7",
  "gasprice":1,
  "whitelisting":false,
  "mincap": 100,
  "tiers":[
    {
      "startDate": "120000",
      "startTime": "120000",
      "endDate":"23/02/2050",
      "endTime":"12:34",
      "minRate":100,
      "maxRate":1000,
      "supply": 500,
      "whitelist":[]
    }]
}
```
2. Set up in Metamask any account other than owner's account. 
3. Buy amount=minCap
4. Buy amount=maxCap

Expected result:
 - token balance should be equal maxCap

Actual result:
 - token balance is fractional and less than maxCap
 - investor can't buy more tokens
 - ****owner is not able to finalize the crowdsale and should wait until crowdsale time will over****

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
*Ganache*

### If you were able to create it, what is the URL of your crowdsale?

*Ganache*

### Do you have screenshots showing the problem?
<img width="1440" alt="screen shot 2018-05-29 at 16 29 56" src="https://user-images.githubusercontent.com/14067096/40691087-21f5fe1a-635f-11e8-8463-4fb31141ba3c.png">

<img width="1440" alt="screen shot 2018-05-29 at 16 30 02" src="https://user-images.githubusercontent.com/14067096/40691092-27db2170-635f-11e8-9e77-d522ba71d447.png">

<img width="1440" alt="screen shot 2018-05-29 at 16 30 18" src="https://user-images.githubusercontent.com/14067096/40691096-2bbbf4d6-635f-11e8-8f8a-30ad1de68848.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No

---

**Comment by vbaranov** [comment]
@dennis00010011b is it reproducible with the new Auth-os Registry [v 1.0.1](https://github.com/auth-os/core/releases/tag/1.0.1)? It is implemented in `2.0` branch of Token Wizard
