### ISSUE TITLE
Please help to distribute reserved tokens 

### ISSUE THREAD

**Issue by lrk1234** [poanetwork/token-wizard#936]
https://wizard.poa.network/manage/0x94DBc0ad6961523ced9281ea336a420e2f633337
Contract  0xe5f4D463976a2baA7d0e4245C2D1FFDAEbB3E6dA
On manage page apiered only Finalize buton - Finalization is the last step of the crowdsale. You can make it only after the end of the last tier. After finalization, it's not possible to update tiers, buy tokens. All tokens will be movable, **reserved tokens will be issued**

**Comment by vbaranov** [comment]
It is not clear what is your issue. The issue created without using a template. 
Use gitter chat for questions: https://gitter.im/poanetwork/ico-wizard
Token Wizard FAQ: https://github.com/poanetwork/token-wizard/wiki/FAQ
