### ISSUE TITLE
(Feature) display 3 prices for Crowdsale page for Dutch Auction strategy

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/token-wizard#938]
**Problem**: crowdsale page displays only current price of the token. It could be useful to see start and end prices also.
**Solution**: display start and end prices of crowdsale in the crowdsale page as well

**Comment by fernandomg** [comment]
@vbaranov As I understand it is displayed as _price_ is how many tokens can be bought per ETH.

I ended up with a layout, that may respect the concepts but I need confirmation:

**Dutch Auction**
![image](https://user-images.githubusercontent.com/3315606/42237253-a7dc9b58-7ed3-11e8-9bc1-f3cc79725082.png)


Or we can replace 'Price' with 'Rate' to make it less confusing and display only one value.

@dennis00010011b thoughts?

**Comment by vbaranov** [comment]
@fernandomg I like this layout, but in the new layout for TW 2.0 redesign, the rates will be displayed over the tickers on the scale. I think display both price and rate will overload the page.

>Or we can replace 'Price' with 'Rate' to make it less confusing and display only one value.

This one looks more preferable to me
