### ISSUE TITLE
(Bug) Whitelisted address can not buy (if was added to 2nd tier before deployment)

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#943]
Test URL: localhost with latest commit https://github.com/poanetwork/token-wizard/commit/fcdc8939ab46bfd41cf6bb7f3a3ff8d611a0b0a6 branch 2.0 

Steps:
 1. Create crowdsale (see below) with parameters: 2 tiers, whitelisted
 2. Wait until 2nd tier will start
 3. Try to buy from whitelisted addresses which added in tier #2 
 4. Observe Contribution page, minCap section 

Expected result:
 - whitelisted address , which was added before deployment, should be able to buy

Actual result:
 - whitelisted address (which was added before deployment) isn't  allowed to buy
 - whitelisted addresses (which were added from manage page)  are allowed to buy
 
Exec ID: ```0x24561c459eb75687c20e605ac55162ba6bf37c3e8a12cfac45de4462570f99dd```

```
{
  "name": "scenarioE2eMintedWhitelist",
  "ticker": "test",
  "decimals": 18,
  "reservedTokens":[
    {
      "address" :"0xecDFec71AbCD5a612eAf9169B19E907eAA2717d9",
      "dimension": "percentage",
      "value": 250
    },
    {
      "address" :  "0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
      "dimension": "tokens",
      "value":100000000
    }
  ],
  "walletAddress":"0x56B2e3C3cFf7f3921Dc2e0F8B8e20d1eEc29216b",
  "gasprice": 100,
  "mincap": 1,
  "tiers":[
    {
      "name":"###1",
      "allowModify": true,
      "isWhitelisted":true,
      "startDate": "360000",
      "startTime": "360000",
      "endDate":"500000",
      "endTime":"500000",
      "rate":20000,
      "supply": 250,
      "whitelist":[
        {
          "address": "0xF16AB2EA0a7F7B28C267cbA3Ed211Ea5c6e27411",
          "min": 50,
          "max": 150
        },
        {
          "address": "0x9E963042D581D262AdE4E31541360e7FDAeE70C6",
          "min": 50,
          "max": 150
        }
      ]
    },
    {
      "name":"###2",
      "allowModify": true,
      "isWhitelisted":true,
      "startDate": "",
      "startTime": "",
      "endDate":"",
      "endTime":"",
      "rate":10000,
      "supply": 200,
      "whitelist":[
        {
          "address": "0xdDdC96314b7f16cB243Cb07e1dE081CA367095E7",
          "min": 25,
          "max": 250
        }]}]}
```

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/contribute?exec-id=0x24561c459eb75687c20e605ac55162ba6bf37c3e8a12cfac45de4462570f99dd&networkID=3*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-06-06 at 20 52 43" src="https://user-images.githubusercontent.com/14067096/41077842-e7c3b4d8-69cd-11e8-8b89-11f2838b1d1d.png">
<img width="1440" alt="screen shot 2018-06-06 at 20 53 13" src="https://user-images.githubusercontent.com/14067096/41077847-e9c9a512-69cd-11e8-933a-da0c0c888e00.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No

---

**Comment by fernandomg** [comment]
@dennis00010011b @vbaranov 

Method to calculate user's contribution is based on the information provided by [`getCurrentTierInfo`](https://github.com/auth-os/applications/blob/100b3b081e8fb5f8f678a38413350d73151ed95b/TokenWizard/crowdsale/MintedCappedCrowdsale/contracts/init/InitCrowdsale.sol#L368), which is returning the first tier despite it has already ended.

![image](https://user-images.githubusercontent.com/3315606/41110121-015e2df2-6a4f-11e8-965c-860a8796f74c.png)

This can be fixed estimating ourselves what's the current tier (you can see that that's working fine in the countdown timer), but I rather prefer not and fix `getCurrentTierInfo` mehtod instead.

**Comment by vbaranov** [comment]
@dennis00010011b it was fixed in Auth-os. I have no such issue anymore. Could you confirm, that issue is eliminated?
