### ISSUE TITLE
(Bug) Dutch_Contribution page: wrong minCap value displayed for owner

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#965]
Expected result: min contribution for owner should be equals crowdsale's minCap 
Actual result:
 - actually owner is not allowed to buy less than minCap in first transaction 
 -  since the owner has already received tokens (totalSupply-tierSupply) then displayed minimum contribution incorrect

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten, 0x3ae797ceef265e3a4f9c1978c47c759eb34a32909251dee7276db339b17b3de3*

### If you were able to create it, what is the URL of your crowdsale?

*http://localhost:3000/contribute?exec-id=0x3ae797ceef265e3a4f9c1978c47c759eb34a32909251dee7276db339b17b3de3&networkID=3*

### Do you have screenshots showing the problem?
<img width="1440" alt="screen shot 2018-06-18 at 13 16 48" src="https://user-images.githubusercontent.com/14067096/41560344-a585c4c6-72fb-11e8-87b3-f914c700ffa0.png">

### Do you see errors in the dev console? If yes, please include a screenshot

No

---

**Comment by vbaranov** [comment]
@dennis00010011b I believe there are no real cases, when the owner will participate in a crowdsale with contribution lower than min cap or participate in a crowdsale at all. I guess we could neglect this issue.
