### ISSUE TITLE
(Bug) Incorrect value of maxCap for whitelisted. minCap is displayed instead

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#974]
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)
Ropsten

### If you were able to create it, what is the URL of your crowdsale?
`0x16f21ac37b56997ba556a8b2bd0791fd3bfa236fdc2ba42c1d24c788029bb19e`

### Do you have screenshots showing the problem?
See: https://github.com/poanetwork/token-wizard/pull/973#issuecomment-399588201

### Do you see errors in the dev console? If yes, please include a screenshot
No

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.
-
---

**Comment by mariano-aguero** [comment]
Currently it is working fine
I was searching among the commits of the last week, I did not find one in particular that modifies the functionality.

Steps to try to reproduce the problem
- Create a new crowdsale
- Select the strategy
- Complete the fields in step 2
- Complete the fields in step 3, enable whitelist
- Wait for transaction in step 4
- Manage the created crowsale, the whitelist list must be displayed correctly

@fernandomg can you confirm this? If it is functioning properly I close the issue

![token wizard_ - http___localhost_3000_manage_0x5929](https://user-images.githubusercontent.com/1144028/42170711-b4779dfe-7ded-11e8-96ca-67fff3e3b070.png)

**Comment by dennis00010011b** [comment]
@mariano-aguero Issue is not reproducible anymore
