### ISSUE TITLE
(Bug) Contribution confirmation popup

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#986]
Popup is displaying the amount entered by the user, instead of the actual amount bought

**Comment by vbaranov** [comment]
@fernandomg for which type of crowdsale you faced with this problem? We were fixing this issue in frames of https://github.com/poanetwork/token-wizard/issues/847 and https://github.com/poanetwork/token-wizard/issues/872

**Comment by fernandomg** [comment]
@vbaranov mintedCapped was
